In [1]:
import pandas as pd

In [2]:
#inputToRead = "/home/j/git/OSL/ETL1-Pipeline/data/inputs/new/mockito_full/mockito_full_commit_output.csv"
inputToRead = "/Users/fd252/OneDrive/Production/ETL1-Pipeline-main/data/inputs/new/cronos/Fabio/historico_cronos_anonymized_cronos.csv"

In [3]:
#fileNameOutput = "/home/j/git/OSL/ETL1-Pipeline/data/outputs/new/mockito/dataframe_file_names.csv"
fileNameOutput = "/Users/fd252/OneDrive/Production/ETL1-Pipeline-main/data/outputs/new/cronos/dataframe_file_namesV2.csv"

In [4]:
#PR3_csv = "/home/j/git/OSL/ETL1-Pipeline/data/outputs/new/g/filesPR3BodyTitle2.csv"
PR3_csv = "/Users/fd252/OneDrive/Production/ETL1-Pipeline-main/data/outputs/new/cronos/filesPR3BodyTitle2V2.csv"

In [5]:
#PR3_txt = "/home/j/git/OSL/ETL1-Pipeline/data/outputs/new/guava/filesPR3BodyTitle2.txt"
PR3_txt = "/Users/fd252/OneDrive/Production/ETL1-Pipeline-main/data/outputs/new/cronos/filesPR3BodyTitle2V2.txt"

In [7]:
authorFilePath = pd.read_csv(inputToRead)

In [8]:
authorFilePath.head()

,revisao,ramo,pai,etiqueta,data,descricao,arquivos
0,MTT-1087,3294:f210d85e13dd,NaN,tip,Fri Jun 18 12:24:29 2021 -0300,https://intranet.mindsatwork.com.br/jira/brow...,src/main/webapp/scripts/listReportLogged...
1,MTT-1073,3293:073e173f89ac,NaN,NaN,Fri Jun 18 10:03:42 2021 -0300,[maven-release-plugin] prepare for next devel...,pom.xml
2,MTT-1073,3292:e7b3bb86e7db,NaN,NaN,Fri Jun 18 10:03:41 2021 -0300,[maven-release-plugin] copy for tag v2021-06-...,.hgtags
3,MTT-1073,3291:fb923c815ae3,NaN,v2021-06-18_13-02-32-RELEASE-(1.14.5),Fri Jun 18 10:03:40 2021 -0300,[maven-release-plugin] prepare release v2021-...,pom.xml
4,MTT-1073,3290:a5409e47a821,3253:070789a0c2ae,NaN,Fri Jun 18 09:28:17 2021 -0300,https://intranet.mindsatwork.com.br/jira/brow...,docs/database/db-mtt-V034-V035.sql src/m...

In [9]:
authorFilePath.shape

(1481, 7)

In [44]:
authorFilePath = authorFilePath[authorFilePath.status == 'MERGED']

In [45]:
authorFilePath.columns

Index(['repository', 'status', 'commit_date', 'multi_patch', 'branch',
       'changed_file', 'change_id', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'tracking_id', 'tracking_id2', 'tracking_id3', 'tracking_id4',
       'tracking_id5', 'tracking_id6', 'tracking_id7', 'tracking_id8',
       'tracking_id9', 'tracking_id10'],
      dtype='object')

In [46]:
authorFilePath.shape

(19479, 20)

In [47]:
authorFilePath.dtypes

repository        object
status            object
commit_date       object
multi_patch        int64
branch            object
changed_file      object
change_id         object
Unnamed: 7       float64
Unnamed: 8       float64
Unnamed: 9       float64
tracking_id       object
tracking_id2      object
tracking_id3      object
tracking_id4      object
tracking_id5      object
tracking_id6      object
tracking_id7      object
tracking_id8      object
tracking_id9      object
tracking_id10     object
dtype: object

In [48]:
authorFilePath2 = authorFilePath.copy()

In [49]:
authorFilePath2.columns

Index(['repository', 'status', 'commit_date', 'multi_patch', 'branch',
       'changed_file', 'change_id', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'tracking_id', 'tracking_id2', 'tracking_id3', 'tracking_id4',
       'tracking_id5', 'tracking_id6', 'tracking_id7', 'tracking_id8',
       'tracking_id9', 'tracking_id10'],
      dtype='object')

In [50]:
authorFilePath2.loc[0:30,"changed_file"]

0     restserviceimpl/base/src/main/java/com/ericsso...
1     entitymodificationimpl/src/test/java/com/erics...
2     integrationtest/componenttestcases/src/test/ja...
3     integrationtest/componenttestcases/src/test/ja...
4     entitymodificationimpl/src/main/java/com/erics...
5     entitymodificationimpl/src/main/java/com/erics...
6     ui/rmcavaluebuilder/src/rmcavaluebuilder/value...
8     entitymodificationimpl/src/test/java/com/erics...
9     importexport/impl/src/main/java/com/ericsson/b...
10    restserviceimpl/restinternal/src/main/java/com...
11    restproxy/impl/src/main/java/com/ericsson/bss/...
12    validation/src/main/java/com/ericsson/bss/rmca...
13    utilities/src/test/java/com/ericsson/bss/rmca/...
14    entitymodificationviews/src/main/java/com/eric...
15    restserviceimpl/restinternal/src/main/java/com...
16    ui/rmcavaluebuilder/src/rmcavaluebuilder/value...
17    ui/rmcaproductspecificationviews/test/unit/Det...
18    ui/rmcavaluebuilder/src/rmcavaluebuilder/value...
19    entityserviceviews/src/main/java/com/ericsson/...
20    entitymodificationimpl/src/main/java/com/erics...
21    entitymodificationimpl/src/test/resources/rule...
22                               oamservices/fc/pom.xml
25    restserviceimpl/restinternal/src/test/java/com...
26    restproxy/impl/src/test/java/com/ericsson/bss/...
27    integrationtest/testcases/src/test/java/com/er...
28    integrationtest/componenttestcases/src/test/ja...
29    entitymodificationimpl/src/test/java/com/erics...
Name: changed_file, dtype: object

In [51]:
#authorFilePath2.loc[0:30,"trouble_report_id"]
authorFilePath2.loc[0:30,"tracking_id"]

0     HX90744
1     HX91715
2     HY60437
3     HY18902
4     HX86471
5     HY48964
6     HY71789
8     HY53290
9     HY46587
10    HY27847
11    HY51063
12    HY40467
13    HY77118
14    HY53290
15    HX85100
16    HY66573
17    HX68141
18    HY66573
19    HY48964
20    HY56644
21    HX66324
22    HX77827
25    HX93518
26    HX84834
27    HX90744
28    HY43069
29    HY53290
Name: tracking_id, dtype: object

In [52]:
#v2 I removed commas (","), "TR:", "SCM", "SCM "
#v2 has multiple id inside one column. So, I splitted them in many columns like, id2, id3... id10

In [53]:
#id_without_SCM = authorFilePath2.trouble_report_id.str.replace("SCM ","")
id_without_SCM = authorFilePath2.tracking_id.str.replace("SCM ","")

In [54]:
#id_without_SCM_TR = id_without_SCM.str.replace("TR:","")
id_without_SCM_TR = id_without_SCM.str.replace("TR:","")

In [55]:
type(id_without_SCM_TR)

pandas.core.series.Series

In [56]:
#file_names_without_brackets2 = file_names_without_quotes.str.replace("]","")

In [57]:
id_without_SCM_TR.head()

0    HX90744
1    HX91715
2    HY60437
3    HY18902
4    HX86471
Name: tracking_id, dtype: object

In [58]:
authorFilePath["trid"] = id_without_SCM_TR

In [59]:
#dataframe_file_names = authorFilePath.files.str.split(",", expand=True)

In [60]:
#dataframe_file_names["pr"] = authorFilePath["Issue_Num"]

In [61]:
authorFilePath["trid"].head()

0    HX90744
1    HX91715
2    HY60437
3    HY18902
4    HX86471
Name: trid, dtype: object

In [62]:
authorFilePath.columns

Index(['repository', 'status', 'commit_date', 'multi_patch', 'branch',
       'changed_file', 'change_id', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'tracking_id', 'tracking_id2', 'tracking_id3', 'tracking_id4',
       'tracking_id5', 'tracking_id6', 'tracking_id7', 'tracking_id8',
       'tracking_id9', 'tracking_id10', 'trid'],
      dtype='object')

In [63]:
#authorFilePath["trouble_report_id"] = authorFilePath["trid"]
authorFilePath["tracking_id"] = authorFilePath["trid"]
authorFilePath.columns

Index(['repository', 'status', 'commit_date', 'multi_patch', 'branch',
       'changed_file', 'change_id', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'tracking_id', 'tracking_id2', 'tracking_id3', 'tracking_id4',
       'tracking_id5', 'tracking_id6', 'tracking_id7', 'tracking_id8',
       'tracking_id9', 'tracking_id10', 'trid'],
      dtype='object')

In [64]:
files_list3 = []

def filter_java3(lines):
 
    for i, v in lines.items():
        
        #trouble_report_id = lines["trouble_report_id"]
        trouble_report_id = lines["tracking_id"]
        
        #v = lines["java"]
        
        commit_date = lines["commit_date"]
        
        #pull_request_id = lines["pull_request_id"]
        pull_request_id = lines["change_id"]
        #body = str(lines["body"])
        #type(body)
        #print(body)
        #body = body.replace("\n", " ") #.str.replace
        #body = body.replace("\"", " ")
        #body = body.replace("\'", " ")
        #body = body.replace("`", " ")
        #body = body.replace(";", " ")
        #body = body.replace(",", " ")
        
        #title = lines["title"]
        #title = title.replace("\n", " ")
        #title = title.replace("\"", " ")
        #title = title.replace("\'", " ")
        #title = title.replace("`", " ")
        #title = title.replace(";", " ")
        #title = title.replace(",", " ")
        #print("Lines:",i, lines["pr"])
        if v is not None:
            if type(v) == str:
                #if i == "trouble_report_id" or i == "commit_date" or i == "pull_request_id" or i == "trid": 
                if i == "tracking_id" or i == "commit_date" or i == "pull_request_id" or i == "trid": 
                    pass
                else:
                    if (v.find('.java') != -1): 
                        print("write pr:", trouble_report_id," java:",v)

                        #dict1 = {}
                        # get input row in dictionary format
                        # key = col_name
                        #d = {pr:v}
                        #dict1.update(d) 

                        #files_list3.append(dict1)
                        data = trouble_report_id,";",v,";",commit_date,";",pull_request_id
                        data = trouble_report_id,";",v,";",commit_date,";",pull_request_id
                        print("data:", data)
                        files_list3.append(data)
                    #else:
                        #print("not a java file:",v, " idx", i)
            #else:
                #print("not a String:", v, " idx", i)
        #else:
            #print("None:", v, " idx", i)

In [65]:
authorFilePath.apply(filter_java3, axis=1)

write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSUriWhitelist.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSUriWhitelist.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedTagSetSpecificationProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedTagSetSpecificationProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY60437  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HY60437', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY18902  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestActivationDependency_UseCase.java
data: ('HY18902', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestActivationDependency_UseCase.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '7/3/20 17:22', ';', 'I04c3cbb7b1907e97150470c4ca5c43f479ebf22c')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestLockTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestLockTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/BucketPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/BucketPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY27847  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/PermissionStrategyRuleConverter.java
data: ('HY27847', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/PermissionStrategyRuleConverter.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HY40467  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/MoveRecurrenceWithAllowanceHook.java
data: ('HY40467', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/MoveRecurrenceWithAllowanceHook.java', ';', '5/6/20 7:36', ';', 'Ibc8481b4c2fbcafea55bb98d63997221ad9c40e0')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY53290  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/TransactionLockException.java
data: ('HY53290', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/TransactionLockException.java', ';', '7/28/20 13:10', ';', 'I4d41599ba9fe98cfd0e66f307918ca60c90ce420')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/LockPageTransactionImpl.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/LockPageTransactionImpl.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY48964  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HY48964', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/EntityConverterUtilities.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/EntityConverterUtilities.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HX93518  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationDetails.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationDetails.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')
write pr: HX84834  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java
data: ('HX84834', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java', ';', '8/19/19 7:55', ';', 'Iabadeb3cf769a9c60059ca4c04eb8d4536c5c632')
write pr: HX90744  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java
data: ('HX90744', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY43069  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY43069', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '5/20/20 18:33', ';', 'I679551f00a74c7c9d676970107ef617630af0112')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketPriorityListCleanupForBillingAccountSpecificationTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketPriorityListCleanupForBillingAccountSpecificationTask.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HY53290  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/TestIdentifiedTaskExecutorServiceImpl.java
data: ('HY53290', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/TestIdentifiedTaskExecutorServiceImpl.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY24150  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY60135  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HY60135', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '9/1/20 11:58', ';', 'Ia8f587ad2d24ca59f2cac902d773f42291647188')
write pr: HX65525  java: restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java
data: ('HX65525', ';', 'restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY43705  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/TestRefillSendExternalNotificationConverter.java
data: ('HY43705', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/TestRefillSendExternalNotificationConverter.java', ';', '5/20/20 8:56', ';', 'I2d85a2de97585e405042f92048da30836f514228')
write pr: BSUC:FT8-15:4  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ErrorMapKey.java
data: ('BSUC:FT8-15:4', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ErrorMapKey.java', ';', '7/27/20 6:54', ';', 'I0d6c6f576cb0813ff8bb9bc9f0dbd085ead415a0')
write pr: HY18902  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/UpstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/UpstreamDependencyAnalyzer.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY40790  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedRefillBusinessStrategyProvider.java
data: ('HY40790', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedRefillBusinessStrategyProvider.java', ';', '5/5/20 8:18', ';', 'I62bd89465d6fd12133d7d4072e17e560252eb873')
write pr: HX77477  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/TestBucketBalance.java
data: ('HX77477', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/TestBucketBalance.java', ';', '7/9/19 11:01', ';', 'Ia4274b0770ee49bbe0a2e843e8c33b5128b8a0db')
write pr: HX93518  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/ResourceFacingServiceSpecificationDetails.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/ResourceFacingServiceSpecificationDetails.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')
write pr: HY24061  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecificationProvider.java
data: ('HY24061', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecificationProvider.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListDataMigration.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListDataMigration.java', ';', '7/28/20 11:41', ';', 'I54f5f21378cb0d1b30404844cea865cc5b54df1c')
write pr: BSUC:FT8-15  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('BSUC:FT8-15', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '7/21/20 9:36', ';', 'I2e24c3a89e0945ebb31a235f7d7e8bbc39e23983')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBucketTagBucketPriorityListManagement.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBucketTagBucketPriorityListManagement.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HX94284  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/characteristicsetspecification/CharacteristicSetSpecificationPageConverter.java
data: ('HX94284', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/characteristicsetspecification/CharacteristicSetSpecificationPageConverter.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '7/17/20 6:33', ';', 'I139d281c30cd4f4b3a7f6b59b1207ec62962c014')
write pr: HY45357  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY45357', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '6/8/20 12:33', ';', 'I009b1911b8212d1c89d4182790c57a697436a82c')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/EtdPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/EtdPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HX86471  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java
data: ('HX86471', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/EtdPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/EtdPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HX86471  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java
data: ('HX86471', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY39316  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/AgreementRealizationItemSpecificationConverter.java
data: ('HY39316', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/AgreementRealizationItemSpecificationConverter.java', ';', '4/30/20 12:16', ';', 'Ia281a738a056930d1ff0925c90a9c7990a5a506f')
write pr: HY59800  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/NewVersionPageQueryImpl.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/NewVersionPageQueryImpl.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HX92381  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityChangeService_ITCase.java
data: ('HX92381', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityChangeService_ITCase.java', ';', '9/26/19 14:23', ';', 'I9f8a674f3f3862391e5eba16e40f650149c284ab')
write pr: HY71789  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/CarryOverProductBucketActionValidationRule.java
data: ('HY71789', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/CarryOverProductBucketActionValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY26947  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY26947', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '2/18/20 11:29', ';', 'I2ebd4be614e40e333277f096794a90fee278417f')
write pr: HY46749  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/Provision.java

write pr: HY45357  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HY45357', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '6/10/20 21:48', ';', 'I8399574367251439d12833436b39bce38357bdb2')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedBillingAccountHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedBillingAccountHelper.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HX99743  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/creationcontext/rfss/TestRestResourceFacingServiceSpecificationCreationContextImpl.java
data: ('HX99743', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/creationcontext/rfss/TestRestResourceFacingServiceSpecificationCreationContextImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HY21738  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProvider.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProvider.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HY18074  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HY18074', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '12/16/19 10:12', ';', 'I4f3f6e4752d389bdfb0ea92e5aac90d22d650274')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY60708  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java
data: ('HY60708', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HX66324  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java
data: ('HX66324', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java', ';', '5/16/19 20:20', ';', 'Ie3ad0574aed45eae4316e0bc9a1e217254caaf67')
write pr: HY60437  java: integrationtest/common/src/main/java/com/ericsson/bss/rmca/integrationtest/common/ExportAsserter.java
data: ('HY60437', ';', 'integrationtest/common/src/main/java/com/ericsson/bss/rmca/integrationtest/common/ExportAsserter.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY24973  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/networkpolicycounterspecification/NetworkPolicyCounterDisallowRelativeSharingLimitBucketsValidationRule.java
data: ('HY24973', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/networkpolicycounterspecification/NetworkPolicyCounterDisallowRelativeSharingLimitBucketsValidationRule.java', ';', '2/6/20 16:02', ';', 'I11bab099dc1090d8b48e7bc07843b06bd5d1aebc')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/NetworkPolicyCounterStatusValueSpecificationImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/NetworkPolicyCounterStatusValueSpecificationImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponseHelper.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponseHelper.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY43069  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestChargingCapabilityViewImpl.java
data: ('HY43069', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestChargingCapabilityViewImpl.java', ';', '5/20/20 18:33', ';', 'I679551f00a74c7c9d676970107ef617630af0112')
write pr: HX77477  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java
data: ('HX77477', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java', ';', '7/9/19 11:01', ';', 'Ia4274b0770ee49bbe0a2e843e8c33b5128b8a0db')
write pr: HY60256  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java
data: ('HY60256', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java', ';', '9/2/20 6:41', ';', 'Ie8e407477721eddb52665e680fae135d1a3f9003')
write pr: HY62744  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY62744', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '9/22/20 12:18', ';', 'Id4683d1052a07df9356af7a331089abe25e06324')
write pr: HY64004  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeUtils.java
data: ('HY64004', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeUtils.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY64004  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HX85100  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageToEntityMapper.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageToEntityMapper.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY46854  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HX74509  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/AbstractTieredConditionConverter.java
data: ('HX74509', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/AbstractTieredConditionConverter.java', ';', '6/19/19 6:15', ';', 'I9b834546f9a32ad7dba545810d206b399d0b34ad')
write pr: HX83389  java: cli/imports/src/main/java/com/ericsson/bss/rmca/cli/imports/provisioning/JsonProvisioner.java
data: ('HX83389', ';', 'cli/imports/src/main/java/com/ericsson/bss/rmca/cli/imports/provisioning/JsonProvisioner.java', ';', '8/29/19 13:01', ';', 'I44a3f2f2f37bfabe01fe5cb7a8196a513f2a69c9')
write pr: HX66324  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketSetRecurrenceHook.java
data: ('HX66324', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketSetRecurrenceHook.java', ';', '5/16/19 20:20', ';', 'Ie3ad0574aed45eae4316e0bc9a1e217254caaf67')
write pr: HX84747  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestCounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestCounterConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HY17608  java: oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/internal/TestAlarmHolder.java
data: ('HY17608', ';', 'oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/internal/TestAlarmHolder.java', ';', '12/11/19 11:16', ';', 'I81823a0a5a65ea1a2b66caa543737e2b0cdc2abe')
write pr: HX87622  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/TestBucketPriorityListToPageConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/TestBucketPriorityListToPageConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '6/8/20 18:37', ';', 'I83a8d3f388c393bb2d9836cac3f723fd33c7ecb4')
write pr: HY21740  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ProductOfferingPriceSpecificationHelper.java
data: ('HY21740', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ProductOfferingPriceSpecificationHelper.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY18902  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/AbstractGraphDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/AbstractGraphDependencyAnalyzer.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY30739  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/LifecycleSpecificationValidationRuleProvider.java
data: ('HY30739', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/LifecycleSpecificationValidationRuleProvider.java', ';', '3/10/20 8:55', ';', 'Ic262489ea61211040cebb42666f8d928ef3346cf')
write pr: HX80786  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: BSUC:FT12-1  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/of/TestPopsContextTypeFilter.java
data: ('BSUC:FT12-1', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/of/TestPopsContextTypeFilter.java', ';', '6/18/19 16:04', ';', 'I8ebff3b442b44f65fd6334c270466eb6f78c4987')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicCustomPurposeValidationRule.java', ';', '8/4/20 12:55', ';', 'Ie3793c1da4f702391793c08abb14a4314712f793')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HY64562  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY64562', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: BSUC:FT12-1  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/of/TestPopsContextTypeFilter.java
data: ('BSUC:FT12-1', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/of/TestPopsContextTypeFilter.java', ';', '6/18/19 16:04', ';', 'I8ebff3b442b44f65fd6334c270466eb6f78c4987')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponseHelper.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponseHelper.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY48964  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredAvailableUnitsHook.java
data: ('HY48964', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredAvailableUnitsHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY15484  java: restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/ServiceRegistryCommands.java
data: ('HY15484', ';', 'restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/ServiceRegistryCommands.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ContractSpecificationValidationRuleProvider.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ContractSpecificationValidationRuleProvider.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '8/4/20 12:55', ';', 'Ie3793c1da4f702391793c08abb14a4314712f793')
write pr: HX92381  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestSendTransactionNotificationTask.java
data: ('HX92381', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestSendTransactionNotificationTask.java', ';', '9/26/19 14:23', ';', 'I9f8a674f3f3862391e5eba16e40f650149c284ab')
write pr: HX92890  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java
data: ('HX92890', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java', ';', '10/2/19 8:29', ';', 'Ifbe6f226b580f342b41ad08cd24375d0132e1814')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestCustomerSpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestCustomerSpecificationConverter.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java

write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedRecurrencePrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedRecurrencePrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY12839  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java
data: ('HY12839', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java', ';', '11/15/19 15:22', ';', 'I7fe17b9acec09f13a00103a81f168cf5060a7d57')
write pr: HY17038  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/TestRefillRulesCrudServiceImpl.java
data: ('HY17038', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/TestRefillRulesCrudServiceImpl.java', ';', '1/7/20 8:37', ';', 'I0858621a15b34f4df45aa5c1eb8fb24b5b93034a')
write pr: HX77827  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java
data: ('HX77827', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java', ';', '7/8/19 13:34', ';', 'Ic5d84a0ee85b7636ab497b74f4757b82924b01db')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HY53290  java: integrationtest/cmd/src/main/java/com/ericsson/bss/rmca/integrationtest/cmd/command/LockCommand.java
data: ('HY53290', ';', 'integrationtest/cmd/src/main/java/com/ericsson/bss/rmca/integrationtest/cmd/command/LockCommand.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestJsonContentEscaper.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestJsonContentEscaper.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY15429  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/networkpolicy/TestNetworkPolicyGroupPriorityListPage_ITCase.java
data: ('HY15429', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/networkpolicy/TestNetworkPolicyGroupPriorityListPage_ITCase.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HY18902  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestUpstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestUpstreamDependencyAnalyzer.java', ';', '1/15/20 7:39', ';', 'I111a811fdc00f0324f117efb979970a197ae94aa')
write pr: HY76253  java: integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java
data: ('HY76253', ';', 'integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY15484  java: integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/sr/ServiceRegistryStub.java
data: ('HY15484', ';', 'integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/sr/ServiceRegistryStub.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY27042  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestCircularRelationsOfEntitiesNotAllowedValidationRule.java
data: ('HY27042', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestCircularRelationsOfEntitiesNotAllowedValidationRule.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HX98116  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java
data: ('HX98116', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java', ';', '10/29/19 15:16', ';', 'I0ee34afdc8d9fc1b3958d6df2b2c6b663d55d1b8')
write pr: HY58815  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestRankingEntryListMerger.java
data: ('HY58815', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestRankingEntryListMerger.java', ';', '8/24/20 6:59', ';', 'I75afbdde68c1b7e984baabb3b79893028cfd4e3f')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ProductPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ProductPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY52064  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredRuleConverter.java
data: ('HY52064', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredRuleConverter.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HX72933  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/LogicAlgorithmSpecificationValidationRuleProvider.java
data: ('HX72933', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/LogicAlgorithmSpecificationValidationRuleProvider.java', ';', '7/19/19 10:47', ';', 'I0853ff1e6a8b107df7e5f7387ffef8bb74635fd1')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HX99751  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/conversion/json/TestTimeZoneTypeConverter.java
data: ('HX99751', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/conversion/json/TestTimeZoneTypeConverter.java', ';', '11/7/19 9:03', ';', 'I334ec6690e885b1e3372a5c0f005445799a29357')
write pr: HY51063  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestCharacteristicMandatoryFieldValidationRule.java
data: ('HY51063', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestCharacteristicMandatoryFieldValidationRule.java', ';', '7/28/20 7:49', ';', 'I2768f8666a00ff719489ece7b49dc749d3d0c203')
write pr: HY52064  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionConverterFactory.java
data: ('HY52064', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionConverterFactory.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY28799  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java
data: ('HY28799', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java', ';', '2/26/20 10:45', ';', 'Id5a233c73716d6a04dff11d33750775630a02352')
write pr: HY66576  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/SetFixedFeeTemplateConverter.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/SetFixedFeeTemplateConverter.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HX99012  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/TestCobaEntityImpl.java
data: ('HX99012', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/TestCobaEntityImpl.java', ';', '10/30/19 11:51', ';', 'I86b611a35e28424205ccfb454478d3ca41da3c72')
write pr: HX80786  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX65525  java: restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java
data: ('HX65525', ';', 'restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY45345  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java', ';', '6/3/20 12:26', ';', 'I6df79d374514e487b0a9ebb4ea4423ef00ab0fe5')
write pr: HX80786  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/JsonContentEscaper.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/JsonContentEscaper.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY28857  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TestCompareValuesExactMatchHook.java
data: ('HY28857', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TestCompareValuesExactMatchHook.java', ';', '2/26/20 14:45', ';', 'I0ba82cd3da3b2d2df57a62bfd0403a8419b0906f')
write pr: HY67817  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/UiEntityFactory.java
data: ('HY67817', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/UiEntityFactory.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY60437  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestPolicyEventUiEntityMapper.java
data: ('HY60437', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestPolicyEventUiEntityMapper.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HX80786  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java
data: ('HX80786', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY46647  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRuleCompiler.java
data: ('HY46647', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRuleCompiler.java', ';', '6/16/20 17:36', ';', 'Id7123b034221d063105caab7716af4c38d524c90')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX83389  java: cli/imports/src/test/java/com/ericsson/bss/rmca/cli/imports/provisioning/TestJsonProvisioner.java
data: ('HX83389', ';', 'cli/imports/src/test/java/com/ericsson/bss/rmca/cli/imports/provisioning/TestJsonProvisioner.java', ';', '8/29/19 13:01', ';', 'I44a3f2f2f37bfabe01fe5cb7a8196a513f2a69c9')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY46647  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRuleCompiler.java
data: ('HY46647', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRuleCompiler.java', ';', '6/16/20 17:36', ';', 'Id7123b034221d063105caab7716af4c38d524c90')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedRecurrencePrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedRecurrencePrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY66573  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY66573', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '11/12/20 6:38', ';', 'Ia6df1f4889a74a6d75f4a5acdd4c769149afb44c')
write pr: HY65926  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestParameterizedBucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestParameterizedBucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY27847  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java
data: ('HY27847', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HX97152  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/TestConditionListProvider.java
data: ('HX97152', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/TestConditionListProvider.java', ';', '10/23/19 12:33', ';', 'I1663596fb506ccb4d32b427ebb540fe606393e45')
write pr: HY26161  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/scheduledefinition/TestScheduleDefinitionListEntry.java
data: ('HY26161', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/scheduledefinition/TestScheduleDefinitionListEntry.java', ';', '2/18/20 19:30', ';', 'Ibc8442f80224648e2fccba3139910c08e80cb687')
write pr: HY71789  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java
data: ('HY71789', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY38940  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java
data: ('HY38940', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedNetworkPolicyCounterStatusProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedNetworkPolicyCounterStatusProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java

write pr: HY65556  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceWithAccumulationHook.java
data: ('HY65556', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceWithAccumulationHook.java', ';', '10/1/20 16:15', ';', 'I6a65926d5c184d8b402d98005393d77c3334617c')
write pr: HY68338  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java
data: ('HY68338', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HX99743  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/UpdatePageTransactionImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/UpdatePageTransactionImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY23963  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/proxy/scenario/Scenario.java
data: ('HY23963', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/proxy/scenario/Scenario.java', ';', '1/29/20 12:43', ';', 'Ie855e6d90e64a1fc3dba52bc44ad4e57e7b145b1')
write pr: HY66450  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY66450', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBasPriorityListManagement.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBasPriorityListManagement.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HX84747  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HY46749  java: jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ApplicationScannerImpl.java
data: ('HY46749', ';', 'jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ApplicationScannerImpl.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY64897  java: importexport/api/src/test/java/com/ericsson/bss/rmca/importexport/api/TestRmcaExport.java
data: ('HY64897', ';', 'importexport/api/src/test/java/com/ericsson/bss/rmca/importexport/api/TestRmcaExport.java', ';', '9/29/20 11:32', ';', 'I3294ef1a95d0016a43ab5d39e9b7d4248b95106d')
write pr: HY65732  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/errorhandling/TestExportImportErrorResponse.java
data: ('HY65732', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/errorhandling/TestExportImportErrorResponse.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HX86828  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NormalizedEventSpecificationValidationRuleProvider.java
data: ('HX86828', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NormalizedEventSpecificationValidationRuleProvider.java', ';', '9/2/19 11:52', ';', 'I33357fbe9fad2076f17854bd9ad16db1bbceeccf')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationWithProratingAtBillcycleRecurrencesValidationRule.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationWithProratingAtBillcycleRecurrencesValidationRule.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY43069  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/NotificationTemplateViewImpl.java
data: ('HY43069', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/NotificationTemplateViewImpl.java', ';', '5/20/20 18:33', ';', 'I679551f00a74c7c9d676970107ef617630af0112')
write pr: HY66450  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY66450', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY66289  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/TestPermissionStrategyRuleConverter.java
data: ('HY66289', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/TestPermissionStrategyRuleConverter.java', ';', '10/9/20 12:02', ';', 'Iafc612201ba729674eb35808da39adb045bdc866')
write pr: HY15429  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY15429', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PublicQueryFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PublicQueryFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX94783  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterConverter.java
data: ('HX94783', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterConverter.java', ';', '10/14/19 12:03', ';', 'I92fd51831fb1b11f284e1ab8ece3d63978b9b66d')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/ScenarioTriggeredConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/ScenarioTriggeredConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX80786  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestAbstractRestEntity.java
data: ('HX80786', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestAbstractRestEntity.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX85856  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/TestCustomerFacingServiceSpecificationPageConverter.java
data: ('HX85856', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/TestCustomerFacingServiceSpecificationPageConverter.java', ';', '8/23/19 18:54', ';', 'Iae5a34f067ef652e6d173b322b260e1a553cf115')
write pr: HX69071  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/StrategyTypeCombinationsValidationRule.java
data: ('HX69071', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/StrategyTypeCombinationsValidationRule.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: HY16823  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestEnrichNesParameterHook.java
data: ('HY16823', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestEnrichNesParameterHook.java', ';', '12/6/19 8:19', ';', 'I442f3488071d6e7761538f4884507555c43af15f')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/LocalConditionUpdater.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/LocalConditionUpdater.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY35764  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRmcaEntityToCompiledRuleConverter.java
data: ('HY35764', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRmcaEntityToCompiledRuleConverter.java', ';', '4/6/20 11:08', ';', 'Ibbd864214ae606b29e19ebeed2dbf0a6122c81b6')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketPriorityListCleanupForBillingAccountSpecificationTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketPriorityListCleanupForBillingAccountSpecificationTask.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/TestBaseEntityDependencyPopulationImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/TestBaseEntityDependencyPopulationImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java', ';', '8/14/20 10:19', ';', 'Ib599f2a6f7be69d97266c7279f4e327aa110774a')
write pr: HY56903  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncementProvider.java
data: ('HY56903', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncementProvider.java', ';', '8/14/20 15:05', ';', 'I856c29d9b73d919b97faf2951227099ec29195af')
write pr: HY66576  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateProvider.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateProvider.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HX83389  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX83389', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/29/19 13:01', ';', 'I44a3f2f2f37bfabe01fe5cb7a8196a513f2a69c9')
write pr: HY64618  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY67817  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestChildUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestChildUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: BSUC:FT8-15  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java
data: ('BSUC:FT8-15', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java', ';', '7/27/20 8:52', ';', 'Id0e64e935b823efb860306c52e4f8d2b69db0bbe')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/UnpublishPageTransactionImpl.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/UnpublishPageTransactionImpl.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY60708  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY60708', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY55767  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisionerUpdater.java
data: ('HY55767', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisionerUpdater.java', ';', '8/6/20 5:57', ';', 'I45ef8bd11db167e66218aca28477034d8ec41f89')
write pr: HY21738  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/DimensionsCharacteristicBuilder.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/DimensionsCharacteristicBuilder.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HY64936  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HY64936', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '9/30/20 8:32', ';', 'I957cd8155513b532592f30d26f778c5141f751dd')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIndexedQueryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIndexedQueryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/SingleValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/SingleValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/PriorityListMigrationHelper.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/PriorityListMigrationHelper.java', ';', '7/28/20 11:41', ';', 'I68f544fdbeb48f50c4f4587e45f8c38710e937ae')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '7/28/20 12:15', ';', 'I772760377e2b68e3f16cc0a8871249e15d6548c7')
write pr: BSUC:FT8-15:4  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestBaseErrorResponse.java
data: ('BSUC:FT8-15:4', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestBaseErrorResponse.java', ';', '7/27/20 6:54', ';', 'I0d6c6f576cb0813ff8bb9bc9f0dbd085ead415a0')
write pr: HY47474  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java
data: ('HY47474', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java', ';', '6/16/20 16:40', ';', 'I4128c314c6a2c792f26958e820f9ce695eb86375')
write pr: HY26736  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsToSharingLimitRelationValidationRule.java
data: ('HY26736', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsToSharingLimitRelationValidationRule.java', ';', '2/20/20 14:20', ';', 'I15e78f87f7af3b89a90fa1eade34b80f49f8e6f3')
write pr: HX94783  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterHelper.java
data: ('HX94783', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterHelper.java', ';', '10/14/19 12:03', ';', 'I92fd51831fb1b11f284e1ab8ece3d63978b9b66d')
write pr: HY53290  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/BucketPriorityListUpdater.java
data: ('HY53290', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/BucketPriorityListUpdater.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HY53290  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/ProductPriorityListGenerator.java

write pr: HY62217  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/RefillProductBucketHook.java
data: ('HY62217', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/RefillProductBucketHook.java', ';', '9/15/20 12:51', ';', 'I2c69ecc4fb046a7729e9110c78f8cfdf64353995')
write pr: HY69497  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java
data: ('HY69497', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java', ';', '11/2/20 6:30', ';', 'I280e9ee744f291564303a5c869ee1610b3b6e4c9')
write pr: HY52844  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java
data: ('HY52844', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java', ';', '7/16/20 14:16', ';', 'I266f0fd1a842bbc64d4b981a33605aa4a36f0b2b')
write pr: HY46749  java: jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestApplicationScannerImpl.java
data: ('HY46749', ';', 'jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestApplicationScannerImpl.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY53290  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java
data: ('HY53290', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java', ';', '7/28/20 13:10', ';', 'I4d41599ba9fe98cfd0e66f307918ca60c90ce420')
write pr: HX88018  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HX88018', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HY53290  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java
data: ('HY53290', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY60708  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestScenarioWithAnnouncementsValidationRule.java
data: ('HY60708', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestScenarioWithAnnouncementsValidationRule.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY69638  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestEventReasonCodeHook.java
data: ('HY69638', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestEventReasonCodeHook.java', ';', '10/28/20 7:38', ';', 'I8458a5d8fe6c503df7a962832124a8511f1a96d1')
write pr: HY65634  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java
data: ('HY65634', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java', ';', '10/6/20 7:16', ';', 'Ic57dd52cdd66db0adeee0237f525b5a5620fc058')
write pr: HX72323  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/CommonEntityRelationPage.java
data: ('HX72323', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/CommonEntityRelationPage.java', ';', '6/20/19 5:01', ';', 'I0ca3d8c20cad05a2e1d66ce99d0e2cf4e3306db3')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSBehavior.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSBehavior.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY64004  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY66576  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateConverter.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateConverter.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HY23963  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java
data: ('HY23963', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java', ';', '1/29/20 12:43', ';', 'Ie855e6d90e64a1fc3dba52bc44ad4e57e7b145b1')
write pr: BSUC:FT8-15:4  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestSpecificErrorDetails.java
data: ('BSUC:FT8-15:4', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestSpecificErrorDetails.java', ';', '7/27/20 6:54', ';', 'I0d6c6f576cb0813ff8bb9bc9f0dbd085ead415a0')
write pr: HY21878  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestExportImpl.java
data: ('HY21878', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestExportImpl.java', ';', '1/14/20 10:01', ';', 'Iff8ba9aa264f801fbf884ac9179316a356c51591')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '7/28/20 13:10', ';', 'I4d41599ba9fe98cfd0e66f307918ca60c90ce420')
write pr: HY53290  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntityTypeKeys.java
data: ('HY53290', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntityTypeKeys.java', ';', '8/13/20 10:10', ';', 'I3f29f482bc8388074283ba83baa978d8360d7768')
write pr: HY10139  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java
data: ('HY10139', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java', ';', '11/12/19 8:43', ';', 'I9f376f4b2393501d670306d5ff94200969948d4d')
write pr: HY38940  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY38940', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX71714  java: jivetest/src/main/java/com/ericsson/bss/rmca/jive/utils/coba/NotificationServiceWrapper.java
data: ('HX71714', ';', 'jivetest/src/main/java/com/ericsson/bss/rmca/jive/utils/coba/NotificationServiceWrapper.java', ';', '6/3/19 8:33', ';', 'I656e5c9d581288f911458386a3c91e625e0d2527')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedSharingProviderPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedSharingProviderPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY46587  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGlobalPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGlobalPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeactivateTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeactivateTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AbstractReasonCodeHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AbstractReasonCodeHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX99012  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/CobaEntityImpl.java
data: ('HX99012', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/CobaEntityImpl.java', ';', '10/30/19 11:51', ';', 'I86b611a35e28424205ccfb454478d3ca41da3c72')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY18074  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java
data: ('HY18074', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java', ';', '12/16/19 10:12', ';', 'I4f3f6e4752d389bdfb0ea92e5aac90d22d650274')
write pr: HY64618  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java
data: ('HY64618', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/MultiTypeDateTimeIntervalHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/MultiTypeDateTimeIntervalHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX84747  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HY15429  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcefacingservicespecification/TestRfssChargingServiceValidationRule.java
data: ('HY15429', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcefacingservicespecification/TestRfssChargingServiceValidationRule.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HY60437  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java
data: ('HY60437', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY58180  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY22981  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java
data: ('HY22981', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/RefillRuleListPageConverter.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/RefillRuleListPageConverter.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HX84971  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/pages/contractspecification/TestContractSpecificationPage_ITCase.java
data: ('HX84971', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/pages/contractspecification/TestContractSpecificationPage_ITCase.java', ';', '8/22/19 9:07', ';', 'I6efb7268fe9aa1f637feccb2cab3a22fae4a87b3')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HX86471  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/TestEntityDependencyPopulationImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/TestEntityDependencyPopulationImpl.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketusagerule/BucketUsageRuleConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketusagerule/BucketUsageRuleConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY46749  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RmcaRestPublisher.java
data: ('HY46749', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RmcaRestPublisher.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestExportTaskImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestExportTaskImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY46647  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/PromotionRuleCompiler.java
data: ('HY46647', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/PromotionRuleCompiler.java', ';', '6/16/20 17:36', ';', 'Id7123b034221d063105caab7716af4c38d524c90')
write pr: HY42110  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java
data: ('HY42110', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java', ';', '5/13/20 10:51', ';', 'I07db9d0d709036e8e1f18f534482b09e5334ed87')
write pr: HY65732  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java
data: ('HY65732', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RankingEntryListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RankingEntryListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSBehavior.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSBehavior.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY70144  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/TestBucketBalanceAnnouncementActionValidationRule.java
data: ('HY70144', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/TestBucketBalanceAnnouncementActionValidationRule.java', ';', '10/29/20 19:40', ';', 'I05899c33811521a2758ad203cbfb6b2e311f9671')

write pr: HY64508  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceHook.java
data: ('HY64508', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceHook.java', ';', '9/28/20 13:54', ';', 'Idb2eac49f3af0b019214c20a423d890f66e960ea')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY45345  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicsInfoHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicsInfoHelper.java', ';', '6/8/20 18:37', ';', 'I83a8d3f388c393bb2d9836cac3f723fd33c7ecb4')
write pr: HX72276  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicPossibleValueModificationInVersionRule.java
data: ('HX72276', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicPossibleValueModificationInVersionRule.java', ';', '6/17/19 19:09', ';', 'I37a4da60a582bda294fa02a01ea6e2979ff93861')
write pr: HY74660  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestUnpublishAffectedEntitiesQueryImpl.java
data: ('HY74660', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestUnpublishAffectedEntitiesQueryImpl.java', ';', '12/14/20 8:47', ';', 'I732b77617ceb37732af2ab0df12910c3cf479905')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java', ';', '8/12/20 7:45', ';', 'I1f7e85efdce5868c4427e8697ae786c8ab48d073')
write pr: HY69497  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java
data: ('HY69497', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java', ';', '11/2/20 6:30', ';', 'I280e9ee744f291564303a5c869ee1610b3b6e4c9')
write pr: HY27847  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/permissionstrategy/TestPermissionStrategyPage_ITCase.java
data: ('HY27847', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/permissionstrategy/TestPermissionStrategyPage_ITCase.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY34694  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationUsedMetaStatesExistsInCobaRule.java
data: ('HY34694', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationUsedMetaStatesExistsInCobaRule.java', ';', '3/31/20 12:33', ';', 'Ib2187d52fa5c4f99baaad4225f7b2a3408402972')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY63435  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java
data: ('HY63435', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java', ';', '9/23/20 8:35', ';', 'I5184845944f18f7abfd79b90ec666c4e9e878b38')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PublicQueryFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PublicQueryFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HX80786  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestFacadeImpl.java
data: ('HX80786', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestFacadeImpl.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY64618  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: BSUC:FT8-15  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java
data: ('BSUC:FT8-15', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java', ';', '7/21/20 9:36', ';', 'I2e24c3a89e0945ebb31a235f7d7e8bbc39e23983')
write pr: HY42777  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java
data: ('HY42777', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java', ';', '5/29/20 6:07', ';', 'Ie9ad14d2533e0d7a6c9cad84f2928d596556ec55')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRealignedTieredBucketBalanceWithBurHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRealignedTieredBucketBalanceWithBurHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverter.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HY17038  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/TestRefillRulesCrudServiceImpl.java
data: ('HY17038', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/TestRefillRulesCrudServiceImpl.java', ';', '1/7/20 8:37', ';', 'I0858621a15b34f4df45aa5c1eb8fb24b5b93034a')
write pr: HY53290  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/RequestPropertyFactory.java
data: ('HY53290', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/RequestPropertyFactory.java', ';', '8/13/20 10:10', ';', 'I3f29f482bc8388074283ba83baa978d8360d7768')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationNotificationsValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationNotificationsValidationRule.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY71789  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java
data: ('HY71789', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPage.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPage.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSFilter.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/XSSFilter.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '7/28/20 13:10', ';', 'I4d41599ba9fe98cfd0e66f307918ca60c90ce420')
write pr: HY56903  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredRuleConverter.java
data: ('HY56903', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredRuleConverter.java', ';', '8/14/20 15:05', ';', 'I856c29d9b73d919b97faf2951227099ec29195af')
write pr: HY43286  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/ChargingCapabilityViewImpl.java
data: ('HY43286', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/ChargingCapabilityViewImpl.java', ';', '5/20/20 10:24', ';', 'If3044bb51429a6ca736d7f6996eead1937537018')
write pr: HY66450  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractTestChaCondition.java
data: ('HY66450', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractTestChaCondition.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '8/4/20 12:55', ';', 'Ie3793c1da4f702391793c08abb14a4314712f793')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java', ';', '7/28/20 13:10', ';', 'I4d41599ba9fe98cfd0e66f307918ca60c90ce420')
write pr: HX96573  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java
data: ('HX96573', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java', ';', '10/17/19 11:11', ';', 'Ia4c4c1eb6ac4fb844578f78cc0012763efccc772')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestTableContainsHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestTableContainsHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY27042  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java
data: ('HY27042', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY26947  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestShadowValueContainerFilter.java
data: ('HY26947', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestShadowValueContainerFilter.java', ';', '2/18/20 11:29', ';', 'I5d2abc92547d213a3d9547a975f29fb822a853c3')
write pr: HY72852  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/commondimension/TestCommonDimensionPageConverter.java
data: ('HY72852', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/commondimension/TestCommonDimensionPageConverter.java', ';', '11/13/20 10:03', ';', 'I25f3405b59d3479a5546f47e4206fdbc0ee8e681')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/AbstractTieredConditionConverter.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/AbstractTieredConditionConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestProductStateAlreadySuspendedOrInactivated.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HX86471  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/DryRunImporter.java
data: ('HX86471', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/DryRunImporter.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY51285  java: restservice/traffic/src/main/java/com/ericsson/bss/rmca/restservice/traffic/RestApiEntity.java
data: ('HY51285', ';', 'restservice/traffic/src/main/java/com/ericsson/bss/rmca/restservice/traffic/RestApiEntity.java', ';', '7/3/20 7:54', ';', 'I1279ccc3fe3d737e0e1b6e3dc7680682b2864d57')
write pr: HX84594  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/statistics/TestAllEntitiesAreIncludedInStatistics.java
data: ('HX84594', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/statistics/TestAllEntitiesAreIncludedInStatistics.java', ';', '9/9/19 19:36', ';', 'Ieda9b6cb75da48428f6485d40e35383dad80a3a7')
write pr: HY46854  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposer.java
data: ('HY46854', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposer.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY38940  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/relation/TestRelationUtilityImpl.java
data: ('HY38940', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/relation/TestRelationUtilityImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY52064  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncementProvider.java
data: ('HY52064', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncementProvider.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY64938  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/ThresholdOffsetUniqueExternalIdValidationRule.java
data: ('HY64938', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/ThresholdOffsetUniqueExternalIdValidationRule.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HX84971  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HX84971', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '8/26/19 10:22', ';', 'Ib6b832e519cb11b7aaf50621eff3edbe92e8d636')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RankingEntryListFilterer.java

write pr: HY65732  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java
data: ('HY65732', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HX84971  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationDetails.java
data: ('HX84971', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationDetails.java', ';', '8/22/19 9:07', ';', 'I6efb7268fe9aa1f637feccb2cab3a22fae4a87b3')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedNetworkPolicyGroupPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedNetworkPolicyGroupPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY37445  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestSendEndUserNotificationTemplateConverter.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestSendEndUserNotificationTemplateConverter.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY65732  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/errorhandling/TestExportImportErrorResponse.java
data: ('HY65732', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/errorhandling/TestExportImportErrorResponse.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/JsonContentEscaper.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/JsonContentEscaper.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY19473  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceConverter.java
data: ('HY19473', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceConverter.java', ';', '12/20/19 13:32', ';', 'Id427faf9ca2c1075a078de981e71c884657e94d7')
write pr: HY64004  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/LockPageTransactionImpl.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/LockPageTransactionImpl.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY64004  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: PBI:269  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/RefillCompiledRuleToRmcaEntityConverter.java
data: ('PBI:269', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/RefillCompiledRuleToRmcaEntityConverter.java', ';', '2/14/20 12:09', ';', 'Ie2b1871e8213ad34e012387b8a3477b86b1b62b7')
write pr: ALM1742604  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityChangeService_ITCase.java
data: ('ALM1742604', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityChangeService_ITCase.java', ';', '6/19/19 12:27', ';', 'I84ef7162420af692b6bd1d44f34022037d49c488')
write pr: HY21738  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProviderFactory.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProviderFactory.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HX88018  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HX88018', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HX89960  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TestConnectedChargingService.java
data: ('HX89960', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TestConnectedChargingService.java', ';', '9/16/19 8:48', ';', 'I01684e074fb128c82b1a79ff5474b6116aa0273d')
write pr: HY27847  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java
data: ('HY27847', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY38940  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestReferencesFromDataMigration.java
data: ('HY38940', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestReferencesFromDataMigration.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverterFactory.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverterFactory.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HX96573  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskValidator.java
data: ('HX96573', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskValidator.java', ';', '10/17/19 11:11', ';', 'Ia4c4c1eb6ac4fb844578f78cc0012763efccc772')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY53290  java: integrationtest/cmd/src/main/java/com/ericsson/bss/rmca/integrationtest/cmd/command/StressCdacWriteTestCommand.java
data: ('HY53290', ';', 'integrationtest/cmd/src/main/java/com/ericsson/bss/rmca/integrationtest/cmd/command/StressCdacWriteTestCommand.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestAnnouncementPhrase.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestAnnouncementPhrase.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY50582  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY50582', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '7/8/20 6:37', ';', 'I9c1fa14935e1d01bb32cda5ba5e060ab6c9a8ca2')
write pr: HY66573  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY66573', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '11/12/20 6:38', ';', 'Ia6df1f4889a74a6d75f4a5acdd4c769149afb44c')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/TestPresetToPolicyValueConverter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/TestPresetToPolicyValueConverter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/PageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/PageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY56903  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionConverterFactory.java
data: ('HY56903', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionConverterFactory.java', ';', '8/14/20 15:05', ';', 'I856c29d9b73d919b97faf2951227099ec29195af')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HY45351  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicsInfoHelper.java
data: ('HY45351', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicsInfoHelper.java', ';', '6/5/20 11:19', ';', 'I8c183012f24dc62d6417601ad3b5c3978731c6fc')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationNotificationsValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationNotificationsValidationRule.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java', ';', '6/3/20 12:26', ';', 'I6df79d374514e487b0a9ebb4ea4423ef00ab0fe5')
write pr: HY46412  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CDRProcessingInformationConverter.java
data: ('HY46412', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CDRProcessingInformationConverter.java', ';', '6/8/20 12:02', ';', 'Ib7b7445e62b9536b26ce3f1e9ab35da40126d07e')
write pr: HY53290  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/ProductPriorityListImporter.java
data: ('HY53290', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/ProductPriorityListImporter.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HY65634  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionType.java
data: ('HY65634', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionType.java', ';', '10/6/20 7:16', ';', 'Ic57dd52cdd66db0adeee0237f525b5a5620fc058')
write pr: HY53290  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/bpl/TestBucketPriorityList_ITCase.java
data: ('HY53290', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/bpl/TestBucketPriorityList_ITCase.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HX94284  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/characteristicsetspecification/CharacteristicSetSpecificationPageConverter.java
data: ('HX94284', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/characteristicsetspecification/CharacteristicSetSpecificationPageConverter.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponse.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponse.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY32754  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Pricing.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Pricing.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY48964  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/availableunits/AvailableUnitsTemplateConverter.java
data: ('HY48964', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/availableunits/AvailableUnitsTemplateConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HX94284  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TestEntityCharacteristics.java
data: ('HX94284', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TestEntityCharacteristics.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HX84747  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestCounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestCounterConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HY64938  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/PbsThresholdOffsetUniqueExternalIdValidationRule.java
data: ('HY64938', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/PbsThresholdOffsetUniqueExternalIdValidationRule.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HY38940  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/MockView.java
data: ('HY38940', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/MockView.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY60437  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/PredefinedEntityIds.java
data: ('HY60437', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/PredefinedEntityIds.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HX92625  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/LogicAlgorithmSpecificationPageConverter.java
data: ('HX92625', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/LogicAlgorithmSpecificationPageConverter.java', ';', '9/27/19 7:56', ';', 'Ic24b9afe4cb3290dd749bf798e43c7408078fe85')
write pr: HY59800  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java

data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRankingEntryListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY45345  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java', ';', '6/4/20 11:13', ';', 'I16b5fc177b2155b8b6eb26f249690a9ab4f4d990')
write pr: HY21740  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/EventReasonCode.java
data: ('HY21740', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/EventReasonCode.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleBaseStateTransitionRuleConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleBaseStateTransitionRuleConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY69943  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/PriorityListUpdateHelper.java
data: ('HY69943', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/PriorityListUpdateHelper.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationConverter.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationConverter.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HX65525  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/EntityReadApi.java
data: ('HX65525', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/EntityReadApi.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY69066  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java
data: ('HY69066', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java', ';', '11/6/20 13:31', ';', 'If55b107445b1a3006a701c037cf371b3d760a58d')
write pr: HY46854  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestRuleConverterContext.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestRuleConverterContext.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListReverser.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListReverser.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '8/4/20 12:55', ';', 'Ie3793c1da4f702391793c08abb14a4314712f793')
write pr: HY17256  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestEnrichNesParameterHook.java
data: ('HY17256', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestEnrichNesParameterHook.java', ';', '12/9/19 13:36', ';', 'Id82848f9045b67c2b4f9c5d7b598ad36b7aca393')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationsFrom.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationsFrom.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY40790  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/statistics/Statistics.java
data: ('HY40790', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/statistics/Statistics.java', ';', '5/5/20 8:18', ';', 'I62bd89465d6fd12133d7d4072e17e560252eb873')
write pr: HY32754  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY67817  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java
data: ('HY67817', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY58180  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY53290  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestBucketPriorityListUpdater.java
data: ('HY53290', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestBucketPriorityListUpdater.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HX98135  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/TestActionListProvider.java
data: ('HX98135', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/TestActionListProvider.java', ';', '10/28/19 12:07', ';', 'I10c0c4974518693d35658b3bcc9c5c869c65ce40')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/StateBeforeHaltHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/StateBeforeHaltHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX93518  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationListPageConverter.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationListPageConverter.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')
write pr: HY58373  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/AbstractNormalizedAndCssParameter.java
data: ('HY58373', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/AbstractNormalizedAndCssParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/PriorityOrder.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/PriorityOrder.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY68338  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java
data: ('HY68338', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX64747  java: persistenceimpl/src/test/java/com/ericsson/bss/rmca/persistenceimpl/notification/TestEntityChangeServicePersistenceImpl.java
data: ('HX64747', ';', 'persistenceimpl/src/test/java/com/ericsson/bss/rmca/persistenceimpl/notification/TestEntityChangeServicePersistenceImpl.java', ';', '5/13/19 15:01', ';', 'I2bd5a4f0534837f720ea0704947eb9c7c9df1178')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HX66324  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java
data: ('HX66324', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java', ';', '5/16/19 20:20', ';', 'Ie3ad0574aed45eae4316e0bc9a1e217254caaf67')
write pr: HY27042  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestCircularDependencyFilter.java
data: ('HY27042', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestCircularDependencyFilter.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY30739  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY30739', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '3/10/20 8:55', ';', 'Ic262489ea61211040cebb42666f8d928ef3346cf')
write pr: HY35363  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/TestContractSpecificationVersionImportValidator.java
data: ('HY35363', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/TestContractSpecificationVersionImportValidator.java', ';', '4/3/20 12:07', ';', 'Idc1d5442147a3362f78678e36589b171570c7583')
write pr: HY53290  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/RecurrencePriorityListUpdater.java
data: ('HY53290', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/RecurrencePriorityListUpdater.java', ';', '7/28/20 11:41', ';', 'I54f5f21378cb0d1b30404844cea865cc5b54df1c')
write pr: HY12839  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY12839', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '11/15/19 15:22', ';', 'I7fe17b9acec09f13a00103a81f168cf5060a7d57')
write pr: HY76370  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY33683  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HY33683', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '3/25/20 11:55', ';', 'I097f13d8eacbfcb1be15b160dfbcf24b8d563727')
write pr: HY50582  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY50582', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '7/8/20 6:37', ';', 'I9c1fa14935e1d01bb32cda5ba5e060ab6c9a8ca2')
write pr: HY77550  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java
data: ('HY77550', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HY24061  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY24061', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY53290  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java
data: ('HY53290', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java', ';', '8/11/20 14:30', ';', 'I98f969c29c1d489799339abda80f0e9333a29c0a')
write pr: HY77550  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java
data: ('HY77550', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HX98016  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HX98016', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '10/25/19 9:17', ';', 'Ia467057e1024d0cadea1332b45b192c66ad09f08')
write pr: HY69943  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/PriorityListUpdateHelper.java
data: ('HY69943', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/PriorityListUpdateHelper.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleTriggerConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleTriggerConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY69952  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java
data: ('HY69952', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java', ';', '10/29/20 11:24', ';', 'I068e8e12ed4e10794e3c3ab3b100c3366fe002f1')
write pr: HY35764  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRmcaEntityToCompiledRuleConverter.java
data: ('HY35764', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRmcaEntityToCompiledRuleConverter.java', ';', '4/6/20 11:08', ';', 'Ibbd864214ae606b29e19ebeed2dbf0a6122c81b6')
write pr: HY48964  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/availableunits/TestAvailableUnitsTemplateConverter.java
data: ('HY48964', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/availableunits/TestAvailableUnitsTemplateConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TimeOfDayConstantsHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TimeOfDayConstantsHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY51285  java: restservice/traffic/src/main/java/com/ericsson/bss/rmca/restservice/traffic/RestApiEntity.java
data: ('HY51285', ';', 'restservice/traffic/src/main/java/com/ericsson/bss/rmca/restservice/traffic/RestApiEntity.java', ';', '7/3/20 7:54', ';', 'I1279ccc3fe3d737e0e1b6e3dc7680682b2864d57')
write pr: HX94284  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/CharacteristicHelper.java
data: ('HX94284', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/CharacteristicHelper.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HX80786  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java

write pr: HY65926  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HY54229  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/realmspecific/productspecification/TestPsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HY54229', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/realmspecific/productspecification/TestPsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '8/5/20 18:08', ';', 'Ib34a1ef75eba28e2d1dde91e972dac0c7f71da1d')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY22981  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCleanupTaskHelper.java
data: ('HY22981', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCleanupTaskHelper.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/AbstractChaConditionHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/AbstractChaConditionHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY55461  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncement.java
data: ('HY55461', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncement.java', ';', '8/5/20 16:52', ';', 'I6fa074f931bbd292ab831b1066d789f5748042c5')
write pr: HY66576  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/TestSetFeeProvider.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/TestSetFeeProvider.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: PBI:269  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/RefillRmcaEntityToCompiledRuleConverter.java
data: ('PBI:269', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/RefillRmcaEntityToCompiledRuleConverter.java', ';', '2/14/20 12:09', ';', 'Ie2b1871e8213ad34e012387b8a3477b86b1b62b7')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY39569  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecification.java
data: ('HY39569', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecification.java', ';', '4/28/20 7:22', ';', 'I380dbd5a7bb147bf035a66ad24d3e4f135dee342')
write pr: HY31764  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestPoPageCharacteristicsHandler.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestPoPageCharacteristicsHandler.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HX84971  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/ContractSpecificationPaymentContextValidationRule.java
data: ('HX84971', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/ContractSpecificationPaymentContextValidationRule.java', ';', '8/26/19 10:22', ';', 'Ib6b832e519cb11b7aaf50621eff3edbe92e8d636')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleMetaStateDefinitionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleMetaStateDefinitionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY26736  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsToSharingLimitRelationValidationRule.java
data: ('HY26736', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsToSharingLimitRelationValidationRule.java', ';', '2/20/20 14:20', ';', 'I15e78f87f7af3b89a90fa1eade34b80f49f8e6f3')
write pr: HX91715  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java
data: ('HX91715', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: BSUC:FT8-15:4  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RMCommonErrorResponse.java
data: ('BSUC:FT8-15:4', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RMCommonErrorResponse.java', ';', '7/27/20 6:54', ';', 'I0d6c6f576cb0813ff8bb9bc9f0dbd085ead415a0')
write pr: HY15484  java: integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/sr/ServiceRegistryStub.java
data: ('HY15484', ';', 'integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/sr/ServiceRegistryStub.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY64004  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeApplicableFor.java
data: ('HY64004', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeApplicableFor.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY43069  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestChargingCapabilityViewImpl.java
data: ('HY43069', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestChargingCapabilityViewImpl.java', ';', '5/20/20 18:33', ';', 'I679551f00a74c7c9d676970107ef617630af0112')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListManagement.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListManagement.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '6/9/20 13:16', ';', 'I9c4ec12293c2c83552af2e769209230fbaf70479')
write pr: HX99482  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java
data: ('HX99482', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java', ';', '11/1/19 15:14', ';', 'I4b5b674e92043f3d7602e7355fd694e054577335')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/SharingProviderPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/SharingProviderPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY66450  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY66450', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/PriorityOrder.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/PriorityOrder.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX90022  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/ExportData.java
data: ('HX90022', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/ExportData.java', ';', '9/16/19 11:49', ';', 'I6687915584c83b5d253d629b97bfbdf64121fb60')
write pr: HY60708  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncementConverter.java
data: ('HY60708', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncementConverter.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY24061  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY24061', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/ManualRecurrenceTriggerHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/ManualRecurrenceTriggerHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListReverser.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListReverser.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY26947  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java
data: ('HY26947', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java', ';', '2/18/20 11:29', ';', 'I5d2abc92547d213a3d9547a975f29fb822a853c3')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleNotificationActionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleNotificationActionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HX96573  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java
data: ('HX96573', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java', ';', '10/17/19 11:11', ';', 'Ia4c4c1eb6ac4fb844578f78cc0012763efccc772')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PolicyValueSpecificationConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PolicyValueSpecificationConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY27042  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/CircularRelationsOfEntitiesNotAllowedValidationRule.java
data: ('HY27042', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/CircularRelationsOfEntitiesNotAllowedValidationRule.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY21738  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProvider.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProvider.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HY53290  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY53290', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY47676  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/NotificationOffsetCharacteristicValueValidationRule.java
data: ('HY47676', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/NotificationOffsetCharacteristicValueValidationRule.java', ';', '6/19/20 18:35', ';', 'I0ce4c0ee035aa3c7f6d642ff7180c855de4aa0a6')
write pr: HY65966  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestSharingResourceProviderHelper.java
data: ('HY65966', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestSharingResourceProviderHelper.java', ';', '10/5/20 12:59', ';', 'I0840216dcb9c8cc31656a0d0bed58e807bbd65e7')
write pr: HY66573  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY66573', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '11/12/20 6:38', ';', 'Ia6df1f4889a74a6d75f4a5acdd4c769149afb44c')
write pr: HY52844  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationToPageConverter.java
data: ('HY52844', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationToPageConverter.java', ';', '7/16/20 14:16', ';', 'I266f0fd1a842bbc64d4b981a33605aa4a36f0b2b')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestReplenishmentTriggeredByHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestReplenishmentTriggeredByHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX93518  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/ResourceFacingServiceSpecificationDetails.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/ResourceFacingServiceSpecificationDetails.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')

write pr: HX92945  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java
data: ('HX92945', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java', ';', '10/3/19 13:35', ';', 'Ia088cd35f8145aad2d83513212081c58db63a787')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverterFactory.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverterFactory.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY19427  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/common/rule/Modifier.java
data: ('HY19427', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/common/rule/Modifier.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HX71714  java: notificationimpl/producer/src/main/java/com/ericsson/bss/rmca/notificationimpl/producer/CassandraProducerFactory.java
data: ('HX71714', ';', 'notificationimpl/producer/src/main/java/com/ericsson/bss/rmca/notificationimpl/producer/CassandraProducerFactory.java', ';', '6/3/19 8:33', ';', 'I656e5c9d581288f911458386a3c91e625e0d2527')
write pr: HY53290  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/bpl/TestBucketPriorityList_ITCase.java
data: ('HY53290', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/bpl/TestBucketPriorityList_ITCase.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY50582  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAccumulateConsumedUnitsValidationRule.java
data: ('HY50582', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAccumulateConsumedUnitsValidationRule.java', ';', '7/8/20 6:37', ';', 'I9c1fa14935e1d01bb32cda5ba5e060ab6c9a8ca2')
write pr: HY66450  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY66450', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY31764  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestPoPageCharacteristicsHandler.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestPoPageCharacteristicsHandler.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestCharacteristicInfoNode.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestCharacteristicInfoNode.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TieredValuesConverter.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TieredValuesConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY35363  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ContractSpecificationVersionImportValidator.java
data: ('HY35363', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ContractSpecificationVersionImportValidator.java', ';', '4/3/20 12:07', ';', 'Idc1d5442147a3362f78678e36589b171570c7583')
write pr: HY19427  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java
data: ('HY19427', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HY53290  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java
data: ('HY53290', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java', ';', '8/14/20 12:03', ';', 'Iae01d82b2716e6471600c533f95344833cee0531')
write pr: BSUC:FT8-15:4  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('BSUC:FT8-15:4', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '7/16/20 17:15', ';', 'I55d736b9a88ebc8aae129ecb29c7fad070cb0055')
write pr: HY28799  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java
data: ('HY28799', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java', ';', '2/26/20 10:45', ';', 'Id5a233c73716d6a04dff11d33750775630a02352')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/NormalizedParameter.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/NormalizedParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HX71714  java: notificationimpl/producer/src/test/java/com/ericsson/bss/rmca/notificationimpl/producer/TestMessageSender.java
data: ('HX71714', ';', 'notificationimpl/producer/src/test/java/com/ericsson/bss/rmca/notificationimpl/producer/TestMessageSender.java', ';', '6/3/19 8:33', ';', 'I656e5c9d581288f911458386a3c91e625e0d2527')
write pr: HY67817  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY60256  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java
data: ('HY60256', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java', ';', '9/2/20 6:41', ';', 'Ie8e407477721eddb52665e680fae135d1a3f9003')
write pr: HY18902  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/UpstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/UpstreamDependencyAnalyzer.java', ';', '1/15/20 7:39', ';', 'I111a811fdc00f0324f117efb979970a197ae94aa')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketthreshold/BucketThresholdConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketthreshold/BucketThresholdConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX99751  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/conversion/json/JsonConverterHelper.java
data: ('HX99751', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/conversion/json/JsonConverterHelper.java', ';', '11/7/19 9:03', ';', 'I334ec6690e885b1e3372a5c0f005445799a29357')
write pr: HX71520  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java
data: ('HX71520', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java', ';', '6/25/19 11:55', ';', 'I3b716397d7f727ee9f01936e96bae29fb123c9e8')
write pr: HY27296  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingusagestrategy/LogicAlgorithmSpecificationPageConverter.java
data: ('HY27296', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingusagestrategy/LogicAlgorithmSpecificationPageConverter.java', ';', '2/18/20 15:40', ';', 'I4a818d1438d03aba58044d65a8dd0cda3ef07f2f')
write pr: HY65889  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationRuleActionValidationRule.java
data: ('HY65889', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationRuleActionValidationRule.java', ';', '10/22/20 14:16', ';', 'I4cf4061ac1afe3996cc9d47c2e71cf1d3f6b6500')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListReverser.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListReverser.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX87622  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/buckettag/BucketTagListEntryConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/buckettag/BucketTagListEntryConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HY46854  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposer.java
data: ('HY46854', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposer.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '8/3/20 9:36', ';', 'I8d1f7b2d9ee1f0042166af77f1e629a5998dd65f')
write pr: HY24061  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/TestProvisionConfigurationServiceImpl.java
data: ('HY24061', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/TestProvisionConfigurationServiceImpl.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HX70244  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/IndexId.java
data: ('HX70244', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/IndexId.java', ';', '6/5/19 12:29', ';', 'I86f2a81befdfd840ceb2df5184cf0a355c31fd6e')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestNormalizedParameter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestNormalizedParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HX74509  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/TestAbstractTieredConditionConverter.java
data: ('HX74509', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/TestAbstractTieredConditionConverter.java', ';', '6/19/19 6:15', ';', 'I9b834546f9a32ad7dba545810d206b399d0b34ad')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestEventReasonCode.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestEventReasonCode.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY58815  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListUpdaterForUseCase.java
data: ('HY58815', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListUpdaterForUseCase.java', ';', '8/24/20 8:36', ';', 'I9c669a4ba2e3bdd9d68d7c57e65d98bf5ed9cb0c')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY53290  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY53290', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HX88018  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HX88018', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HY26708  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/ProductOfferingPriceSpecificationPageConverter.java
data: ('HY26708', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/ProductOfferingPriceSpecificationPageConverter.java', ';', '2/18/20 8:47', ';', 'If954ce037eb210a99dacfe14e1eeb6417a1f89d6')
write pr: HY32754  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY43705  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/RefillSendExternalNotificationTemplateProvider.java
data: ('HY43705', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/RefillSendExternalNotificationTemplateProvider.java', ';', '5/20/20 8:56', ';', 'I2d85a2de97585e405042f92048da30836f514228')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIndexedQueryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIndexedQueryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ProductPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ProductPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY47676  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY47676', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '6/19/20 18:35', ';', 'I0ce4c0ee035aa3c7f6d642ff7180c855de4aa0a6')
write pr: HY69268  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY69268', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '10/29/20 17:47', ';', 'I63bf642953556e104791c1828282d8f36d49d049')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/recurrence/RecurrenceRuleCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/recurrence/RecurrenceRuleCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY76253  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/css/TestCharacteristicSetSpecificationCusPage_ITCase.java
data: ('HY76253', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/css/TestCharacteristicSetSpecificationCusPage_ITCase.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/validators/XSSJsonValidator.java

data: ('HY64562', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/rating/TestRatingRuleValidation.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: HY74660  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestAffectedEntity.java
data: ('HY74660', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestAffectedEntity.java', ';', '12/14/20 8:47', ';', 'I732b77617ceb37732af2ab0df12910c3cf479905')
write pr: HY69943  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFiltererFactory.java
data: ('HY69943', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFiltererFactory.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY46587  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestBucketPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestBucketPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY53290  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY53290', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/11/20 9:43', ';', 'I032212ca6e36354471c809b5680c4e67937ba484')
write pr: HY48964  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceTemplateConverter.java
data: ('HY48964', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceTemplateConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY65926  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/BucketRuleConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HX99482  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java
data: ('HX99482', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java', ';', '11/1/19 15:14', ';', 'I4b5b674e92043f3d7602e7355fd694e054577335')
write pr: HY68338  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java
data: ('HY68338', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HY60437  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/PolicyEventUiEntityMapper.java
data: ('HY60437', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/PolicyEventUiEntityMapper.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY45357  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java
data: ('HY45357', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java', ';', '6/8/20 12:33', ';', 'I009b1911b8212d1c89d4182790c57a697436a82c')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/EntityConverterUtilities.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/EntityConverterUtilities.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY43286  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/NotificationTemplateViewImpl.java
data: ('HY43286', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/NotificationTemplateViewImpl.java', ';', '5/20/20 10:24', ';', 'If3044bb51429a6ca736d7f6996eead1937537018')
write pr: HY19427  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/common/rule/Modifier.java
data: ('HY19427', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/common/rule/Modifier.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '7/28/20 13:00', ';', 'I608d4c3f2637d5f657adc0840ea634613b5770b0')
write pr: HY16864  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java
data: ('HY16864', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java', ';', '12/9/19 10:24', ';', 'I689ddb4e648e4443f7d7ce80d4006e33cad787a0')
write pr: HY43286  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/ChargingCapabilityViewImpl.java
data: ('HY43286', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/ChargingCapabilityViewImpl.java', ';', '5/20/20 10:24', ';', 'If3044bb51429a6ca736d7f6996eead1937537018')
write pr: HX98116  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java
data: ('HX98116', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java', ';', '10/29/19 15:16', ';', 'I0ee34afdc8d9fc1b3958d6df2b2c6b663d55d1b8')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionTemplateConverterFactory.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionTemplateConverterFactory.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY16097  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAtLeastOneStrategyPerCfssValidationRule.java
data: ('HY16097', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAtLeastOneStrategyPerCfssValidationRule.java', ';', '12/4/19 17:05', ';', 'I8fa4f26eab9dc21631a24977af3b48ce5105e4d9')
write pr: HY24973  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestRelativeSharingLimitFilter.java
data: ('HY24973', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestRelativeSharingLimitFilter.java', ';', '2/5/20 13:15', ';', 'Ied8cca294197f65fdec96d1b2200ef62b5aa0a38')
write pr: HX66324  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/ActionHook.java
data: ('HX66324', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/ActionHook.java', ';', '5/16/19 20:20', ';', 'Ie3ad0574aed45eae4316e0bc9a1e217254caaf67')
write pr: HX69071  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/RulesCrudService.java
data: ('HX69071', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/RulesCrudService.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskValidator.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskValidator.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeleteLastProductOfferingVersionTransaction.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeleteLastProductOfferingVersionTransaction.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY65601  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateConverter.java
data: ('HY65601', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateConverter.java', ';', '10/5/20 12:19', ';', 'I4b643b6094bf5501295e184f5bb1e3899be343f3')
write pr: HY53290  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java
data: ('HY53290', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY64618  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java
data: ('HY64618', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY39972  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HY39972', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '4/30/20 6:15', ';', 'I629f4a47960687b6a4fa395c674aad8b654a8c16')
write pr: HY42110  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/PoWithPolicyEventFilter.java
data: ('HY42110', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/PoWithPolicyEventFilter.java', ';', '5/13/20 10:51', ';', 'I07db9d0d709036e8e1f18f534482b09e5334ed87')
write pr: HY52425  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsRelationToPolicyValueSpecificationValidationRule.java
data: ('HY52425', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsRelationToPolicyValueSpecificationValidationRule.java', ';', '9/21/20 8:44', ';', 'Ie5adec5215453463107d8b88e8b456cc55bade1f')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/SharingProviderPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/SharingProviderPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY37445  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestSendEndUserNotificationTemplate.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestSendEndUserNotificationTemplate.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleMetaStateDefinitionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleMetaStateDefinitionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY62744  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY62744', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '9/22/20 12:18', ';', 'Id4683d1052a07df9356af7a331089abe25e06324')
write pr: HY53290  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/cache/IdentifiedTask.java
data: ('HY53290', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/cache/IdentifiedTask.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY45357  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java
data: ('HY45357', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java', ';', '6/8/20 12:33', ';', 'I009b1911b8212d1c89d4182790c57a697436a82c')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/BucketTagBucketPriorityListUpdateTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/BucketTagBucketPriorityListUpdateTask.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HX72933  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/NetworkPolicyReferencesValidationRule.java
data: ('HX72933', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/NetworkPolicyReferencesValidationRule.java', ';', '7/19/19 10:47', ';', 'I0853ff1e6a8b107df7e5f7387ffef8bb74635fd1')
write pr: HX77683  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/realmspecific/productoffering/TestProductOfferingPriceSignatureValidationRule.java
data: ('HX77683', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/realmspecific/productoffering/TestProductOfferingPriceSignatureValidationRule.java', ';', '7/10/19 7:04', ';', 'I0c260dfd1b04bc64882f07712adecf311d091547')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceWithBurHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceWithBurHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GenericEntityImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GenericEntityImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestMergableTargetEntriesIdentifier.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestMergableTargetEntriesIdentifier.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/LocalConditionUpdater.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/LocalConditionUpdater.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HX77477  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java
data: ('HX77477', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java', ';', '7/9/19 11:01', ';', 'Ia4274b0770ee49bbe0a2e843e8c33b5128b8a0db')
write pr: HY21738  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProviderFactory.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProviderFactory.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY32754  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY15484  java: oamservices/srimpl/src/main/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/ServiceRegistryConsumerServiceImpl.java
data: ('HY15484', ';', 'oamservices/srimpl/src/main/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/ServiceRegistryConsumerServiceImpl.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')

data: ('HY53290', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListUpdaterForUseCase.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HY13972  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TextFilter.java
data: ('HY13972', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TextFilter.java', ';', '11/25/19 9:26', ';', 'I54725cd2b7a7ff1209d2c4d6b3989e472ed82550')
write pr: HY59766  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY37594  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketdirection/BucketDirectionConverter.java
data: ('HY37594', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketdirection/BucketDirectionConverter.java', ';', '4/20/20 12:46', ';', 'If6ac98a86e1629582e91aba2152632914fb8c201')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestHTMLEncoder.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestHTMLEncoder.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY45351  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/TestGenericUtils.java
data: ('HY45351', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/TestGenericUtils.java', ';', '6/5/20 11:19', ';', 'I8c183012f24dc62d6417601ad3b5c3978731c6fc')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY66450  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestCharacteristicParameter.java
data: ('HY66450', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestCharacteristicParameter.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HX81737  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java
data: ('HX81737', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java', ';', '8/1/19 11:48', ';', 'I2436b1920f9cec78edf9d773752a35755f1ee374')
write pr: HX65525  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/BillingManagementApi.java
data: ('HX65525', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/BillingManagementApi.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/PublishPageTransactionImpl.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/PublishPageTransactionImpl.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HX87622  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/buckettag/TestBucketTagListEntryConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/buckettag/TestBucketTagListEntryConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskFactoryImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskFactoryImpl.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY42110  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/PoWithPolicyEventFilter.java
data: ('HY42110', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/PoWithPolicyEventFilter.java', ';', '5/13/20 10:51', ';', 'I07db9d0d709036e8e1f18f534482b09e5334ed87')
write pr: HY63320  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java
data: ('HY63320', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java', ';', '9/21/20 9:23', ';', 'Ic5c84e1bf79426dece4417727fe48273d957ed81')
write pr: HY66576  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateConverter.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateConverter.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TableContainsBestMatchHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TableContainsBestMatchHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSValidatorFactory.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSValidatorFactory.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY46854  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationProvider.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationProvider.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY18902  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDeactivationDependency_UseCase.java
data: ('HY18902', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDeactivationDependency_UseCase.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY27042  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/CircularDependencyFilter.java
data: ('HY27042', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/CircularDependencyFilter.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestMergableTargetEntriesIdentifier.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestMergableTargetEntriesIdentifier.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPvsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPvsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/GenericPriorityListManagementTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/GenericPriorityListManagementTask.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY60708  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionListProvider.java
data: ('HY60708', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/ActionListProvider.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HX99743  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestEntityReadApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestEntityReadApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedPolicyEventsProvider.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedPolicyEventsProvider.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HX80786  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestAbstractRestEntity.java
data: ('HX80786', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestAbstractRestEntity.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY62458  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/MatchingOffsetOrThresholdCharacteristicResolver.java
data: ('HY62458', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/MatchingOffsetOrThresholdCharacteristicResolver.java', ';', '9/22/20 10:41', ';', 'If9dd66370e0eaae973e30d1aefcc49177159b0a6')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestLegacyTableContainsHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestLegacyTableContainsHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY34694  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/AbstractLifecycleSpecificationValidationRule.java
data: ('HY34694', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/AbstractLifecycleSpecificationValidationRule.java', ';', '3/31/20 12:33', ';', 'Ib2187d52fa5c4f99baaad4225f7b2a3408402972')
write pr: HX77827  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java
data: ('HX77827', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java', ';', '7/8/19 13:34', ';', 'Ic5d84a0ee85b7636ab497b74f4757b82924b01db')
write pr: HX70485  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/action/ExternalNotificationActionDecorator.java
data: ('HX70485', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/action/ExternalNotificationActionDecorator.java', ';', '6/5/19 8:36', ';', 'I16324ae339fee59f254fcf7c8e4bd3ffb8dcf1c7')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/AbstractBucketPriorityListUpdateTask.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/AbstractBucketPriorityListUpdateTask.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY76253  java: integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java
data: ('HY76253', ';', 'integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY52425  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/ConditionTemplatesCrudServiceImpl.java
data: ('HY52425', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/ConditionTemplatesCrudServiceImpl.java', ';', '9/21/20 8:44', ';', 'Ie5adec5215453463107d8b88e8b456cc55bade1f')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTimeOfDayHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTimeOfDayHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX97812  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestDayOfWeekHook.java
data: ('HX97812', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestDayOfWeekHook.java', ';', '10/25/19 12:05', ';', 'I040e76d2d2d379d97b3749bdd03ae64e29167eb8')
write pr: HY52064  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HY52064', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY51063  java: predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java
data: ('HY51063', ';', 'predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY58180  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationNotificationsValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationNotificationsValidationRule.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/SpecificationUpdater.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/SpecificationUpdater.java', ';', '8/12/20 11:25', ';', 'Iad7b93baefb63b2ef22b29f7d00e31302fa7929d')
write pr: HY68338  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java
data: ('HY68338', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HY46412  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCDRProcessingInformationConverter.java
data: ('HY46412', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCDRProcessingInformationConverter.java', ';', '6/8/20 12:02', ';', 'Ib7b7445e62b9536b26ce3f1e9ab35da40126d07e')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java

write pr: HY17547  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java
data: ('HY17547', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HX72323  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/DueDateJiveTest.java
data: ('HX72323', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/DueDateJiveTest.java', ';', '6/20/19 5:01', ';', 'I0ca3d8c20cad05a2e1d66ce99d0e2cf4e3306db3')
write pr: HY24150  java: predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java
data: ('HY24150', ';', 'predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/AbstractRuleListEntryConverter.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/AbstractRuleListEntryConverter.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ExportImportErrorResponseHelper.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ExportImportErrorResponseHelper.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicMandatoryFieldValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicMandatoryFieldValidationRule.java', ';', '7/28/20 7:49', ';', 'I2768f8666a00ff719489ece7b49dc749d3d0c203')
write pr: HY18902  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY15484  java: oamservices/srimpl/src/test/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/TestServiceRegistryConsumerServiceImpl.java
data: ('HY15484', ';', 'oamservices/srimpl/src/test/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/TestServiceRegistryConsumerServiceImpl.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY30915  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java
data: ('HY30915', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java', ';', '3/23/20 16:50', ';', 'If62d9ed0f8048f2909ae3419c26a54335685f422')
write pr: HY34694  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationUsedMetaStatesExistsInCobaRule.java
data: ('HY34694', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationUsedMetaStatesExistsInCobaRule.java', ';', '3/31/20 12:33', ';', 'Ib2187d52fa5c4f99baaad4225f7b2a3408402972')
write pr: HY26736  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestPsToSharingLimitRelationValidationRule.java
data: ('HY26736', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestPsToSharingLimitRelationValidationRule.java', ';', '2/20/20 14:20', ';', 'I15e78f87f7af3b89a90fa1eade34b80f49f8e6f3')
write pr: HY71789  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java
data: ('HY71789', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY58815  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java
data: ('HY58815', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java', ';', '8/24/20 6:59', ';', 'I75afbdde68c1b7e984baabb3b79893028cfd4e3f')
write pr: HX85856  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/TestCustomerFacingServiceSpecificationPageConverter.java
data: ('HX85856', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/TestCustomerFacingServiceSpecificationPageConverter.java', ';', '8/23/19 18:54', ';', 'Iae5a34f067ef652e6d173b322b260e1a553cf115')
write pr: HY70144  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/VreHelper.java
data: ('HY70144', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/VreHelper.java', ';', '10/29/20 19:40', ';', 'I05899c33811521a2758ad203cbfb6b2e311f9671')
write pr: HY24150  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/AbstractTestNormalizedAndCssParameter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/AbstractTestNormalizedAndCssParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HX89960  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/ConnectedChargingService.java
data: ('HX89960', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/ConnectedChargingService.java', ';', '9/16/19 8:48', ';', 'I01684e074fb128c82b1a79ff5474b6116aa0273d')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedPolicyEventsProvider.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedPolicyEventsProvider.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY15429  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/TestRestFramework_ITCase.java
data: ('HY15429', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/TestRestFramework_ITCase.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/RecurrencePriorityListCleanupTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/RecurrencePriorityListCleanupTask.java', ';', '8/12/20 7:45', ';', 'I1f7e85efdce5868c4427e8697ae786c8ab48d073')
write pr: HX83389  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX83389', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/29/19 13:01', ';', 'I44a3f2f2f37bfabe01fe5cb7a8196a513f2a69c9')
write pr: HY24150  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java
data: ('HY24150', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HX94284  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/CharacteristicHelper.java
data: ('HX94284', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/CharacteristicHelper.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HY17038  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/RefillRulesCrudServiceImpl.java
data: ('HY17038', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/refill/RefillRulesCrudServiceImpl.java', ';', '1/7/20 8:37', ';', 'I0858621a15b34f4df45aa5c1eb8fb24b5b93034a')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCollectionContainsConditionHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCollectionContainsConditionHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY27594  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY27594', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '2/25/20 14:41', ';', 'I23d72c9a1f9fc8279f05b90cf87b8fd602436f37')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/BucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/BucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY64562  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY64562', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: HY61542  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java
data: ('HY61542', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java', ';', '9/9/20 6:50', ';', 'If243c7a3661fdacf82b9d32fbd4eb766fb49369d')
write pr: HY57789  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java
data: ('HY57789', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java', ';', '9/15/20 13:09', ';', 'I790df3822588e4dfa40379531dc96a0e8121c574')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY47474  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java
data: ('HY47474', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java', ';', '6/16/20 16:40', ';', 'I4128c314c6a2c792f26958e820f9ce695eb86375')
write pr: HY67817  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestChildUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestChildUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY42535  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/TestRefillRuleListPageConverter.java
data: ('HY42535', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/TestRefillRuleListPageConverter.java', ';', '5/25/20 7:11', ';', 'I0a261b3544a27b878a527f917baf90508e444eb6')
write pr: HY62217  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/HookUtils.java
data: ('HY62217', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/HookUtils.java', ';', '9/15/20 12:51', ';', 'I2c69ecc4fb046a7729e9110c78f8cfdf64353995')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/validators/XSSJsonValidator.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/validators/XSSJsonValidator.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY68338  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponseHelper.java
data: ('HY68338', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponseHelper.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedTagSetSpecificationProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedTagSetSpecificationProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HX65525  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityRead_ITCase.java
data: ('HX65525', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityRead_ITCase.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY27042  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java
data: ('HY27042', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY52064  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRuleContextComposerImplAllEmpty.java
data: ('HY52064', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRuleContextComposerImplAllEmpty.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY62458  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY62458', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '9/22/20 10:41', ';', 'If9dd66370e0eaae973e30d1aefcc49177159b0a6')
write pr: HY18902  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDeactivationDependency_UseCase.java
data: ('HY18902', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDeactivationDependency_UseCase.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY66450  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicDataTypeValidationRule.java
data: ('HY66450', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicDataTypeValidationRule.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java', ';', '8/12/20 11:25', ';', 'Iad7b93baefb63b2ef22b29f7d00e31302fa7929d')
write pr: HY74660  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestUnpublishAffectedEntitiesQueryImpl.java
data: ('HY74660', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestUnpublishAffectedEntitiesQueryImpl.java', ';', '12/14/20 8:47', ';', 'I732b77617ceb37732af2ab0df12910c3cf479905')
write pr: HY58386  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestCharacteristicParameter.java
data: ('HY58386', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestCharacteristicParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY66573  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java

write pr: BSUC:FT8-15:4  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsFiltererTask.java
data: ('BSUC:FT8-15:4', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsFiltererTask.java', ';', '7/17/20 9:56', ';', 'Idad6dba92d65ef28a651e434c95ea8091725e85f')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/commondimension/CommonDimensionPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/commondimension/CommonDimensionPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HX85064  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/bucketdeterminationspecification/TestBdsShadowContainerValueSharingLimitsValidationRule.java
data: ('HX85064', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/bucketdeterminationspecification/TestBdsShadowContainerValueSharingLimitsValidationRule.java', ';', '8/21/19 12:32', ';', 'Ifa2ef7a6f4ee26477d1204f2323e150e83e32dbe')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetsToConditionCharacteristicConverter.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetsToConditionCharacteristicConverter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY64004  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionTypeUtils.java
data: ('HY64004', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionTypeUtils.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '6/9/20 13:16', ';', 'I9c4ec12293c2c83552af2e769209230fbaf70479')
write pr: HY52425  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestConditionTemplatesCrudServiceImpl.java
data: ('HY52425', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestConditionTemplatesCrudServiceImpl.java', ';', '9/21/20 8:44', ';', 'Ie5adec5215453463107d8b88e8b456cc55bade1f')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestCommunityMembershipHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestCommunityMembershipHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY26161  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/scheduledefinition/ScheduleDefinitionListEntry.java
data: ('HY26161', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/scheduledefinition/ScheduleDefinitionListEntry.java', ';', '2/18/20 19:30', ';', 'Ibc8442f80224648e2fccba3139910c08e80cb687')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY26736  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestPsToSharingLimitRelationValidationRule.java
data: ('HY26736', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestPsToSharingLimitRelationValidationRule.java', ';', '2/20/20 14:20', ';', 'I15e78f87f7af3b89a90fa1eade34b80f49f8e6f3')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestProductStateAlreadySuspendedOrInactivated.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/RelationConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/RelationConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HY64618  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/networkpolicy/TestNetworkPolicyCounterSpecificationPage_ITCase.java
data: ('HY64618', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/networkpolicy/TestNetworkPolicyCounterSpecificationPage_ITCase.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY59766  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY59766', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY27847  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java
data: ('HY27847', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY58035  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY58035', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/18/20 12:30', ';', 'Ifb9bbd003acc5d13f17aa3f644a1a7d362c67069')
write pr: HY53290  java: integrationtest/cmd/src/main/java/com/ericsson/bss/rmca/integrationtest/cmd/command/DeactivateCommand.java
data: ('HY53290', ';', 'integrationtest/cmd/src/main/java/com/ericsson/bss/rmca/integrationtest/cmd/command/DeactivateCommand.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY39014  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java
data: ('HY39014', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java', ';', '5/29/20 13:09', ';', 'Idabd0326b92081edbc1a15c35c8f442df6c2e1c5')
write pr: HY65556  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/FixedPriceWithAccumulationHook.java
data: ('HY65556', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/FixedPriceWithAccumulationHook.java', ';', '10/1/20 16:15', ';', 'I6a65926d5c184d8b402d98005393d77c3334617c')
write pr: HX85578  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/TestScheduleDefinitionPage.java
data: ('HX85578', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/TestScheduleDefinitionPage.java', ';', '9/3/19 11:09', ';', 'Id3d14e020239d809698ef7c966de359a6fc8b9b1')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetsToConditionCharacteristicConverter.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetsToConditionCharacteristicConverter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY69943  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestPriorityListUpdateHelper.java
data: ('HY69943', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestPriorityListUpdateHelper.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY71789  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java
data: ('HY71789', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY54229  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HY54229', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '8/5/20 18:08', ';', 'Ib34a1ef75eba28e2d1dde91e972dac0c7f71da1d')
write pr: HY76370  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY58180  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY62744  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY62744', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '9/22/20 12:18', ';', 'Id4683d1052a07df9356af7a331089abe25e06324')
write pr: HY66289  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/customerfacingservicespecification/TestCustomerFacingServiceSpecificationRuleConverter.java
data: ('HY66289', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/customerfacingservicespecification/TestCustomerFacingServiceSpecificationRuleConverter.java', ';', '10/9/20 12:02', ';', 'Iafc612201ba729674eb35808da39adb045bdc866')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestProductStateAlreadySuspendedOrInactivated.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY24489  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/networkpolicycounterspecification/NetworkPolicyCounterWithThresholdValidationRule.java
data: ('HY24489', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/networkpolicycounterspecification/NetworkPolicyCounterWithThresholdValidationRule.java', ';', '2/10/20 14:45', ';', 'I2f577f46a989aa609d41fa72582538e92c682382')
write pr: HY67817  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY53290  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/RequestPropertyFactory.java
data: ('HY53290', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/RequestPropertyFactory.java', ';', '8/13/20 10:10', ';', 'I3f29f482bc8388074283ba83baa978d8360d7768')
write pr: HX77477  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java
data: ('HX77477', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java', ';', '7/9/19 11:01', ';', 'Ia4274b0770ee49bbe0a2e843e8c33b5128b8a0db')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/BucketTagReferenceCharacteristicsDataMigration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/BucketTagReferenceCharacteristicsDataMigration.java', ';', '7/3/20 17:22', ';', 'I04c3cbb7b1907e97150470c4ca5c43f479ebf22c')
write pr: HY18902  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY58373  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetToPolicyValueConverter.java
data: ('HY58373', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetToPolicyValueConverter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY22981  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/DeactivateTransactionImpl.java
data: ('HY22981', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/DeactivateTransactionImpl.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HX69071  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java
data: ('HX69071', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: HY52064  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRuleContextComposerImplAllEmpty.java
data: ('HY52064', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRuleContextComposerImplAllEmpty.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY52844  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java
data: ('HY52844', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java', ';', '7/16/20 14:16', ';', 'I266f0fd1a842bbc64d4b981a33605aa4a36f0b2b')
write pr: HY52959  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/product/TestProductBucketPageConverter.java
data: ('HY52959', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/product/TestProductBucketPageConverter.java', ';', '7/16/20 12:53', ';', 'Iad410d135a8cf62470bd2ea10bdbc7afee5e2606')
write pr: HX84971  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/CustomerContractPageHelper.java
data: ('HX84971', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/CustomerContractPageHelper.java', ';', '8/22/19 9:07', ';', 'I6efb7268fe9aa1f637feccb2cab3a22fae4a87b3')
write pr: HX86471  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java
data: ('HX86471', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY47676  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNotificationOffsetCharacteristicValueValidationRule.java
data: ('HY47676', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNotificationOffsetCharacteristicValueValidationRule.java', ';', '6/19/20 18:35', ';', 'I0ce4c0ee035aa3c7f6d642ff7180c855de4aa0a6')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY38940  java: factory/src/main/java/com/ericsson/bss/rmca/factory/RmcaServiceFactory.java
data: ('HY38940', ';', 'factory/src/main/java/com/ericsson/bss/rmca/factory/RmcaServiceFactory.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestSpecificErrorDetails.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestSpecificErrorDetails.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY35363  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ContractSpecificationVersionImportValidator.java
data: ('HY35363', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ContractSpecificationVersionImportValidator.java', ';', '4/3/20 12:07', ';', 'Idc1d5442147a3362f78678e36589b171570c7583')

write pr: HY40467  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestMoveRecurrenceWithAllowanceHook.java
data: ('HY40467', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestMoveRecurrenceWithAllowanceHook.java', ';', '5/6/20 7:36', ';', 'Ibc8481b4c2fbcafea55bb98d63997221ad9c40e0')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/SingleValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/SingleValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY19473  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/TestBucketBalance.java
data: ('HY19473', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/TestBucketBalance.java', ';', '12/20/19 13:32', ';', 'Id427faf9ca2c1075a078de981e71c884657e94d7')
write pr: HX69071  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucketdeterminationspecification/TestBucketDeterminationSpecificationPage.java
data: ('HX69071', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucketdeterminationspecification/TestBucketDeterminationSpecificationPage.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: BSUC:FT12-1  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java
data: ('BSUC:FT12-1', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java', ';', '6/18/19 16:04', ';', 'I8ebff3b442b44f65fd6334c270466eb6f78c4987')
write pr: HX99743  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestPublishPageTransactionImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestPublishPageTransactionImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GlobalPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GlobalPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationsFrom.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationsFrom.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY38940  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestReferencesFromDataMigration.java
data: ('HY38940', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestReferencesFromDataMigration.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestAbstractTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestAbstractTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY15484  java: restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/ServiceRegistryCommands.java
data: ('HY15484', ';', 'restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/ServiceRegistryCommands.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY76370  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/Characteristics.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/Characteristics.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY27847  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/ConditionListProvider.java
data: ('HY27847', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/ConditionListProvider.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/NormalizedParameter.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/NormalizedParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleResumeActionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleResumeActionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/CommunityMembershipHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/CommunityMembershipHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: BSUC:FT8-15:4  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ImportValidationErrorMessage.java
data: ('BSUC:FT8-15:4', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ImportValidationErrorMessage.java', ';', '7/27/20 6:54', ';', 'I0d6c6f576cb0813ff8bb9bc9f0dbd085ead415a0')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRateHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRateHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY18074  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HY18074', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '12/16/19 10:12', ';', 'I4f3f6e4752d389bdfb0ea92e5aac90d22d650274')
write pr: BSUC:FT8-15:4  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java
data: ('BSUC:FT8-15:4', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java', ';', '7/17/20 9:56', ';', 'Idad6dba92d65ef28a651e434c95ea8091725e85f')
write pr: HY46749  java: jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestErrorHandler.java
data: ('HY46749', ';', 'jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestErrorHandler.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: BSUC:FT8-15:4  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java
data: ('BSUC:FT8-15:4', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java', ';', '7/16/20 18:28', ';', 'I2da2cc0130d715bf1cada10f3685cd11a1ea4f96')
write pr: HY66450  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java
data: ('HY66450', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY66573  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY66573', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '11/12/20 6:38', ';', 'Ia6df1f4889a74a6d75f4a5acdd4c769149afb44c')
write pr: HY46749  java: jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ApplicationScannerImpl.java
data: ('HY46749', ';', 'jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ApplicationScannerImpl.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY26947  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NetworkPolicyCounterSpecificationValidationRuleProvider.java
data: ('HY26947', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NetworkPolicyCounterSpecificationValidationRuleProvider.java', ';', '2/18/20 11:29', ';', 'I2ebd4be614e40e333277f096794a90fee278417f')
write pr: HY30739  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationTransitionToTerminatedValidationRule.java
data: ('HY30739', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationTransitionToTerminatedValidationRule.java', ';', '3/10/20 8:55', ';', 'Ic262489ea61211040cebb42666f8d928ef3346cf')
write pr: HY46749  java: jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestApplicationScannerImpl.java
data: ('HY46749', ';', 'jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestApplicationScannerImpl.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY46854  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationConverter.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationConverter.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY66450  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java
data: ('HY66450', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY12839  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HY12839', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '11/15/19 15:22', ';', 'I7fe17b9acec09f13a00103a81f168cf5060a7d57')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '6/3/19 9:06', ';', 'I37bdbfc1e3f0d67251de9be302d2bf191c5f4e4d')
write pr: HX88018  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleaner.java
data: ('HX88018', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleaner.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: PBI:269  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/refillrule/RefillRuleConverter.java
data: ('PBI:269', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/refillrule/RefillRuleConverter.java', ';', '2/14/20 12:09', ';', 'Ie2b1871e8213ad34e012387b8a3477b86b1b62b7')
write pr: HY63435  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java
data: ('HY63435', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java', ';', '9/23/20 8:35', ';', 'I5184845944f18f7abfd79b90ec666c4e9e878b38')
write pr: HX85100  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageToEntityMapper.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageToEntityMapper.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY23533  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/NormalizedEventSpecificationPageConverter.java
data: ('HY23533', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/NormalizedEventSpecificationPageConverter.java', ';', '1/24/20 17:10', ';', 'I41bac7cc72e65d7c4ba616df7b48043a55cbbb1f')
write pr: HX84971  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/customerspecification/TestCustomerSpecificationPage_ITCase.java
data: ('HX84971', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/customerspecification/TestCustomerSpecificationPage_ITCase.java', ';', '8/22/19 9:07', ';', 'I6efb7268fe9aa1f637feccb2cab3a22fae4a87b3')
write pr: HY19427  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/common/rule/Modifier.java
data: ('HY19427', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/common/rule/Modifier.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HX99743  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestConfigurationDataImpl.java
data: ('HX99743', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestConfigurationDataImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateSharedVersionValuesTransaction.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateSharedVersionValuesTransaction.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '7/3/20 17:22', ';', 'I04c3cbb7b1907e97150470c4ca5c43f479ebf22c')
write pr: HY24150  java: predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/CustomerCharacteristicTemplate.java
data: ('HY24150', ';', 'predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/CustomerCharacteristicTemplate.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY37445  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestSendEndUserNotificationConverter.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestSendEndUserNotificationConverter.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HX80786  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestCatalogManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestCatalogManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java

write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestFailureCounterHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestFailureCounterHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY17547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/converters/TestAbstractCompiledRuleToRmcaEntityConverter.java
data: ('HY17547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/converters/TestAbstractCompiledRuleToRmcaEntityConverter.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueCharacteristicValueMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueCharacteristicValueMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY46749  java: jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ErrorHandler.java
data: ('HY46749', ';', 'jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ErrorHandler.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY34068  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestProductOfferingPriceSpecificationConverterImpl.java
data: ('HY34068', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestProductOfferingPriceSpecificationConverterImpl.java', ';', '4/7/20 10:54', ';', 'Ibe4f38f916221ca280570c38cf66976012f74c0e')
write pr: HY34068  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java
data: ('HY34068', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java', ';', '4/7/20 10:54', ';', 'Ibe4f38f916221ca280570c38cf66976012f74c0e')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/FailureCounterHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/FailureCounterHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY60708  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java
data: ('HY60708', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HX65525  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/EntityReadApi.java
data: ('HX65525', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/EntityReadApi.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestNewVersionPageQueryImpl.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestNewVersionPageQueryImpl.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY27042  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java
data: ('HY27042', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY66576  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/TestSetFixedFeeTemplateConverter.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/TestSetFixedFeeTemplateConverter.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HY42110  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java
data: ('HY42110', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java', ';', '5/13/20 10:51', ';', 'I07db9d0d709036e8e1f18f534482b09e5334ed87')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/Characteristics.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/Characteristics.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY74660  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingspecification/SharingConsumerPageConverter.java
data: ('HY74660', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingspecification/SharingConsumerPageConverter.java', ';', '12/14/20 8:47', ';', 'I732b77617ceb37732af2ab0df12910c3cf479905')
write pr: HY53290  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java
data: ('HY53290', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java', ';', '8/11/20 9:43', ';', 'I032212ca6e36354471c809b5680c4e67937ba484')
write pr: HX84747  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HX97812  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestDayOfWeekHook.java
data: ('HX97812', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestDayOfWeekHook.java', ';', '10/25/19 12:05', ';', 'I040e76d2d2d379d97b3749bdd03ae64e29167eb8')
write pr: HY77550  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestExternalVersionImporter.java
data: ('HY77550', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestExternalVersionImporter.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HY64618  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java
data: ('HY64618', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSFilter.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSFilter.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRankingEntryListFilterer.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRankingEntryListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY53290  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/BucketPriorityListUpdater.java
data: ('HY53290', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/BucketPriorityListUpdater.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY26947  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NetworkPolicyCounterSpecificationValidationRuleProvider.java
data: ('HY26947', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NetworkPolicyCounterSpecificationValidationRuleProvider.java', ';', '2/18/20 11:29', ';', 'I2ebd4be614e40e333277f096794a90fee278417f')
write pr: HY22981  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/RecurrencePriorityListCleanupTask.java
data: ('HY22981', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/RecurrencePriorityListCleanupTask.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TableContainsHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TableContainsHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY46749  java: ui/web/src/main/java/com/ericsson/bss/rmca/web/error/ErrorHandler.java
data: ('HY46749', ';', 'ui/web/src/main/java/com/ericsson/bss/rmca/web/error/ErrorHandler.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListDataMigration.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListDataMigration.java', ';', '7/28/20 11:41', ';', 'I54f5f21378cb0d1b30404844cea865cc5b54df1c')
write pr: HY33683  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HY33683', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '3/25/20 11:55', ';', 'I097f13d8eacbfcb1be15b160dfbcf24b8d563727')
write pr: HY46865  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/AnnouncementPhrase.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/AnnouncementPhrase.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicCustomPurposeValidationRule.java', ';', '8/3/20 9:36', ';', 'I8d1f7b2d9ee1f0042166af77f1e629a5998dd65f')
write pr: HY76253  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java
data: ('HY76253', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY52064  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposer.java
data: ('HY52064', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposer.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueCharacteristicValueMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueCharacteristicValueMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY69952  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketUsageValidationRule.java
data: ('HY69952', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketUsageValidationRule.java', ';', '10/29/20 11:24', ';', 'I068e8e12ed4e10794e3c3ab3b100c3366fe002f1')
write pr: HX99743  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/TestRestCobaImpl.java
data: ('HX99743', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/TestRestCobaImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GlobalPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GlobalPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY21719  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/MultiTypeDateTimeIntervalHook.java
data: ('HY21719', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/MultiTypeDateTimeIntervalHook.java', ';', '1/15/20 13:43', ';', 'If2e9b28a2a3b58713999de6b59fe6ac0d63a204a')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/PageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/PageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/SharingProviderPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/SharingProviderPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/BucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/BucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HX93518  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationListPageConverter.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationListPageConverter.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')
write pr: HY53290  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestBucketPriorityListUpdater.java
data: ('HY53290', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestBucketPriorityListUpdater.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestRelationsFrom.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestRelationsFrom.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HX97730  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestBucket.java
data: ('HX97730', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestBucket.java', ';', '11/4/19 8:45', ';', 'Ic7253ad94aed2a9eb1af7f92a958ca86269fc445')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HY53290  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ProductPriorityListUpdaterForUseCase.java

write pr: HY71789  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java
data: ('HY71789', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/RecurrencePriorityListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/RecurrencePriorityListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY19427  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/NotificationHook.java
data: ('HY19427', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/NotificationHook.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HY26947  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY26947', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '2/18/20 11:29', ';', 'I2ebd4be614e40e333277f096794a90fee278417f')
write pr: HX92625  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/TestLogicAlgorithmSpecificationPageConverter.java
data: ('HX92625', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/TestLogicAlgorithmSpecificationPageConverter.java', ';', '9/27/19 7:56', ';', 'Ic24b9afe4cb3290dd749bf798e43c7408078fe85')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestAbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestAbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY26947  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/ShadowValueContainerFilter.java
data: ('HY26947', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/ShadowValueContainerFilter.java', ';', '2/18/20 11:29', ';', 'I5d2abc92547d213a3d9547a975f29fb822a853c3')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleStateChangeActionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleStateChangeActionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY63320  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java
data: ('HY63320', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java', ';', '9/21/20 9:23', ';', 'Ic5c84e1bf79426dece4417727fe48273d957ed81')
write pr: HY28799  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/NetworkPolicyCounterRuleConverter.java
data: ('HY28799', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/NetworkPolicyCounterRuleConverter.java', ';', '2/26/20 10:45', ';', 'Id5a233c73716d6a04dff11d33750775630a02352')
write pr: HY32754  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY22981  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/BucketPriorityListCleanupForBillingAccountSpecificationTask.java
data: ('HY22981', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/BucketPriorityListCleanupForBillingAccountSpecificationTask.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HY47474  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/SetResponseParameterHook.java
data: ('HY47474', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/SetResponseParameterHook.java', ';', '6/16/20 16:40', ';', 'I4128c314c6a2c792f26958e820f9ce695eb86375')
write pr: HY32754  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/UsageTriggered.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/UsageTriggered.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY64004  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY60437  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/PredefinedEntityIds.java
data: ('HY60437', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/PredefinedEntityIds.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY66450  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/PhysicalResourceCharacteristicValidationRule.java
data: ('HY66450', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/PhysicalResourceCharacteristicValidationRule.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HX81737  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java
data: ('HX81737', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java', ';', '8/1/19 11:48', ';', 'I2436b1920f9cec78edf9d773752a35755f1ee374')
write pr: HY77550  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java
data: ('HY77550', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HY12839  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY12839', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '11/15/19 15:22', ';', 'I7fe17b9acec09f13a00103a81f168cf5060a7d57')
write pr: HY53290  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/Service.java
data: ('HY53290', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/Service.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY59766  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY21738  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleConditionCharacteristicProviderFactory.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleConditionCharacteristicProviderFactory.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/TestScenarioTriggered.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/TestScenarioTriggered.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY53290  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/RmcaScheduledExecutorServiceImpl.java
data: ('HY53290', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/RmcaScheduledExecutorServiceImpl.java', ';', '7/29/20 14:03', ';', 'I6ced8004f0e0214d6f3f0f3ffd915b50b41390e1')
write pr: HY39569  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityRead_ITCase.java
data: ('HY39569', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityRead_ITCase.java', ';', '4/28/20 7:22', ';', 'I380dbd5a7bb147bf035a66ad24d3e4f135dee342')
write pr: HY76370  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/TestRestListEntityImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/TestRestListEntityImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY19427  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java
data: ('HY19427', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HY76370  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestRestListProductPriorityListConverterImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestRestListProductPriorityListConverterImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY66576  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/TestSetFixedFeeTemplateConverter.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/TestSetFixedFeeTemplateConverter.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueLink.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueLink.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY45357  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY45357', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '6/8/20 12:33', ';', 'I009b1911b8212d1c89d4182790c57a697436a82c')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/SpecificErrorDetails.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/SpecificErrorDetails.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY71789  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java
data: ('HY71789', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY39316  java: persistenceimpl/src/test/java/com/ericsson/bss/rmca/persistenceimpl/TestEntitySchemaFactory.java
data: ('HY39316', ';', 'persistenceimpl/src/test/java/com/ericsson/bss/rmca/persistenceimpl/TestEntitySchemaFactory.java', ';', '4/30/20 12:16', ';', 'Ia281a738a056930d1ff0925c90a9c7990a5a506f')
write pr: HY21738  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProviderFactory.java
data: ('HY21738', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestPossibleConditionCharacteristicProviderFactory.java', ';', '1/22/20 7:28', ';', 'I15dd77f2a8c8a45842a3d54f9b781b24f76de4eb')
write pr: HY52844  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java
data: ('HY52844', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java', ';', '7/16/20 14:16', ';', 'I266f0fd1a842bbc64d4b981a33605aa4a36f0b2b')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY58373  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetToPolicyValueConverter.java
data: ('HY58373', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetToPolicyValueConverter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY71789  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/CarryOverProductBucketActionValidationRule.java
data: ('HY71789', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/CarryOverProductBucketActionValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY64004  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeUtils.java
data: ('HY64004', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeUtils.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY24489  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY24489', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '2/10/20 14:45', ';', 'I2f577f46a989aa609d41fa72582538e92c682382')
write pr: HX86471  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportBillingAccountSpecificationBucketPriorityTask.java
data: ('HX86471', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportBillingAccountSpecificationBucketPriorityTask.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/DuplicatePageQueryImpl.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/DuplicatePageQueryImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TieredValuesConverter.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TieredValuesConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY68832  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java
data: ('HY68832', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java', ';', '10/26/20 8:48', ';', 'Id497fe04573e5d35a1dd0b1a9c1abe436c863dd9')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/DateTimeIntervalConstantHook.java

data: ('HY15429', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/TestRestFramework_ITCase.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/BucketTagReferenceCharacteristicsDataMigration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/BucketTagReferenceCharacteristicsDataMigration.java', ';', '7/3/20 17:22', ';', 'I04c3cbb7b1907e97150470c4ca5c43f479ebf22c')
write pr: HY66800  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/TestRefillActionCombinationValidationRule.java
data: ('HY66800', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/TestRefillActionCombinationValidationRule.java', ';', '10/14/20 10:06', ';', 'Ide074a76c875222e79e4e0a9fe978b68068eaf32')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY30739  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY30739', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '3/10/20 8:55', ';', 'Ic262489ea61211040cebb42666f8d928ef3346cf')
write pr: HY63435  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/event/TestBasPriorityListManagement_ITCase.java
data: ('HY63435', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/event/TestBasPriorityListManagement_ITCase.java', ';', '9/23/20 8:35', ';', 'I5184845944f18f7abfd79b90ec666c4e9e878b38')
write pr: HY54229  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HY54229', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '8/5/20 18:08', ';', 'Ib34a1ef75eba28e2d1dde91e972dac0c7f71da1d')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBucketTagBucketPriorityListManagement.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBucketTagBucketPriorityListManagement.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedBillingAccountHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedBillingAccountHelper.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HY31764  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestPoPageCharacteristicsHandler.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestPoPageCharacteristicsHandler.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRealignedTieredBucketBalanceWithBurHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRealignedTieredBucketBalanceWithBurHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY15429  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/networkpolicy/TestNetworkPolicyGroupPriorityListPage_ITCase.java
data: ('HY15429', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/networkpolicy/TestNetworkPolicyGroupPriorityListPage_ITCase.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '6/9/20 13:16', ';', 'I9c4ec12293c2c83552af2e769209230fbaf70479')
write pr: HY62217  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/BucketAddHook.java
data: ('HY62217', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/BucketAddHook.java', ';', '9/15/20 12:51', ';', 'I2c69ecc4fb046a7729e9110c78f8cfdf64353995')
write pr: HY15429  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/cfs/TestCustomerFacingServiceSpecification_ITCase.java
data: ('HY15429', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/cfs/TestCustomerFacingServiceSpecification_ITCase.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HX66324  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketAddRecurrenceHook.java
data: ('HX66324', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketAddRecurrenceHook.java', ';', '5/16/19 20:20', ';', 'Ie3ad0574aed45eae4316e0bc9a1e217254caaf67')
write pr: HX99012  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/TestCobaEntityImpl.java
data: ('HX99012', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/TestCobaEntityImpl.java', ';', '10/30/19 11:51', ';', 'I86b611a35e28424205ccfb454478d3ca41da3c72')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/DataImport.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/DataImport.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY15429  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/TsCoreAbstractTest.java
data: ('HY15429', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/TsCoreAbstractTest.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedRecurrencePrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedRecurrencePrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY64547  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/modals/CharacteristicsManagerPage.java
data: ('HY64547', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/modals/CharacteristicsManagerPage.java', ';', '10/13/20 13:24', ';', 'I34be2235ff68618ba5500f06e560cd8fbaf3c540')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestCommunityMembershipHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestCommunityMembershipHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX64747  java: persistenceimpl/src/test/java/com/ericsson/bss/rmca/persistenceimpl/notification/TestEntityChangeServicePersistenceImpl.java
data: ('HX64747', ';', 'persistenceimpl/src/test/java/com/ericsson/bss/rmca/persistenceimpl/notification/TestEntityChangeServicePersistenceImpl.java', ';', '5/13/19 15:01', ';', 'I2bd5a4f0534837f720ea0704947eb9c7c9df1178')
write pr: HY74660  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/AffectedEntity.java
data: ('HY74660', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/AffectedEntity.java', ';', '12/14/20 8:47', ';', 'I732b77617ceb37732af2ab0df12910c3cf479905')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTimeOfDayOfWeekHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTimeOfDayOfWeekHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HY59800  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HX69993  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX69993', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '7/18/19 12:45', ';', 'I23cb612542829282fa9ec5b6ca9e5c5ae9fe86be')
write pr: HY53290  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java
data: ('HY53290', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java', ';', '8/11/20 8:18', ';', 'I9ed5e3c13d4f10b31cd42da0db5e4fb4cb7001ed')
write pr: HX84594  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedCustomerSpecificationProvider.java
data: ('HX84594', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedCustomerSpecificationProvider.java', ';', '9/6/19 13:45', ';', 'I12b28e8f3dcffedd165fed986a143b76cfd803e1')
write pr: HY60437  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/HiddenUiEntityMapper.java
data: ('HY60437', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/HiddenUiEntityMapper.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY77550  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ExternalVersionData.java
data: ('HY77550', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ExternalVersionData.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HY53290  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/BucketPriorityListImporter.java
data: ('HY53290', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/BucketPriorityListImporter.java', ';', '8/13/20 5:49', ';', 'Ie9ed89f74e885cee6adae9c4c834d77e03934382')
write pr: HX99482  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/compilers/rules/AbstractRuleCompiler.java
data: ('HX99482', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/compilers/rules/AbstractRuleCompiler.java', ';', '11/1/19 15:14', ';', 'I4b5b674e92043f3d7602e7355fd694e054577335')
write pr: HX70485  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/CustomerFacingServiceSpecificationPageConverter.java
data: ('HX70485', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/CustomerFacingServiceSpecificationPageConverter.java', ';', '6/4/19 11:29', ';', 'I23fa95b6c7e555cf722ae0cde62822897cdf8dec')
write pr: HY15429  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/networkpolicy/TestNetworkPolicyCounterSpecificationPage_ITCase.java
data: ('HY15429', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/networkpolicy/TestNetworkPolicyCounterSpecificationPage_ITCase.java', ';', '12/18/19 17:45', ';', 'Ifecaa62fbdf9ba22c5e583c12823142c8c5f486b')
write pr: HX86471  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/DryRunImporter.java
data: ('HX86471', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/DryRunImporter.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY48964  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/availableunits/AvailableUnitsTemplateConverter.java
data: ('HY48964', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/availableunits/AvailableUnitsTemplateConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY17547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/ScenarioTriggeredRuleCompiler.java
data: ('HY17547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/ScenarioTriggeredRuleCompiler.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HY65732  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java
data: ('HY65732', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestContractSpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestContractSpecificationConverter.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY69751  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scheduledefinition/TestSpecificationHelper.java
data: ('HY69751', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scheduledefinition/TestSpecificationHelper.java', ';', '10/30/20 15:47', ';', 'If2bb29b073b4090995afd493fd5dd11db3b5b956')
write pr: HX85100  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/pages/ars/TestAgreementSpecificationPage_ITCase.java
data: ('HX85100', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/pages/ars/TestAgreementSpecificationPage_ITCase.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/TestBaseEntityDependencyPopulationImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/TestBaseEntityDependencyPopulationImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY58815  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ProductPriorityListUpdaterForUseCase.java
data: ('HY58815', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ProductPriorityListUpdaterForUseCase.java', ';', '8/24/20 8:36', ';', 'I9c669a4ba2e3bdd9d68d7c57e65d98bf5ed9cb0c')
write pr: HX66291  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ReferenceHelper.java
data: ('HX66291', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ReferenceHelper.java', ';', '5/9/19 11:36', ';', 'I6e9101173b69e4e6a91c58c807661880c70d2ac1')
write pr: HY65926  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HY48964  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HY48964', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')

write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/RelationConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/RelationConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HY18902  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationUtility.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationUtility.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY18074  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HY18074', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '12/16/19 10:12', ';', 'I4f3f6e4752d389bdfb0ea92e5aac90d22d650274')
write pr: HX99743  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/FillPageQueryImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/FillPageQueryImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY65926  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucket/TestBucketRuleConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/BucketTagBucketPriorityListUpdateTask.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/BucketTagBucketPriorityListUpdateTask.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY46587  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGenericEntityImporter.java
data: ('HY46587', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGenericEntityImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HX98676  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterProvider.java
data: ('HX98676', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterProvider.java', ';', '10/30/19 8:43', ';', 'I91935eb3f45356a33db4f3b9e82ce5323c7fa6e7')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY58373  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/AbstractNormalizedAndCssParameter.java
data: ('HY58373', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/AbstractNormalizedAndCssParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY64508  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/CharacteristicAnnotation.java
data: ('HY64508', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/CharacteristicAnnotation.java', ';', '9/28/20 13:54', ';', 'Idb2eac49f3af0b019214c20a423d890f66e960ea')
write pr: HY53290  java: integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java
data: ('HY53290', ';', 'integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java', ';', '8/13/20 10:10', ';', 'I3f29f482bc8388074283ba83baa978d8360d7768')
write pr: HY53290  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestBucketPriorityListImporter.java
data: ('HY53290', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestBucketPriorityListImporter.java', ';', '8/13/20 5:49', ';', 'Ie9ed89f74e885cee6adae9c4c834d77e03934382')
write pr: HX94284  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestCharacteristicHelper.java
data: ('HX94284', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestCharacteristicHelper.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HY50582  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAccumulateConsumedUnitsValidationRule.java
data: ('HY50582', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAccumulateConsumedUnitsValidationRule.java', ';', '7/8/20 6:37', ';', 'I9c1fa14935e1d01bb32cda5ba5e060ab6c9a8ca2')
write pr: HY15429  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcefacingservicespecification/RfssChargingServiceValidationRule.java
data: ('HY15429', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcefacingservicespecification/RfssChargingServiceValidationRule.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HY66289  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/customerfacingservicespecification/CustomerFacingServiceSpecificationRuleConverter.java
data: ('HY66289', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/customerfacingservicespecification/CustomerFacingServiceSpecificationRuleConverter.java', ';', '10/9/20 12:02', ';', 'Iafc612201ba729674eb35808da39adb045bdc866')
write pr: HY76253  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/css/TestCharacteristicSetSpecificationCusPage_ITCase.java
data: ('HY76253', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/css/TestCharacteristicSetSpecificationCusPage_ITCase.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/PriorityGroupConverter.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/PriorityGroupConverter.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY72852  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/commondimension/TestCommonDimensionPageConverter.java
data: ('HY72852', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/commondimension/TestCommonDimensionPageConverter.java', ';', '11/13/20 10:03', ';', 'I25f3405b59d3479a5546f47e4206fdbc0ee8e681')
write pr: HX65525  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/BillingManagementApi.java
data: ('HX65525', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/BillingManagementApi.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY24489  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY24489', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '2/10/20 14:45', ';', 'I2f577f46a989aa609d41fa72582538e92c682382')
write pr: HY76253  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/css/TestCharacteristicSetSpecificationConverter.java
data: ('HY76253', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/css/TestCharacteristicSetSpecificationConverter.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY53290  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestRmcaServicesFactory.java
data: ('HY53290', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestRmcaServicesFactory.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY68338  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java
data: ('HY68338', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HY28857  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/AbstractNesAndCssNoCharacteristicsHook.java
data: ('HY28857', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/AbstractNesAndCssNoCharacteristicsHook.java', ';', '2/26/20 14:45', ';', 'I0ba82cd3da3b2d2df57a62bfd0403a8419b0906f')
write pr: HY47676  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductOfferingValidationRuleProvider.java
data: ('HY47676', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductOfferingValidationRuleProvider.java', ';', '6/19/20 18:35', ';', 'I0ce4c0ee035aa3c7f6d642ff7180c855de4aa0a6')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX86471  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportBillingAccountSpecificationBucketPriorityTask.java
data: ('HX86471', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportBillingAccountSpecificationBucketPriorityTask.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HX86471  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/service/profile/ValidationProfile.java
data: ('HX86471', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/service/profile/ValidationProfile.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HX77683  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/realmspecific/productoffering/TestProductOfferingPriceSignatureValidationRule.java
data: ('HX77683', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/realmspecific/productoffering/TestProductOfferingPriceSignatureValidationRule.java', ';', '7/10/19 7:04', ';', 'I0c260dfd1b04bc64882f07712adecf311d091547')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY64004  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionTypeUtils.java
data: ('HY64004', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionTypeUtils.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HX71846  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestCharacteristicValueRangeNotAllowedToConstrictValidationRule.java
data: ('HX71846', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestCharacteristicValueRangeNotAllowedToConstrictValidationRule.java', ';', '6/7/19 9:12', ';', 'I5cfba41fc95291f848a1e985b603338a47b7a525')
write pr: HX66291  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingBillCycleAlignedAllowedOnlyForPostpaidValidationRule.java
data: ('HX66291', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingBillCycleAlignedAllowedOnlyForPostpaidValidationRule.java', ';', '5/9/19 11:36', ';', 'I6e9101173b69e4e6a91c58c807661880c70d2ac1')
write pr: HY37445  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestNotificationTemplateProvider.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestNotificationTemplateProvider.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkPolicyGroupPriorityListDataMigration.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkPolicyGroupPriorityListDataMigration.java', ';', '7/28/20 11:41', ';', 'I68f544fdbeb48f50c4f4587e45f8c38710e937ae')
write pr: HY76253  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CharacteristicSetSpecificationConverter.java
data: ('HY76253', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CharacteristicSetSpecificationConverter.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY51063  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestCharacteristicMandatoryFieldValidationRule.java
data: ('HY51063', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestCharacteristicMandatoryFieldValidationRule.java', ';', '7/28/20 7:49', ';', 'I2768f8666a00ff719489ece7b49dc749d3d0c203')
write pr: HY67817  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestChildUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestChildUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueRange.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueRange.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HX77827  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HX77827', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '7/8/19 13:34', ';', 'Ic5d84a0ee85b7636ab497b74f4757b82924b01db')
write pr: HY40790  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedRefillBusinessStrategyProvider.java
data: ('HY40790', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedRefillBusinessStrategyProvider.java', ';', '5/5/20 8:18', ';', 'I62bd89465d6fd12133d7d4072e17e560252eb873')

data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY51063  java: predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java
data: ('HY51063', ';', 'predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY59800  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountBucketPriorityListToPageConverter.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY24061  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/TestProvisionConfigurationServiceImpl.java
data: ('HY24061', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/TestProvisionConfigurationServiceImpl.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY42110  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java
data: ('HY42110', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java', ';', '5/13/20 10:51', ';', 'I07db9d0d709036e8e1f18f534482b09e5334ed87')
write pr: HX66291  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ReferenceHelper.java
data: ('HX66291', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ReferenceHelper.java', ';', '5/9/19 11:36', ';', 'I6e9101173b69e4e6a91c58c807661880c70d2ac1')
write pr: HY59800  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java
data: ('HY59800', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HX71520  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/TestRulesCrudServiceImpl.java
data: ('HX71520', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/TestRulesCrudServiceImpl.java', ';', '6/25/19 11:55', ';', 'I3b716397d7f727ee9f01936e96bae29fb123c9e8')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HY65889  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY65889', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '10/22/20 14:16', ';', 'I4cf4061ac1afe3996cc9d47c2e71cf1d3f6b6500')
write pr: HY58373  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetToPolicyValueConverter.java
data: ('HY58373', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetToPolicyValueConverter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY43069  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/ChargingCapabilityViewImpl.java
data: ('HY43069', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/ChargingCapabilityViewImpl.java', ';', '5/20/20 18:33', ';', 'I679551f00a74c7c9d676970107ef617630af0112')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCascadingActivateTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCascadingActivateTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCustomerHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCustomerHelper.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GenericEntityImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GenericEntityImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY55461  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncement.java
data: ('HY55461', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/SendVoiceAnnouncement.java', ';', '8/5/20 16:52', ';', 'I6fa074f931bbd292ab831b1066d789f5748042c5')
write pr: HY64936  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java
data: ('HY64936', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java', ';', '9/30/20 8:32', ';', 'I957cd8155513b532592f30d26f778c5141f751dd')
write pr: HY24150  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketoffset/BucketOffsetConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketoffset/BucketOffsetConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestDayOfWeekHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestDayOfWeekHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY62744  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java
data: ('HY62744', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java', ';', '9/22/20 12:18', ';', 'Id4683d1052a07df9356af7a331089abe25e06324')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GenericEntityImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/GenericEntityImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY15484  java: oamservices/srimpl/src/test/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/TestServiceRegistryConsumerServiceImpl.java
data: ('HY15484', ';', 'oamservices/srimpl/src/test/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/TestServiceRegistryConsumerServiceImpl.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HX88018  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleaner.java
data: ('HX88018', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleaner.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/PoPageCharacteristicsHandler.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/PoPageCharacteristicsHandler.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestHTMLEncoder.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestHTMLEncoder.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY53290  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY53290', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/11/20 11:20', ';', 'I08ce3d0261448d2211a99f6aaf2656007f9907bb')
write pr: HY53290  java: integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java
data: ('HY53290', ';', 'integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java', ';', '8/12/20 7:45', ';', 'I1f7e85efdce5868c4427e8697ae786c8ab48d073')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleBaseStateTransitionRuleConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleBaseStateTransitionRuleConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY27042  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java
data: ('HY27042', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestWithFilterFactory.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY27594  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY27594', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '2/25/20 14:41', ';', 'I23d72c9a1f9fc8279f05b90cf87b8fd602436f37')
write pr: HY66576  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/TestCommonActionTemplateUtils.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/TestCommonActionTemplateUtils.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HY32754  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/SlimPriority.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/SlimPriority.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/AbstractTestNormalizedAndCssParameter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/AbstractTestNormalizedAndCssParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY30739  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY30739', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '3/10/20 8:55', ';', 'Ic262489ea61211040cebb42666f8d928ef3346cf')
write pr: HY64547  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/modals/CharacteristicsManagerPage.java
data: ('HY64547', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/modals/CharacteristicsManagerPage.java', ';', '10/13/20 13:24', ';', 'I34be2235ff68618ba5500f06e560cd8fbaf3c540')
write pr: HX71785  java: notificationimpl/consumer/src/test/java/com/ericsson/bss/rmca/notificationimpl/consumer/TestNotificationConsumerServiceImpl.java
data: ('HX71785', ';', 'notificationimpl/consumer/src/test/java/com/ericsson/bss/rmca/notificationimpl/consumer/TestNotificationConsumerServiceImpl.java', ';', '6/4/19 6:18', ';', 'I822d1145bd9920f9b245a0ff4679ce39c7fa7cbb')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestBucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestBucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCascadingLockTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCascadingLockTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HX80786  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestValidatePriorityChangeCatalogManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY60437  java: integrationtest/common/src/main/java/com/ericsson/bss/rmca/integrationtest/common/ExportAsserter.java
data: ('HY60437', ';', 'integrationtest/common/src/main/java/com/ericsson/bss/rmca/integrationtest/common/ExportAsserter.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '6/4/20 11:13', ';', 'I16b5fc177b2155b8b6eb26f249690a9ab4f4d990')
write pr: HX69071  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingusagestrategy/SharingUsageStrategyPageConverter.java
data: ('HX69071', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingusagestrategy/SharingUsageStrategyPageConverter.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')

write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HX70206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/EntityDependencyPopulationImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/EntityDependencyPopulationImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY59800  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY43705  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/TestRefillSendExternalNotificationTemplateProvider.java
data: ('HY43705', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/TestRefillSendExternalNotificationTemplateProvider.java', ';', '5/20/20 8:56', ';', 'I2d85a2de97585e405042f92048da30836f514228')
write pr: HY15429  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcefacingservicespecification/TestRfssChargingServiceValidationRule.java
data: ('HY15429', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcefacingservicespecification/TestRfssChargingServiceValidationRule.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HX99743  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestServiceLocationImpl.java
data: ('HX99743', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestServiceLocationImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedSharingProviderPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedSharingProviderPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestCustomerSpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestCustomerSpecificationConverter.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/RecurrencePriorityListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/RecurrencePriorityListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPage.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPage.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPage.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPage.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/TestPresetToPolicyValueConverter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/TestPresetToPolicyValueConverter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY43705  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/TestRefillSendExternalNotificationTemplateProvider.java
data: ('HY43705', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/TestRefillSendExternalNotificationTemplateProvider.java', ';', '5/20/20 8:56', ';', 'I2d85a2de97585e405042f92048da30836f514228')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestNormalizedParameter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestNormalizedParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HX99743  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestCreatePageTransactionImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestCreatePageTransactionImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY64938  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/ThresholdOffsetUniqueExternalIdValidationRule.java
data: ('HY64938', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/ThresholdOffsetUniqueExternalIdValidationRule.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HX81737  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/TestNetworkPolicyCounterPageConverter.java
data: ('HX81737', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/TestNetworkPolicyCounterPageConverter.java', ';', '8/1/19 11:48', ';', 'I2436b1920f9cec78edf9d773752a35755f1ee374')
write pr: HY65601  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterTemplateConverter.java
data: ('HY65601', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterTemplateConverter.java', ';', '10/5/20 12:19', ';', 'I4b643b6094bf5501295e184f5bb1e3899be343f3')
write pr: HY22981  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleanupTaskHelper.java
data: ('HY22981', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleanupTaskHelper.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY16097  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/ResourceFacingServiceSpecificationPageConverter.java
data: ('HY16097', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/ResourceFacingServiceSpecificationPageConverter.java', ';', '12/4/19 17:05', ';', 'I8fa4f26eab9dc21631a24977af3b48ce5105e4d9')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueRange.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueRange.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY64938  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/ThresholdOffsetUniqueExternalIdValidationRule.java
data: ('HY64938', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/ThresholdOffsetUniqueExternalIdValidationRule.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HY21719  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestMultiTypeDateTimeIntervalHook.java
data: ('HY21719', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestMultiTypeDateTimeIntervalHook.java', ';', '1/15/20 13:43', ';', 'If2e9b28a2a3b58713999de6b59fe6ac0d63a204a')
write pr: HY18902  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestUpstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestUpstreamDependencyAnalyzer.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredRateHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredRateHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestAnnouncementPhrase.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestAnnouncementPhrase.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY12839  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java
data: ('HY12839', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java', ';', '11/15/19 15:22', ';', 'I7fe17b9acec09f13a00103a81f168cf5060a7d57')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/recurrence/RecurrenceRuleCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/recurrence/RecurrenceRuleCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY21708  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestProductStateAlreadySuspendedOrInactivated.java
data: ('HY21708', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'I656f6de36d0b8fad46310f767d609f2c4552f438')
write pr: HX84594  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedContractSpecificationProvider.java
data: ('HX84594', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedContractSpecificationProvider.java', ';', '9/6/19 13:45', ';', 'I12b28e8f3dcffedd165fed986a143b76cfd803e1')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TableContainsBestMatchHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TableContainsBestMatchHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY22981  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCleanupTaskHelper.java
data: ('HY22981', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCleanupTaskHelper.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HY53290  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java
data: ('HY53290', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java', ';', '8/14/20 6:20', ';', 'I0506e688a199098a2b3f451677f7791b55711a39')
write pr: HY64004  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY42777  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java
data: ('HY42777', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java', ';', '5/29/20 6:07', ';', 'Ie9ad14d2533e0d7a6c9cad84f2928d596556ec55')
write pr: HY71663  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HY71663', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '11/9/20 12:40', ';', 'I8d6817cce75a006cbb4fcc22710bb40b185b43c2')
write pr: HY46854  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestRuleConverterContext.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestRuleConverterContext.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HX72933  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/TestNetworkPolicyReferencesValidationRule.java
data: ('HX72933', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/TestNetworkPolicyReferencesValidationRule.java', ';', '7/19/19 10:47', ';', 'I0853ff1e6a8b107df7e5f7387ffef8bb74635fd1')
write pr: HY67817  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java
data: ('HY67817', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestUiEntityFactoryForImport.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY60437  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestHiddenEntityMapperForPolicyEvent.java

data: ('HY37445', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/TestNotificationTemplateProvider.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY46854  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/TestScenarioTriggeredActionListProvider.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/TestScenarioTriggeredActionListProvider.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY58180  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HX99743  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/PublishPageTransactionImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/PublishPageTransactionImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY62833  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java
data: ('HY62833', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java', ';', '9/15/20 8:22', ';', 'I40d8b797ef0bd8934f9fbab1388e111932def93a')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '6/3/19 9:06', ';', 'I37bdbfc1e3f0d67251de9be302d2bf191c5f4e4d')
write pr: HY40790  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedRefillBusinessStrategyProvider.java
data: ('HY40790', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedRefillBusinessStrategyProvider.java', ';', '5/5/20 8:18', ';', 'I62bd89465d6fd12133d7d4072e17e560252eb873')
write pr: HY42535  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/TestRefillRuleListPageConverter.java
data: ('HY42535', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/TestRefillRuleListPageConverter.java', ';', '5/25/20 7:11', ';', 'I0a261b3544a27b878a527f917baf90508e444eb6')
write pr: HX70244  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/IndexUpdateResolver.java
data: ('HX70244', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/IndexUpdateResolver.java', ';', '6/5/19 12:29', ';', 'I86f2a81befdfd840ceb2df5184cf0a355c31fd6e')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestBucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestBucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY34694  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationUsedMetaStatesExistsInCobaRule.java
data: ('HY34694', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationUsedMetaStatesExistsInCobaRule.java', ';', '3/31/20 12:33', ';', 'Ib2187d52fa5c4f99baaad4225f7b2a3408402972')
write pr: HX90744  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java
data: ('HX90744', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY77550  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ExternalVersionData.java
data: ('HY77550', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/ExternalVersionData.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HY66450  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java
data: ('HY66450', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HX72276  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicModificationInVersionRule.java
data: ('HX72276', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicModificationInVersionRule.java', ';', '6/17/19 19:09', ';', 'I37a4da60a582bda294fa02a01ea6e2979ff93861')
write pr: HY46854  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HY46854', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryParameterFlags.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryParameterFlags.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX65525  java: restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java
data: ('HX65525', ';', 'restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY43286  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestNotificationTemplateViewImpl.java
data: ('HY43286', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestNotificationTemplateViewImpl.java', ';', '5/20/20 10:24', ';', 'If3044bb51429a6ca736d7f6996eead1937537018')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSJsonValidator.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSJsonValidator.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY60437  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestHiddenEntityMapperForPolicyEvent.java
data: ('HY60437', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestHiddenEntityMapperForPolicyEvent.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '6/8/20 18:37', ';', 'I83a8d3f388c393bb2d9836cac3f723fd33c7ecb4')
write pr: HY46587  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestProductPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestProductPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HX89960  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/ConnectedSpecificationService.java
data: ('HX89960', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/ConnectedSpecificationService.java', ';', '9/16/19 8:48', ';', 'I01684e074fb128c82b1a79ff5474b6116aa0273d')
write pr: HY13972  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TextFilter.java
data: ('HY13972', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TextFilter.java', ';', '11/25/19 9:26', ';', 'I54725cd2b7a7ff1209d2c4d6b3989e472ed82550')
write pr: HX84747  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/TestRelationConverter.java', ';', '8/19/19 10:42', ';', 'I7d0949edba5ace28a6de92ed2517047fee2e26da')
write pr: HX69993  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicValueUomDecimalsValidationRule.java
data: ('HX69993', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicValueUomDecimalsValidationRule.java', ';', '7/18/19 12:45', ';', 'I23cb612542829282fa9ec5b6ca9e5c5ae9fe86be')
write pr: HX70206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/EntityDependencyPopulationImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/EntityDependencyPopulationImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY17547  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java
data: ('HY17547', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HY17608  java: oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/internal/AlarmServiceImpl.java
data: ('HY17608', ';', 'oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/internal/AlarmServiceImpl.java', ';', '12/11/19 11:16', ';', 'I81823a0a5a65ea1a2b66caa543737e2b0cdc2abe')
write pr: HY65556  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/rating/RatingActionTemplateCompiler.java
data: ('HY65556', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/rating/RatingActionTemplateCompiler.java', ';', '10/1/20 16:15', ';', 'I6a65926d5c184d8b402d98005393d77c3334617c')
write pr: HY58815  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java
data: ('HY58815', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/RankingEntryListMerger.java', ';', '8/24/20 6:59', ';', 'I75afbdde68c1b7e984baabb3b79893028cfd4e3f')
write pr: HX72933  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/NetworkPolicyReferencesValidationRule.java
data: ('HX72933', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/NetworkPolicyReferencesValidationRule.java', ';', '7/19/19 10:47', ';', 'I0853ff1e6a8b107df7e5f7387ffef8bb74635fd1')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY46587  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGenericEntityImporter.java
data: ('HY46587', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGenericEntityImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSJsonValidator.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSJsonValidator.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY54229  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY54229', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '8/5/20 18:08', ';', 'Ib34a1ef75eba28e2d1dde91e972dac0c7f71da1d')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/SelectableScenarioIdHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/SelectableScenarioIdHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY48964  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HY48964', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketoffset/TestBucketOffsetConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketoffset/TestBucketOffsetConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/validators/XSSValidator.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/validators/XSSValidator.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY64562  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY64562', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestSpecificErrorDetails.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestSpecificErrorDetails.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY17608  java: oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/internal/AlarmHolder.java
data: ('HY17608', ';', 'oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/internal/AlarmHolder.java', ';', '12/11/19 11:16', ';', 'I81823a0a5a65ea1a2b66caa543737e2b0cdc2abe')
write pr: HX95001  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/resourcefacingservicespecification/ResourceFacingServiceSpecificationRuleConverter.java
data: ('HX95001', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/resourcefacingservicespecification/ResourceFacingServiceSpecificationRuleConverter.java', ';', '10/11/19 7:44', ';', 'I1a01188be848f09d8d73346804eb5e3d5fffb12c')
write pr: HY58180  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY67817  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/ChildUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/ChildUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/DuplicatePageQueryImpl.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/DuplicatePageQueryImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')

write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HX83389  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX83389', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '8/29/19 13:01', ';', 'I44a3f2f2f37bfabe01fe5cb7a8196a513f2a69c9')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HY66304  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/packages/bucketusagerule/TestBucketUsageRule.java
data: ('HY66304', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/packages/bucketusagerule/TestBucketUsageRule.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY69943  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestBucketPriorityListFiltererFactory.java
data: ('HY69943', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestBucketPriorityListFiltererFactory.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY21740  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/EventReasonCode.java
data: ('HY21740', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/EventReasonCode.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY58386  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestNormalizedParameter.java
data: ('HY58386', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestNormalizedParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY17547  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRestProductSpecificationPageImpl.java
data: ('HY17547', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRestProductSpecificationPageImpl.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HX74509  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/TestAbstractTieredConditionConverter.java
data: ('HX74509', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/TestAbstractTieredConditionConverter.java', ';', '6/19/19 6:15', ';', 'I9b834546f9a32ad7dba545810d206b399d0b34ad')
write pr: HX84971  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/customerspecification/TestCustomerSpecificationLifeCycleValuesValidationRule.java
data: ('HX84971', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/customerspecification/TestCustomerSpecificationLifeCycleValuesValidationRule.java', ';', '8/26/19 10:22', ';', 'Ib6b832e519cb11b7aaf50621eff3edbe92e8d636')
write pr: HX86471  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/TestEntityDependencyPopulationImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/importexport/TestEntityDependencyPopulationImpl.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestEventReasonCodeHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestEventReasonCodeHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestDateTimeIntervalConstantHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestDateTimeIntervalConstantHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCustomerHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCustomerHelper.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HX66660  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HX66660', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '5/10/19 14:08', ';', 'I7a84aa034f19af64f59e6ac4d77bce7991d1c756')
write pr: BSUC:FT12-1  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java
data: ('BSUC:FT12-1', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestProductOfferingPriceSpecificationConverterImpl.java', ';', '6/18/19 19:03', ';', 'Ia036b50d8ab6c17d0711691717022535bb71c8a6')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/16/20 15:51', ';', 'Ie1d5b270409da044ec54f2286e9fb3087d1e0272')
write pr: HX85578  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scheduledefinition/TestUsedBy.java
data: ('HX85578', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scheduledefinition/TestUsedBy.java', ';', '9/3/19 11:09', ';', 'Id3d14e020239d809698ef7c966de359a6fc8b9b1')
write pr: HY77118  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestRankingEntryListMerger.java
data: ('HY77118', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestRankingEntryListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY69638  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestReasonCodeForResumptionHook.java
data: ('HY69638', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestReasonCodeForResumptionHook.java', ';', '10/28/20 7:38', ';', 'I8458a5d8fe6c503df7a962832124a8511f1a96d1')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '7/3/20 17:22', ';', 'I04c3cbb7b1907e97150470c4ca5c43f479ebf22c')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredBucketBalanceHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredBucketBalanceHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY62003  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestSharingResourceProviderHelper.java
data: ('HY62003', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestSharingResourceProviderHelper.java', ';', '9/15/20 8:20', ';', 'Ia641f0b73d4d46ff35006b718770134e3c4ce2d5')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredBucketBalanceHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/ProductOfferingPageService.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/ProductOfferingPageService.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY52064  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java
data: ('HY52064', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HX77477  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalance.java
data: ('HX77477', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalance.java', ';', '7/9/19 11:01', ';', 'Ia4274b0770ee49bbe0a2e843e8c33b5128b8a0db')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/CommunityMembershipHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/CommunityMembershipHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicMandatoryFieldValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicMandatoryFieldValidationRule.java', ';', '7/28/20 7:49', ';', 'I2768f8666a00ff719489ece7b49dc749d3d0c203')
write pr: HY59800  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationPageToEntityMapper.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationPageToEntityMapper.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HX96185  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/TestRestListEntityImpl.java
data: ('HX96185', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/TestRestListEntityImpl.java', ';', '10/23/19 14:03', ';', 'I761864b6b250e74e4536fa26f72b670e371bd2b6')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverter.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PublicQueryFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PublicQueryFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HX99743  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestCreatePageTransactionImpl.java
data: ('HX99743', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestCreatePageTransactionImpl.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HX87622  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/BucketPriorityListToPageConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/BucketPriorityListToPageConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestAbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestAbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY16864  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HY16864', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '12/9/19 10:24', ';', 'I689ddb4e648e4443f7d7ce80d4006e33cad787a0')
write pr: HY27847  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/permissionstrategy/TestPermissionStrategyPage_ITCase.java
data: ('HY27847', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/permissionstrategy/TestPermissionStrategyPage_ITCase.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY65889  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY65889', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '10/22/20 14:16', ';', 'I4cf4061ac1afe3996cc9d47c2e71cf1d3f6b6500')
write pr: HX80786  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestAbstractRestEntity.java
data: ('HX80786', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestAbstractRestEntity.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY32754  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Refill.java
data: ('HY32754', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Refill.java', ';', '3/24/20 10:30', ';', 'Id76bbb9b177d4716186ddda04da9dec27f9623f9')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleTriggerConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleTriggerConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY45357  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY45357', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '6/10/20 13:53', ';', 'Ib725b51712dd5e27858e80249085b7c6f7878e6b')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TestChaCollectionContainsConditionHookWithCssParameter.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TestChaCollectionContainsConditionHookWithCssParameter.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/ContractSpecificationNotificationsValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/ContractSpecificationNotificationsValidationRule.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HX97812  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/TestConditionTemplate_ITCase.java
data: ('HX97812', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/TestConditionTemplate_ITCase.java', ';', '10/25/19 12:05', ';', 'I040e76d2d2d379d97b3749bdd03ae64e29167eb8')

write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestContractSpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/TestContractSpecificationConverter.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY28799  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/NetworkPolicyCounterRuleConverter.java
data: ('HY28799', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/NetworkPolicyCounterRuleConverter.java', ';', '2/26/20 10:45', ';', 'Id5a233c73716d6a04dff11d33750775630a02352')
write pr: HY27042  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestCircularRelationsOfEntitiesNotAllowedValidationRule.java
data: ('HY27042', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestCircularRelationsOfEntitiesNotAllowedValidationRule.java', ';', '3/3/20 6:39', ';', 'I3ac1ef560e8cf71d8822eaa9b5042e5b1c8115b1')
write pr: HY15484  java: integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/sr/ServiceRegistryStub.java
data: ('HY15484', ';', 'integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/sr/ServiceRegistryStub.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY53290  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/PriorityListVersionUpdaterFactory.java
data: ('HY53290', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/PriorityListVersionUpdaterFactory.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY76253  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CharacteristicSetSpecificationConverter.java
data: ('HY76253', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CharacteristicSetSpecificationConverter.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/DateTimeIntervalHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/DateTimeIntervalHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY48964  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredAvailableUnitsHook.java
data: ('HY48964', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredAvailableUnitsHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY53290  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/RmcaScheduledExecutorServiceImpl.java
data: ('HY53290', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/RmcaScheduledExecutorServiceImpl.java', ';', '8/11/20 8:18', ';', 'I9ed5e3c13d4f10b31cd42da0db5e4fb4cb7001ed')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueLink.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueLink.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicMandatoryFieldValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicMandatoryFieldValidationRule.java', ';', '7/28/20 7:49', ';', 'I2768f8666a00ff719489ece7b49dc749d3d0c203')
write pr: HY27847  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/PermissionStrategyRuleConverter.java
data: ('HY27847', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/PermissionStrategyRuleConverter.java', ';', '2/20/20 10:13', ';', 'Ie7ab2387e47838726c0cf943e57b065fb1ea74b1')
write pr: HY50582  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY50582', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '7/8/20 6:37', ';', 'I9c1fa14935e1d01bb32cda5ba5e060ab6c9a8ca2')
write pr: HY18902  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/UpstreamDependencyAnalyzer.java
data: ('HY18902', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/UpstreamDependencyAnalyzer.java', ';', '1/15/20 7:39', ';', 'I111a811fdc00f0324f117efb979970a197ae94aa')
write pr: HY45345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java
data: ('HY45345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java', ';', '6/8/20 18:37', ';', 'I72a456d8fcc8988321bf6985d3b99cc4d619f749')
write pr: HY24973  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java
data: ('HY24973', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java', ';', '2/6/20 16:02', ';', 'Iad2395e564b7a2850a2c55ee426131ae7b16f627')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestBaseErrorResponse.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestBaseErrorResponse.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY53290  java: integrationtest/readdvtestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/readdvtestcases/AbstractRoTest.java
data: ('HY53290', ';', 'integrationtest/readdvtestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/readdvtestcases/AbstractRoTest.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY62458  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicValuesRegistry.java
data: ('HY62458', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicValuesRegistry.java', ';', '9/22/20 10:41', ';', 'If9dd66370e0eaae973e30d1aefcc49177159b0a6')
write pr: HY64562  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/RulePackagesRegistryImpl.java
data: ('HY64562', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/RulePackagesRegistryImpl.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: HY46854  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/refillrule/RefillRuleConverter.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/refillrule/RefillRuleConverter.java', ';', '6/12/20 7:05', ';', 'Ib07629ca5bce3766699bdaebb302aa2192492faf')
write pr: HY24061  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecification.java
data: ('HY24061', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecification.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY39569  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityRead_ITCase.java
data: ('HY39569', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityRead_ITCase.java', ';', '4/28/20 7:22', ';', 'I380dbd5a7bb147bf035a66ad24d3e4f135dee342')
write pr: HX86828  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNesConsumableUnitsValidationRule.java
data: ('HX86828', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNesConsumableUnitsValidationRule.java', ';', '9/2/19 11:52', ';', 'I33357fbe9fad2076f17854bd9ad16db1bbceeccf')
write pr: HX88018  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HX88018', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HY68338  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java
data: ('HY68338', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/networkpolicycounter/CompositeStatusConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/networkpolicycounter/CompositeStatusConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY24973  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/RelativeSharingLimitFilter.java
data: ('HY24973', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/RelativeSharingLimitFilter.java', ';', '2/5/20 13:15', ';', 'Ied8cca294197f65fdec96d1b2200ef62b5aa0a38')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/networkpolicycounter/TestNetworkPolicyCounterStatusHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/networkpolicycounter/TestNetworkPolicyCounterStatusHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY39316  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntitySchemaFactory.java
data: ('HY39316', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntitySchemaFactory.java', ';', '4/30/20 12:16', ';', 'Ia281a738a056930d1ff0925c90a9c7990a5a506f')
write pr: HY17547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/TestScenarioTriggeredRmcaEntityToCompiledRuleConverter.java
data: ('HY17547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/scenariotriggered/TestScenarioTriggeredRmcaEntityToCompiledRuleConverter.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/ProductPriorityListGeneratorEventConsumer.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/ProductPriorityListGeneratorEventConsumer.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HX93518  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/resourcefacingservicespecification/ResourceFacingServiceSpecificationListPageConverter.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/resourcefacingservicespecification/ResourceFacingServiceSpecificationListPageConverter.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')
write pr: HY15429  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY15429', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/BucketPriorityListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/BucketPriorityListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY69751  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/TestScheduleDefinitionPageConverter.java
data: ('HY69751', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/TestScheduleDefinitionPageConverter.java', ';', '10/30/20 15:47', ';', 'If2bb29b073b4090995afd493fd5dd11db3b5b956')
write pr: HX92890  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java
data: ('HX92890', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java', ';', '10/2/19 8:29', ';', 'Ifbe6f226b580f342b41ad08cd24375d0132e1814')
write pr: HY46749  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/Provision.java
data: ('HY46749', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/Provision.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY60708  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY60708', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY76253  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/css/TestCharacteristicSetSpecificationConverter.java
data: ('HY76253', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/css/TestCharacteristicSetSpecificationConverter.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY59766  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ContractSpecificationValidationRuleProvider.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ContractSpecificationValidationRuleProvider.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY53290  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestBucketPriorityListUpdater.java
data: ('HY53290', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestBucketPriorityListUpdater.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PvsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PvsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java', ';', '8/14/20 10:19', ';', 'Ib599f2a6f7be69d97266c7279f4e327aa110774a')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/EntityImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/EntityImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY23963  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java

write pr: HY46412  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/TestCDRProcessingInformationConverter.java
data: ('HY46412', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/TestCDRProcessingInformationConverter.java', ';', '6/8/20 12:02', ';', 'Ib7b7445e62b9536b26ce3f1e9ab35da40126d07e')
write pr: HX94284  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/characteristicsetspecification/TestCharacteristicSetSpecificationPageConverter.java
data: ('HX94284', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/characteristicsetspecification/TestCharacteristicSetSpecificationPageConverter.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HY42777  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java
data: ('HY42777', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestSetResponseParameterHook.java', ';', '5/29/20 6:07', ';', 'Ie9ad14d2533e0d7a6c9cad84f2928d596556ec55')
write pr: HY65926  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setthresholdscenario/TestSetThresholdScenarioConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setthresholdscenario/TestSetThresholdScenarioConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationPageToEntityMapper.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationPageToEntityMapper.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY77550  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java
data: ('HY77550', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/ExternalVersionImporter.java', ';', '12/14/20 8:18', ';', 'I0568204b711bc2a58e1a979f5160e78de177bb54')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/networkauthorization/NetworkAuthorizationConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/networkauthorization/NetworkAuthorizationConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY76370  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestListProductPriorityListConverterImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestListProductPriorityListConverterImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY77118  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HY77118', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HX65525  java: restproxy/src/main/java/com/ericsson/bss/rmca/restproxy/internal/ProxyBase.java
data: ('HX65525', ';', 'restproxy/src/main/java/com/ericsson/bss/rmca/restproxy/internal/ProxyBase.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueCharacteristicValueMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueCharacteristicValueMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY74660  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java
data: ('HY74660', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java', ';', '12/14/20 8:47', ';', 'I732b77617ceb37732af2ab0df12910c3cf479905')
write pr: HY53290  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java
data: ('HY53290', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java', ';', '8/14/20 10:19', ';', 'Ib599f2a6f7be69d97266c7279f4e327aa110774a')
write pr: HY42535  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/TestRefillRuleListEntry.java
data: ('HY42535', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/TestRefillRuleListEntry.java', ';', '5/25/20 7:11', ';', 'I0a261b3544a27b878a527f917baf90508e444eb6')
write pr: HY46587  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestBucketPriorityListImporter.java
data: ('HY46587', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestBucketPriorityListImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HY64618  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/permissionstrategy/PermissionStrategyPageToEntityMapper.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/permissionstrategy/PermissionStrategyPageToEntityMapper.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY24061  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/ProvisionConfigurationServiceImpl.java
data: ('HY24061', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/ProvisionConfigurationServiceImpl.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HX65525  java: jivetest/src/main/java/com/ericsson/bss/rmca/jive/testcases/TestBillingManagement.java
data: ('HX65525', ';', 'jivetest/src/main/java/com/ericsson/bss/rmca/jive/testcases/TestBillingManagement.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredBucketBalanceHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredBucketBalanceHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: BSUC:FT12-1  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/of/PopsContextTypeFilter.java
data: ('BSUC:FT12-1', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/of/PopsContextTypeFilter.java', ';', '6/18/19 16:04', ';', 'I8ebff3b442b44f65fd6334c270466eb6f78c4987')
write pr: HY66450  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java
data: ('HY66450', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/characteristicsetspecification/CssForEntityTypeValidationRule.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HX88018  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java
data: ('HX88018', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HY60437  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestPolicyEventUiEntityMapper.java
data: ('HY60437', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestPolicyEventUiEntityMapper.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HX98116  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/NetworkPolicyCounterRuleConverter.java
data: ('HX98116', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/NetworkPolicyCounterRuleConverter.java', ';', '10/29/19 15:16', ';', 'I0ee34afdc8d9fc1b3958d6df2b2c6b663d55d1b8')
write pr: HY52844  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY52844', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '7/16/20 14:16', ';', 'I266f0fd1a842bbc64d4b981a33605aa4a36f0b2b')
write pr: HX91715  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBucketTagSetProvider.java
data: ('HX91715', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBucketTagSetProvider.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY59766  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY59766', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/NotificationTemplate.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/NotificationTemplate.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HX66291  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ReferenceHelper.java
data: ('HX66291', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ReferenceHelper.java', ';', '5/9/19 11:36', ';', 'I6e9101173b69e4e6a91c58c807661880c70d2ac1')
write pr: HX77683  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productoffering/ProductOfferingPriceSignatureValidationRule.java
data: ('HX77683', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productoffering/ProductOfferingPriceSignatureValidationRule.java', ';', '7/10/19 7:04', ';', 'I0c260dfd1b04bc64882f07712adecf311d091547')
write pr: HY18902  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestUpstreamDependency_UseCase.java
data: ('HY18902', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestUpstreamDependency_UseCase.java', ';', '1/14/20 13:35', ';', 'I2b897fa224f045af30aa06cd201b2205e856ab7e')
write pr: HY30034  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/networkpolicycounterspecification/TestNetworkPolicyCounterRuleMustHaveValuesSet.java
data: ('HY30034', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/networkpolicycounterspecification/TestNetworkPolicyCounterRuleMustHaveValuesSet.java', ';', '3/4/20 15:39', ';', 'If68826aca30430f11d165eb631ae7a3503e1e762')
write pr: HY43069  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestNotificationTemplateViewImpl.java
data: ('HY43069', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/TestNotificationTemplateViewImpl.java', ';', '5/20/20 18:33', ';', 'I679551f00a74c7c9d676970107ef617630af0112')
write pr: HY64618  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestRestPageImpl.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestRestPageImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY60708  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/ScenarioWithAnnouncementsValidationRule.java
data: ('HY60708', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/ScenarioWithAnnouncementsValidationRule.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '8/3/20 9:36', ';', 'I8d1f7b2d9ee1f0042166af77f1e629a5998dd65f')
write pr: HY46412  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/ContractSpecificationMaxAgeValidationRule.java
data: ('HY46412', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/ContractSpecificationMaxAgeValidationRule.java', ';', '6/8/20 7:43', ';', 'Idec48c2047eba0cee6b3826b93d663681311c819')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java', ';', '10/28/20 10:31', ';', 'I79b2c226a35a412d5549569b83f9dc89379c6baa')
write pr: HY58180  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/MergableTargetEntriesIdentifier.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/MergableTargetEntriesIdentifier.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY64004  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/TestLifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '8/12/20 7:45', ';', 'I1f7e85efdce5868c4427e8697ae786c8ab48d073')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java
data: ('HY65732', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/RestImportImpl.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY76370  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestRestListProductPriorityListConverterImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestRestListProductPriorityListConverterImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY62744  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java
data: ('HY62744', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java', ';', '9/22/20 12:18', ';', 'Id4683d1052a07df9356af7a331089abe25e06324')
write pr: HY30915  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java
data: ('HY30915', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java', ';', '3/23/20 16:50', ';', 'If62d9ed0f8048f2909ae3419c26a54335685f422')

write pr: HX92890  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java
data: ('HX92890', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java', ';', '10/2/19 8:29', ';', 'Ifbe6f226b580f342b41ad08cd24375d0132e1814')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestPopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY46749  java: jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ApplicationScannerImpl.java
data: ('HY46749', ';', 'jaxrspublisher/src/main/java/com/ericsson/bss/rmca/jaxrspublisher/internal/ApplicationScannerImpl.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY46854  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HY46854', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY65634  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java
data: ('HY65634', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java', ';', '10/6/20 7:16', ';', 'Ic57dd52cdd66db0adeee0237f525b5a5620fc058')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY60256  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java
data: ('HY60256', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java', ';', '9/2/20 6:41', ';', 'Ie8e407477721eddb52665e680fae135d1a3f9003')
write pr: HY15429  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY15429', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HX86471  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '9/2/19 12:30', ';', 'Ie1f272531a90eb5d9df20f0a5a3506da059e9c57')
write pr: HY35886  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestAtLeastOnePricePerServiceValidationRule.java
data: ('HY35886', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/price/TestAtLeastOnePricePerServiceValidationRule.java', ';', '4/17/20 12:39', ';', 'Ia22c3acc0589eb8a89ffe192969b4e7a6cca9ca8')
write pr: HY69943  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestBucketPriorityListFiltererFactory.java
data: ('HY69943', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestBucketPriorityListFiltererFactory.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY64938  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/PbsThresholdOffsetUniqueExternalIdValidationRule.java
data: ('HY64938', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/PbsThresholdOffsetUniqueExternalIdValidationRule.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HY24489  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY24489', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '2/10/20 14:45', ';', 'I2f577f46a989aa609d41fa72582538e92c682382')
write pr: HX71438  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestProductOfferingPriceSpecificationConverterImpl.java
data: ('HX71438', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/TestProductOfferingPriceSpecificationConverterImpl.java', ';', '6/18/19 11:59', ';', 'I81a8e2216ae65889509a246ed464bff4c8f0f6a2')
write pr: HY66914  java: importexport/api/src/test/java/com/ericsson/bss/rmca/importexport/api/TestExportData.java
data: ('HY66914', ';', 'importexport/api/src/test/java/com/ericsson/bss/rmca/importexport/api/TestExportData.java', ';', '10/19/20 8:55', ';', 'I99dcf6cc5963bfb0b5973a5ca0c99982c94845ac')
write pr: HY38940  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY38940', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY35764  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/PromotionRmcaEntityToCompiledRuleConverter.java
data: ('HY35764', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/PromotionRmcaEntityToCompiledRuleConverter.java', ';', '4/6/20 11:08', ';', 'Ibbd864214ae606b29e19ebeed2dbf0a6122c81b6')
write pr: HX69071  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingspecification/TestSharingSpecificationPage.java
data: ('HX69071', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingspecification/TestSharingSpecificationPage.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: HY46412  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationMaxAgeValidationRule.java
data: ('HY46412', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationMaxAgeValidationRule.java', ';', '6/8/20 7:43', ';', 'Idec48c2047eba0cee6b3826b93d663681311c819')
write pr: HY69751  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/ScheduleDefinitionPageConverter.java
data: ('HY69751', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/ScheduleDefinitionPageConverter.java', ';', '10/30/20 15:47', ';', 'If2bb29b073b4090995afd493fd5dd11db3b5b956')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestEventReasonCode.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestEventReasonCode.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PolicyValueSpecificationConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PolicyValueSpecificationConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/ProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/ProductOfferingPriceCompareValueCharacteristicMustMatchCssCharacteristicValidationRule.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmDataMigrationViewImpl.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCreateTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestCreateTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY24150  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationDetails.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationDetails.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY58180  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HY65966  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/SharingResourceProviderHelper.java
data: ('HY65966', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/SharingResourceProviderHelper.java', ';', '10/5/20 12:59', ';', 'I0840216dcb9c8cc31656a0d0bed58e807bbd65e7')
write pr: HY64938  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/TestThresholdOffsetUniqueExternalIdValidationRule.java
data: ('HY64938', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/resourcespecification/TestThresholdOffsetUniqueExternalIdValidationRule.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HX66291  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productoffering/ProductOfferingBillCycleAlignedAllowedOnlyForPostpaidValidationRule.java
data: ('HX66291', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productoffering/ProductOfferingBillCycleAlignedAllowedOnlyForPostpaidValidationRule.java', ';', '5/9/19 11:36', ';', 'I6e9101173b69e4e6a91c58c807661880c70d2ac1')
write pr: HX69071  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java
data: ('HX69071', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/TestRulesCrudServiceImpl.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: HY21740  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/ProductStateAlreadySuspendedOrInactivatedHook.java
data: ('HY21740', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/ProductStateAlreadySuspendedOrInactivatedHook.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/ProductPriorityListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/ProductPriorityListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeleteTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeleteTransactionImpl.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java', ';', '8/7/20 14:42', ';', 'I96e419f81057c634b53e3ecfd29d6c3f2cb15d33')
write pr: HY53290  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java
data: ('HY53290', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY19427  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java
data: ('HY19427', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java', ';', '1/7/20 11:25', ';', 'I1cd288d4b101c02f8f77529f8e300a944db77206')
write pr: HX99482  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java
data: ('HX99482', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java', ';', '11/1/19 15:14', ';', 'I4b5b674e92043f3d7602e7355fd694e054577335')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleTriggerActionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleTriggerActionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '8/14/20 10:19', ';', 'Ib599f2a6f7be69d97266c7279f4e327aa110774a')
write pr: HY60256  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HY60256', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '9/2/20 6:41', ';', 'Ie8e407477721eddb52665e680fae135d1a3f9003')
write pr: HY15429  java: restsimbundle/src/main/java/com/ericsson/bss/rmca/restsimbundle/cs/CsToNesMaps.java
data: ('HY15429', ';', 'restsimbundle/src/main/java/com/ericsson/bss/rmca/restsimbundle/cs/CsToNesMaps.java', ';', '12/9/19 11:42', ';', 'I3e71c65f17e909cc81f9b3591c30daca21572b03')
write pr: HY76370  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestListProductPriorityListConverterImpl.java
data: ('HY76370', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/converter/RestListProductPriorityListConverterImpl.java', ';', '12/7/20 11:24', ';', 'Ic37b5c999da7c851e7b0a575b958820c6ebba582')
write pr: HY17547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/converters/TestAbstractCompiledRuleToRmcaEntityConverter.java
data: ('HY17547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/converters/TestAbstractCompiledRuleToRmcaEntityConverter.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HY61542  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java
data: ('HY61542', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java', ';', '9/9/20 6:50', ';', 'If243c7a3661fdacf82b9d32fbd4eb766fb49369d')
write pr: HY47676  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNotificationOffsetCharacteristicValueValidationRule.java
data: ('HY47676', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNotificationOffsetCharacteristicValueValidationRule.java', ';', '6/19/20 18:35', ';', 'I0ce4c0ee035aa3c7f6d642ff7180c855de4aa0a6')
write pr: HY45351  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/GenericUtils.java
data: ('HY45351', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/GenericUtils.java', ';', '6/5/20 11:19', ';', 'I8c183012f24dc62d6417601ad3b5c3978731c6fc')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRateHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TestRateHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX86471  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskFactoryImpl.java
data: ('HX86471', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskFactoryImpl.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY65732  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestExportImportErrorResponse.java

data: ('HY46865', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/AnnouncementPhrase.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY22981  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateNewBucketPriorityListVersionTask.java
data: ('HY22981', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateNewBucketPriorityListVersionTask.java', ';', '1/22/20 13:10', ';', 'I834e6b0a751abebf3498d239920720a4e91b3ba2')
write pr: HX65525  java: restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/AbstractTestProxyBase.java
data: ('HX65525', ';', 'restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/AbstractTestProxyBase.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY15484  java: oamservices/srimpl/src/main/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/ServiceRegistryConsumerServiceImpl.java
data: ('HY15484', ';', 'oamservices/srimpl/src/main/java/com/ericsson/bss/rmca/oamservices/srimpl/internal/ServiceRegistryConsumerServiceImpl.java', ';', '11/28/19 14:31', ';', 'If5bbef257c084cf55fcee3f1b70e5b28bb98859d')
write pr: HY58386  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetConverterImpl.java
data: ('HY58386', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/PresetConverterImpl.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFilterer.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFilterer.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY76253  java: integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java
data: ('HY76253', ';', 'integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY21740  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ProductOfferingPriceSpecificationHelper.java
data: ('HY21740', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ProductOfferingPriceSpecificationHelper.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmDataMigrationViewImpl.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY46854  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/TestScenarioTriggeredActionListProvider.java
data: ('HY46854', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/TestScenarioTriggeredActionListProvider.java', ';', '6/10/20 15:22', ';', 'I855ee686049bc531de418edbcd88dd896c6b02d5')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HX80786  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java
data: ('HX80786', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY58386  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/AbstractTestNormalizedAndCssParameter.java
data: ('HY58386', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/AbstractTestNormalizedAndCssParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY46865  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestAnnouncementPhrase.java
data: ('HY46865', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestAnnouncementPhrase.java', ';', '6/15/20 15:52', ';', 'I6329c2dc2b9e889676e3d8c1bada3eedb56c932f')
write pr: HY24150  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/TestCustomerSpecificationPageConverter.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HX90022  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/ExportData.java
data: ('HX90022', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/ExportData.java', ';', '9/17/19 6:30', ';', 'I6138e011180e274c97194f1d40d477f9f4b73a5f')
write pr: HY42110  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java
data: ('HY42110', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/WithFilterFactory.java', ';', '5/13/20 10:51', ';', 'I07db9d0d709036e8e1f18f534482b09e5334ed87')
write pr: HY77118  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/RecurrencePriorityListMerger.java
data: ('HY77118', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/RecurrencePriorityListMerger.java', ';', '12/11/20 12:16', ';', 'I70accccd34c64f56ad18b8c5844c21043b6c6575')
write pr: HY53290  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestBucketPriorityListImporter.java
data: ('HY53290', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestBucketPriorityListImporter.java', ';', '8/13/20 5:49', ';', 'Ie9ed89f74e885cee6adae9c4c834d77e03934382')
write pr: HX65525  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java
data: ('HX65525', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY48964  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TieredValuesConverter.java
data: ('HY48964', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TieredValuesConverter.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY19473  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceConverter.java
data: ('HY19473', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceConverter.java', ';', '12/20/19 13:32', ';', 'Id427faf9ca2c1075a078de981e71c884657e94d7')
write pr: HX90744  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSValidatorFactory.java
data: ('HX90744', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/TestXSSValidatorFactory.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY40467  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestMoveRecurrenceWithAllowanceHook.java
data: ('HY40467', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestMoveRecurrenceWithAllowanceHook.java', ';', '5/6/20 7:36', ';', 'Ibc8481b4c2fbcafea55bb98d63997221ad9c40e0')
write pr: HX87622  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/BucketPriorityListToPageConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/BucketPriorityListToPageConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HX86828  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX86828', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/2/19 11:52', ';', 'I33357fbe9fad2076f17854bd9ad16db1bbceeccf')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleaner.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/PriorityListCleaner.java', ';', '8/12/20 7:45', ';', 'I1f7e85efdce5868c4427e8697ae786c8ab48d073')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/refillrule/RefillRuleConverter.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/refillrule/RefillRuleConverter.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY53290  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/recurrenceprioritylist/TestRecurrencePriorityListPage_ITCase.java
data: ('HY53290', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/recurrenceprioritylist/TestRecurrencePriorityListPage_ITCase.java', ';', '7/17/20 6:33', ';', 'I139d281c30cd4f4b3a7f6b59b1207ec62962c014')
write pr: HX66324  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/BucketAddRecurrenceHook.java
data: ('HX66324', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/BucketAddRecurrenceHook.java', ';', '5/16/19 20:20', ';', 'Ie3ad0574aed45eae4316e0bc9a1e217254caaf67')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/PriorityListMigrationHelper.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/PriorityListMigrationHelper.java', ';', '7/28/20 11:41', ';', 'I68f544fdbeb48f50c4f4587e45f8c38710e937ae')
write pr: HX84971  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HX84971', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '8/22/19 9:07', ';', 'I6efb7268fe9aa1f637feccb2cab3a22fae4a87b3')
write pr: HY64938  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ResourceSpecificationValidationRuleProvider.java
data: ('HY64938', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ResourceSpecificationValidationRuleProvider.java', ';', '9/29/20 14:35', ';', 'I4b98cb72b37299e6fabaf72bf2d9dd76b2cc0abb')
write pr: HY55461  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java
data: ('HY55461', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementConverter.java', ';', '8/5/20 16:52', ';', 'I6fa074f931bbd292ab831b1066d789f5748042c5')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/AbstractChaConditionHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/AbstractChaConditionHook.java', ';', '10/28/20 10:31', ';', 'I79b2c226a35a412d5549569b83f9dc89379c6baa')
write pr: HY58815  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestRankingEntryListReverser.java
data: ('HY58815', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/core/TestRankingEntryListReverser.java', ';', '8/24/20 6:59', ';', 'I75afbdde68c1b7e984baabb3b79893028cfd4e3f')
write pr: HY64004  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java
data: ('HY64004', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/lifecyclestatechange/LifecycleStateChangeActionTemplateCompiler.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/BucketTagReferenceCharacteristicsDataMigration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/BucketTagReferenceCharacteristicsDataMigration.java', ';', '7/3/20 17:22', ';', 'I04c3cbb7b1907e97150470c4ca5c43f479ebf22c')
write pr: HY38940  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY38940', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY76253  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CharacteristicSetSpecificationConverter.java
data: ('HY76253', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CharacteristicSetSpecificationConverter.java', ';', '12/7/20 10:25', ';', 'I84d5d8163085a5c99a4d5f135a82f9b76470dfe9')
write pr: HY53290  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java
data: ('HY53290', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/ProductPriorityListFilterer.java', ';', '8/11/20 8:18', ';', 'I9ed5e3c13d4f10b31cd42da0db5e4fb4cb7001ed')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY58373  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/AbstractNormalizedAndCssParameter.java
data: ('HY58373', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/AbstractNormalizedAndCssParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HX84864  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierHelper.java
data: ('HX84864', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierHelper.java', ';', '8/22/19 18:50', ';', 'I9e6ccb0e9b79d5e24d4ba33b33e12c677472794d')
write pr: HY16864  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmBaseConfigContract.java
data: ('HY16864', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmBaseConfigContract.java', ';', '12/9/19 10:24', ';', 'I689ddb4e648e4443f7d7ce80d4006e33cad787a0')
write pr: HX65525  java: restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java
data: ('HX65525', ';', 'restproxy/src/test/java/com/ericsson/bss/rmca/restproxy/internal/TestNotificationTemplateViewImpl.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY35764  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/PromotionRmcaEntityToCompiledRuleConverter.java
data: ('HY35764', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/PromotionRmcaEntityToCompiledRuleConverter.java', ';', '4/6/20 11:08', ';', 'Ibbd864214ae606b29e19ebeed2dbf0a6122c81b6')
write pr: HY48964  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredAvailableUnitsHook.java
data: ('HY48964', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredAvailableUnitsHook.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HX88018  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java
data: ('HX88018', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java', ';', '9/4/19 12:50', ';', 'I008e261b264bb904a6ead1e731629877a35bb8a1')
write pr: HX90022  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/TestRmcaExport.java
data: ('HX90022', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/TestRmcaExport.java', ';', '9/16/19 11:49', ';', 'I6687915584c83b5d253d629b97bfbdf64121fb60')
write pr: HX99743  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestPublishPageTransactionImpl.java

write pr: BSUC:FT8-15  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java
data: ('BSUC:FT8-15', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestProductPriorityListFilterer.java', ';', '7/21/20 9:36', ';', 'I2e24c3a89e0945ebb31a235f7d7e8bbc39e23983')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketthreshold/BucketThresholdConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketthreshold/BucketThresholdConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX87622  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/buckettag/TestBucketTagListEntryConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/buckettag/TestBucketTagListEntryConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HX91715  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/VersionIdentifierMustBeNullOrEmptyOnCreateValidationRule.java
data: ('HX91715', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/VersionIdentifierMustBeNullOrEmptyOnCreateValidationRule.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY46749  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RmcaRestPublisher.java
data: ('HY46749', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RmcaRestPublisher.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HY30739  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY30739', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '3/10/20 8:55', ';', 'Ic262489ea61211040cebb42666f8d928ef3346cf')
write pr: HY19185  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java
data: ('HY19185', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java', ';', '12/18/19 14:30', ';', 'Ieaec00e40317e0d60c9660d586c34671066ad40b')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestTableContainsHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestTableContainsHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '7/28/20 13:10', ';', 'I4d41599ba9fe98cfd0e66f307918ca60c90ce420')
write pr: HY69943  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestPriorityListUpdateHelper.java
data: ('HY69943', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestPriorityListUpdateHelper.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BucketTagBucketPriorityListManagement.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BucketTagBucketPriorityListManagement.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestStateBeforeHaltHook.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestStateBeforeHaltHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY30915  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java
data: ('HY30915', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java', ';', '3/23/20 16:50', ';', 'If62d9ed0f8048f2909ae3419c26a54335685f422')
write pr: HY52064  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposerImpl.java
data: ('HY52064', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RuleContextComposerImpl.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY66573  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HY66573', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '11/12/20 6:38', ';', 'Ia6df1f4889a74a6d75f4a5acdd4c769149afb44c')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestParameterizedBucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestParameterizedBucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY21740  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/ProductStateAlreadySuspendedOrInactivated.java
data: ('HY21740', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/local/ProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HX85064  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ResourceSpecificationValidationRuleProvider.java
data: ('HX85064', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ResourceSpecificationValidationRuleProvider.java', ';', '8/21/19 12:32', ';', 'Ifa2ef7a6f4ee26477d1204f2323e150e83e32dbe')
write pr: HX94284  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/EntityCharacteristics.java
data: ('HX94284', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/EntityCharacteristics.java', ';', '10/8/19 13:17', ';', 'I576c4e498e7c9e01249bbc5721120c7c53bd4829')
write pr: HY21740  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/ProductStateAlreadySuspendedOrInactivated.java
data: ('HY21740', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/ProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HX72933  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/LogicAlgorithmSpecificationValidationRuleProvider.java
data: ('HX72933', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/LogicAlgorithmSpecificationValidationRuleProvider.java', ';', '7/19/19 10:47', ';', 'I0853ff1e6a8b107df7e5f7387ffef8bb74635fd1')
write pr: HY62217  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/BucketAddHook.java
data: ('HY62217', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/BucketAddHook.java', ';', '9/15/20 12:51', ';', 'I2c69ecc4fb046a7729e9110c78f8cfdf64353995')
write pr: HY58386  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestCharacteristicParameter.java
data: ('HY58386', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestCharacteristicParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY68338  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java
data: ('HY68338', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestStrategyUiEntityMapper.java', ';', '10/21/20 7:10', ';', 'I22a000d58981222c0bbf45a5fd7a002575f4a81f')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/filtering/FilteringConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/filtering/FilteringConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleStateChangeActionConverter.java
data: ('HY56644', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleStateTransitionRuleStateChangeActionConverter.java', ';', '8/10/20 13:55', ';', 'I245043401884717ff9cb9fe090faa50ba611b25b')
write pr: HY64004  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionTypeUtils.java
data: ('HY64004', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionTypeUtils.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY24061  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java
data: ('HY24061', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/AbstractTestNormalizedAndCssParameter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/AbstractTestNormalizedAndCssParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY42777  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/CompiledActionFacade.java
data: ('HY42777', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/CompiledActionFacade.java', ';', '5/29/20 6:07', ';', 'Ie9ad14d2533e0d7a6c9cad84f2928d596556ec55')
write pr: HY46412  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationMaxAgeValidationRule.java
data: ('HY46412', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/contractspecification/TestContractSpecificationMaxAgeValidationRule.java', ';', '6/8/20 12:02', ';', 'Ib7b7445e62b9536b26ce3f1e9ab35da40126d07e')
write pr: HX99012  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/CobaEntityImpl.java
data: ('HX99012', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/coba/CobaEntityImpl.java', ';', '10/30/19 11:51', ';', 'I86b611a35e28424205ccfb454478d3ca41da3c72')
write pr: HX86471  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java
data: ('HX86471', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestExportImport_ITCase.java', ';', '8/30/19 8:31', ';', 'If7c2e8a5990f19c49b3dc4a504e534f0aa621cd9')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HX94783  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterProvider.java
data: ('HX94783', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterProvider.java', ';', '10/14/19 12:03', ';', 'I92fd51831fb1b11f284e1ab8ece3d63978b9b66d')
write pr: HY65633  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/serviceusage/ServiceUsagePopsPageConverter.java
data: ('HY65633', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/serviceusage/ServiceUsagePopsPageConverter.java', ';', '10/1/20 7:37', ';', 'I78425ea1827d3d86aaa29736f6e8f33627ae4fef')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkPolicyGroupPriorityListDataMigration.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkPolicyGroupPriorityListDataMigration.java', ';', '7/28/20 11:41', ';', 'I68f544fdbeb48f50c4f4587e45f8c38710e937ae')
write pr: HY52518  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java
data: ('HY52518', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java', ';', '7/10/20 11:55', ';', 'I94b13e16ba04158770a2a5d5d79f2177cd738db8')
write pr: HY17608  java: oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/internal/TestAlarmHolder.java
data: ('HY17608', ';', 'oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/internal/TestAlarmHolder.java', ';', '12/11/19 11:16', ';', 'I81823a0a5a65ea1a2b66caa543737e2b0cdc2abe')
write pr: HY39569  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java
data: ('HY39569', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java', ';', '4/28/20 7:22', ';', 'I380dbd5a7bb147bf035a66ad24d3e4f135dee342')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationUtilityImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationUtilityImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: BSUC:FT8-15:4  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java
data: ('BSUC:FT8-15:4', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java', ';', '7/16/20 17:15', ';', 'I643b04f4a9bfa99cf128541c4b348875c3c5a4e5')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationTemplate.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/SendEndUserNotificationTemplate.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY69268  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HY69268', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '10/29/20 17:47', ';', 'I63bf642953556e104791c1828282d8f36d49d049')
write pr: HY71789  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java
data: ('HY71789', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/pop/ResumeBucketActionBucketUsageValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HY39014  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/agreementspecification/TestAgreementSpecificationListEntry.java
data: ('HY39014', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/agreementspecification/TestAgreementSpecificationListEntry.java', ';', '5/29/20 13:09', ';', 'Idabd0326b92081edbc1a15c35c8f442df6c2e1c5')
write pr: HX84594  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/StatisticsViewImpl.java

data: ('HY53290', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestGlobalPriorityListImporter.java', ';', '7/17/20 6:33', ';', 'I139d281c30cd4f4b3a7f6b59b1207ec62962c014')
write pr: HX69071  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingusagestrategy/SharingUsageStrategyPage.java
data: ('HX69071', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/sharingusagestrategy/SharingUsageStrategyPage.java', ';', '5/23/19 6:51', ';', 'Ibd80b1466ccfac26a975030013c3f5f29fc90ec8')
write pr: HY53290  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY53290', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicMandatoryFieldValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicMandatoryFieldValidationRule.java', ';', '7/28/20 7:49', ';', 'I2768f8666a00ff719489ece7b49dc749d3d0c203')
write pr: HX93518  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationDetails.java
data: ('HX93518', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/resourcefacingservicespecification/TestResourceFacingServiceSpecificationDetails.java', ';', '10/8/19 8:16', ';', 'If4a1c767723961022371b2419b7aa10d53a39844')
write pr: HY66450  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestCharacteristicParameter.java
data: ('HY66450', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestCharacteristicParameter.java', ';', '10/19/20 7:26', ';', 'I6a98e2ea8ca17068e16db75a3c35e38e2fb3a3b5')
write pr: HY66289  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/TestPermissionStrategyRuleConverter.java
data: ('HY66289', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/permissionstrategy/TestPermissionStrategyRuleConverter.java', ';', '10/9/20 12:02', ';', 'Iafc612201ba729674eb35808da39adb045bdc866')
write pr: HY24150  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HY53290  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/buckettag/TestBucketTagPrioList_ITCase.java
data: ('HY53290', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/buckettag/TestBucketTagPrioList_ITCase.java', ';', '8/13/20 14:20', ';', 'I3cd4181a7191c00ece7458371867bfdeebf8b4d8')
write pr: HY24150  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java
data: ('HY24150', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerspecification/CustomerSpecificationPageConverter.java', ';', '2/4/20 14:08', ';', 'I0a712cfa4ce0300ddc72ed7513f19dd5bd31719f')
write pr: HX80786  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java
data: ('HX80786', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestCertificateValidator.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY64562  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/validation/TestRuleValidationEngineImpl.java
data: ('HY64562', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/validation/TestRuleValidationEngineImpl.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/ConverterHelper.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationUtilityImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationUtilityImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java', ';', '10/28/20 10:31', ';', 'I79b2c226a35a412d5549569b83f9dc89379c6baa')
write pr: HY52844  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java
data: ('HY52844', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/bas/TestBillingAccountSpecificationPage_ITCase.java', ';', '7/16/20 14:16', ';', 'I266f0fd1a842bbc64d4b981a33605aa4a36f0b2b')
write pr: HY31764  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/RestProductOfferingPageImpl.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HY53290  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java
data: ('HY53290', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java', ';', '8/11/20 14:30', ';', 'I98f969c29c1d489799339abda80f0e9333a29c0a')
write pr: HX84594  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedTagSpecificationProvider.java
data: ('HX84594', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedTagSpecificationProvider.java', ';', '9/6/19 13:45', ';', 'I12b28e8f3dcffedd165fed986a143b76cfd803e1')
write pr: HY51063  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverter.java
data: ('HY51063', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/EntitySpecificationConverter.java', ';', '7/6/20 13:36', ';', 'Ib83e71495b5237a21f981fa9dff475fe742c5ca7')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestBillingManagementApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/AnyValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY66304  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TestChaCompareDataConditionHookWithCssParameter.java
data: ('HY66304', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/nesandcssnocharacteristics/TestChaCompareDataConditionHookWithCssParameter.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY69943  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFiltererFactory.java
data: ('HY69943', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/BucketPriorityListFiltererFactory.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HY60708  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/VreHelper.java
data: ('HY60708', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/VreHelper.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY46647  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRuleCompiler.java
data: ('HY46647', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/promotion/TestPromotionRuleCompiler.java', ';', '6/16/20 17:36', ';', 'Id7123b034221d063105caab7716af4c38d524c90')
write pr: HY71789  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java
data: ('HY71789', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/pop/TestResumeBucketActionBucketTypeValidationRule.java', ';', '11/12/20 10:09', ';', 'Ia83b5622b388c50f6736324cfe2718cd7dfa2707')
write pr: HX72933  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/LogicAlgorithmSpecificationValidationRuleProvider.java
data: ('HX72933', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/LogicAlgorithmSpecificationValidationRuleProvider.java', ';', '7/19/19 10:47', ';', 'I0853ff1e6a8b107df7e5f7387ffef8bb74635fd1')
write pr: HX98676  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterHelper.java
data: ('HX98676', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterHelper.java', ';', '10/30/19 8:43', ';', 'I91935eb3f45356a33db4f3b9e82ce5323c7fa6e7')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AbstractTieredBucketBalanceWithBurHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/AbstractTieredBucketBalanceWithBurHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY31764  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java
data: ('HY31764', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java', ';', '3/17/20 8:47', ';', 'Ib35213bfb25aacfe904cf205f07a7bc5ee3e3a3d')
write pr: HX65525  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/billingManagement/TestBillingManagement_ITCase.java
data: ('HX65525', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/billingManagement/TestBillingManagement_ITCase.java', ';', '5/10/19 6:44', ';', 'If3c09b7b273da54933fed45d05425f8b5df43a87')
write pr: HY48964  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HY48964', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '7/3/20 17:22', ';', 'I103115bc33c30c7f287b17603c5b19b9e601e24f')
write pr: HY10139  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/service/provider/TestCommonValidationRuleProvider.java
data: ('HY10139', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/service/provider/TestCommonValidationRuleProvider.java', ';', '11/12/19 8:43', ';', 'I9f376f4b2393501d670306d5ff94200969948d4d')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/RealignedTieredBucketBalanceWithBurHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/RealignedTieredBucketBalanceWithBurHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HX72276  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicPossibleValueModificationInVersionRule.java
data: ('HX72276', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicPossibleValueModificationInVersionRule.java', ';', '6/17/19 19:09', ';', 'I37a4da60a582bda294fa02a01ea6e2979ff93861')
write pr: HY65926  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setthresholdscenario/TestSetThresholdScenarioConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setthresholdscenario/TestSetThresholdScenarioConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HY46587  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/NetworkPolicyCounterStatusValueSpecificationImporter.java
data: ('HY46587', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/NetworkPolicyCounterStatusValueSpecificationImporter.java', ';', '6/5/20 8:55', ';', 'Ica9470010bf766cf6ff3ef9227518ec30237f57c')
write pr: HX86828  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/NesConsumableUnitsValidationRule.java
data: ('HX86828', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/NesConsumableUnitsValidationRule.java', ';', '9/2/19 11:52', ';', 'I33357fbe9fad2076f17854bd9ad16db1bbceeccf')
write pr: HY53290  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY53290', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '7/29/20 14:03', ';', 'I6ced8004f0e0214d6f3f0f3ffd915b50b41390e1')
write pr: HX70206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/BaseEntityDependencyPopulationImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/BaseEntityDependencyPopulationImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY51063  java: predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java
data: ('HY51063', ';', 'predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HX84747  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java
data: ('HX84747', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicygroup/CounterConverter.java', ';', '8/16/19 12:19', ';', 'Ie6231c7d229ed44f90cb216e8201870d604e2422')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY37445  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/NotificationTemplateProvider.java
data: ('HY37445', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendendusernotification/NotificationTemplateProvider.java', ';', '4/23/20 9:17', ';', 'I078f41189b574e81f48af4f8db7b5d0ad01567db')
write pr: HX98116  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java
data: ('HX98116', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/networkpolicycounter/TestNetworkPolicyCounterRuleConverter.java', ';', '10/29/19 15:16', ';', 'I0ee34afdc8d9fc1b3958d6df2b2c6b663d55d1b8')
write pr: HX81198  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/list/filter/TestWithPaymentContextFilter.java
data: ('HX81198', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/list/filter/TestWithPaymentContextFilter.java', ';', '7/26/19 13:19', ';', 'Ie0b0f84380af9a85544fbee9b29dde5951073f43')
write pr: HX80786  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/TestRequestCertificateValidator.java

write pr: HY58180  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java
data: ('HY58180', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java', ';', '8/31/20 7:59', ';', 'I07e583c68d61b0fa7947a19e9ecd7398cc67a308')
write pr: HX80786  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestManager.java
data: ('HX80786', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestManager.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY62744  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java
data: ('HY62744', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestCharacteristicsInfoHelper.java', ';', '9/22/20 12:18', ';', 'Id4683d1052a07df9356af7a331089abe25e06324')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/FailureCounterHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/FailureCounterHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY51063  java: predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java
data: ('HY51063', ';', 'predefinedconfiguration/src/main/java/com/ericsson/bss/rmca/predefinedconfiguration/configuration/baseconfiguration/ContractSpecificationTemplate.java', ';', '7/28/20 8:54', ';', 'Ide2f03fa1098c6c4c7333123d6c1984899b7605a')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketthreshold/BucketThresholdConditionTemplateCompiler.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/bucketthreshold/BucketThresholdConditionTemplateCompiler.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY53290  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java
data: ('HY53290', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTestBase.java', ';', '8/5/20 12:27', ';', 'I94308175cfd806a24047348bf5ecb941ac181019')
write pr: HY12839  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HY12839', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '11/15/19 15:22', ';', 'I7fe17b9acec09f13a00103a81f168cf5060a7d57')
write pr: HY67817  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestParentUiEntityMapper.java
data: ('HY67817', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestParentUiEntityMapper.java', ';', '10/21/20 5:53', ';', 'I11e9b8b7849abdcbf3673ed8bd2fb5be733f5559')
write pr: HY60708  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java
data: ('HY60708', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/scenariotriggeredrule/ScenarioTriggeredActionListProvider.java', ';', '9/21/20 14:28', ';', 'If708498aad29a9c2bf1b9ce366b4d8058c80567c')
write pr: HY66304  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java
data: ('HY66304', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/BucketBalanceHook.java', ';', '10/26/20 9:09', ';', 'I8cd21c16479f61b5d795e0dc3b8e2f91da66ccbd')
write pr: HY65732  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/CertificateValidator.java
data: ('HY65732', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/CertificateValidator.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY54229  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY54229', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '8/5/20 18:08', ';', 'Ib34a1ef75eba28e2d1dde91e972dac0c7f71da1d')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java', ';', '7/29/20 13:13', ';', 'Ia729b87fe2732524a7dcbb29f88019d4d67f3e3d')
write pr: HX70485  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/CustomerFacingServiceSpecificationPageConverter.java
data: ('HX70485', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/customerfacingservicespecification/CustomerFacingServiceSpecificationPageConverter.java', ';', '6/5/19 8:19', ';', 'I214ddd45a19618182181522447d72731f5ab60cd')
write pr: HY60437  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestHiddenUiEntityMapper.java
data: ('HY60437', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestHiddenUiEntityMapper.java', ';', '9/4/20 6:08', ';', 'I69cfd57a14355f01285abe37f29243e56d81f62a')
write pr: HX86828  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNesConsumableUnitsValidationRule.java
data: ('HX86828', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestNesConsumableUnitsValidationRule.java', ';', '9/2/19 11:52', ';', 'I33357fbe9fad2076f17854bd9ad16db1bbceeccf')
write pr: HY24061  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java
data: ('HY24061', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/TestPresetToPolicyValueConverter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/TestPresetToPolicyValueConverter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY24061  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java
data: ('HY24061', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedLifecycleSpecificationProvider.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY52330  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedBillingAccountHelper.java
data: ('HY52330', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedBillingAccountHelper.java', ';', '7/17/20 17:04', ';', 'I703abd7fbe17f678bd54236d59906abdd8b2e687')
write pr: HY50582  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAccumulateConsumedUnitsValidationRule.java
data: ('HY50582', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationAccumulateConsumedUnitsValidationRule.java', ';', '7/8/20 6:37', ';', 'I9c1fa14935e1d01bb32cda5ba5e060ab6c9a8ca2')
write pr: HX71714  java: jivetest/src/main/java/com/ericsson/bss/rmca/jive/utils/coba/NotificationServiceWrapper.java
data: ('HX71714', ';', 'jivetest/src/main/java/com/ericsson/bss/rmca/jive/utils/coba/NotificationServiceWrapper.java', ';', '6/3/19 8:33', ';', 'I656e5c9d581288f911458386a3c91e625e0d2527')
write pr: HY64618  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java
data: ('HY64618', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java', ';', '9/28/20 8:48', ';', 'Icbb4120f32858ab379866de06b3baede1b651c72')
write pr: HY21740  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestEventReasonCode.java
data: ('HY21740', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/global/TestEventReasonCode.java', ';', '1/16/20 8:31', ';', 'Ibe2e0485ebbb1987e1d7d08741e7efa88d1d09bc')
write pr: HY28857  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/VreHelper.java
data: ('HY28857', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/VreHelper.java', ';', '2/26/20 14:45', ';', 'I0ba82cd3da3b2d2df57a62bfd0403a8419b0906f')
write pr: HY21708  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestProductStateAlreadySuspendedOrInactivated.java
data: ('HY21708', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/internal/TestProductStateAlreadySuspendedOrInactivated.java', ';', '1/16/20 8:31', ';', 'I656f6de36d0b8fad46310f767d609f2c4552f438')
write pr: HY24061  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/RepeatableEntityConfigurationProvisioner.java
data: ('HY24061', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/RepeatableEntityConfigurationProvisioner.java', ';', '1/29/20 11:47', ';', 'Id63190327cfdc4e84bb79f3ea15f27d6957517fa')
write pr: HY46749  java: jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestErrorHandler.java
data: ('HY46749', ';', 'jaxrspublisher/src/test/java/com/ericsson/bss/rmca/jaxrspublisher/internal/TestErrorHandler.java', ';', '6/15/20 21:51', ';', 'I42930cf8ba1c08e8177d156ccc05ef306c3b644b')
write pr: HX72276  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicPossibleValueModificationInVersionRule.java
data: ('HX72276', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelaxCharacteristicPossibleValueModificationInVersionRule.java', ';', '6/17/19 19:09', ';', 'I37a4da60a582bda294fa02a01ea6e2979ff93861')
write pr: HY58373  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestNormalizedParameter.java
data: ('HY58373', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/global/TestNormalizedParameter.java', ';', '8/19/20 11:41', ';', 'I53a3c42384f917ad2c1aad0e272ae125675ddfe2')
write pr: HY39972  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java
data: ('HY39972', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestProductSpecificationPage.java', ';', '4/30/20 6:15', ';', 'I629f4a47960687b6a4fa395c674aad8b654a8c16')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestBucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestBucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HX80786  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestEntityReadApi.java
data: ('HX80786', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestEntityReadApi.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HY19473  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceConverter.java
data: ('HY19473', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketbalance/BucketBalanceConverter.java', ';', '12/20/19 13:32', ';', 'Id427faf9ca2c1075a078de981e71c884657e94d7')
write pr: HX91715  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java
data: ('HX91715', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY48964  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestParameterizedBucketTagReferenceCharacteristicsDecorationProvider.java
data: ('HY48964', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestParameterizedBucketTagReferenceCharacteristicsDecorationProvider.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HX77827  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java
data: ('HX77827', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/generator/RmcaDefinitionsSerializer.java', ';', '7/8/19 13:34', ';', 'Ic5d84a0ee85b7636ab497b74f4757b82924b01db')
write pr: HY42777  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java
data: ('HY42777', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/compilers/actiontemplates/AbstractActionTemplateCompiler.java', ';', '5/29/20 6:07', ';', 'Ie9ad14d2533e0d7a6c9cad84f2928d596556ec55')
write pr: HX99743  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java
data: ('HX99743', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java', ';', '11/7/19 11:16', ';', 'I7c1a23ec490ef627914ee611ece361a23b46513f')
write pr: HY53290  java: integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/event/TestBasPriorityListManagement_ITCase.java
data: ('HY53290', ';', 'integrationtest/testsystem/src/test/java/com/ericsson/bss/rmca/integrationtest/testsystem/event/TestBasPriorityListManagement_ITCase.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HY43705  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/RefillSendExternalNotificationTemplateProvider.java
data: ('HY43705', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/externalnotification/RefillSendExternalNotificationTemplateProvider.java', ';', '5/20/20 8:56', ';', 'I2d85a2de97585e405042f92048da30836f514228')
write pr: HY51063  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicCustomPurposeValidationRule.java', ';', '7/28/20 12:15', ';', 'I772760377e2b68e3f16cc0a8871249e15d6548c7')
write pr: HX80786  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/InternalRestImplBase.java
data: ('HX80786', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/InternalRestImplBase.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX85100  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/PublishPageTransactionImpl.java
data: ('HX85100', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/PublishPageTransactionImpl.java', ';', '9/3/19 8:44', ';', 'Icb5d2f37ed7218d2e33572e61044c13c21e33719')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java', ';', '6/3/19 9:06', ';', 'I37bdbfc1e3f0d67251de9be302d2bf191c5f4e4d')
write pr: HX90022  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/ExportData.java
data: ('HX90022', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/importexport/ExportData.java', ';', '9/16/19 11:49', ';', 'I6687915584c83b5d253d629b97bfbdf64121fb60')
write pr: HY54229  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HY54229', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '8/5/20 18:08', ';', 'Ib34a1ef75eba28e2d1dde91e972dac0c7f71da1d')
write pr: HY64004  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HY64004', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '9/22/20 11:26', ';', 'Ic091f771b7162e0a04af65703fbb37fc7fababd3')
write pr: HY56644  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/LifecycleBaseStateTransitionRuleConverter.java

write pr: HY76158  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HY76158', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '12/18/20 13:18', ';', 'I526f074db835e50317acc2606f6fef4814c9c114')
write pr: HY82987  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedBillingAccountHelper.java
data: ('HY82987', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedBillingAccountHelper.java', ';', '2/12/21 13:10', ';', 'I0a0e081bba0b4151faabde3a7fffc53bda1ca5da')
write pr: HY80326  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TaxExemptionSpecificationAdapter.java
data: ('HY80326', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TaxExemptionSpecificationAdapter.java', ';', '1/14/21 8:44', ';', 'Ie4787d4f43052e82f66f59e734fccef3e1d6d813')
write pr: HY78897  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/NormalizedEventSpecificationPage.java
data: ('HY78897', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/NormalizedEventSpecificationPage.java', ';', '12/22/20 11:55', ';', 'I04c4bac3c7defafb5ac0e555dd18060ccf626643')
write pr: HY81210  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityChangeService_ITCase.java
data: ('HY81210', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestEntityChangeService_ITCase.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/NetworkPolicyGroupPriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/NetworkPolicyGroupPriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsUpdaterTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsUpdaterTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkPolicyGroupPriorityListDataMigration.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkPolicyGroupPriorityListDataMigration.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81210  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/NetworkPolicyGroupPriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/NetworkPolicyGroupPriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81679  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sessionsetupfee/TestSessionSetupFeeTemplateProvider.java
data: ('HY81679', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sessionsetupfee/TestSessionSetupFeeTemplateProvider.java', ';', '1/23/21 20:50', ';', 'I69ffa54dbc7fa256ddfa9f07c82b7c150d1d152f')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81414  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestBillingCycleSpecificationFromAgreementPageConverter.java
data: ('HY81414', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestBillingCycleSpecificationFromAgreementPageConverter.java', ';', '1/19/21 10:01', ';', 'Id22ae279bc9f09042ee3c4cc91a979c6ccb3c00e')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY78897  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/TestNormalizedEventSpecificationPage.java
data: ('HY78897', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/TestNormalizedEventSpecificationPage.java', ';', '12/22/20 11:55', ';', 'I04c4bac3c7defafb5ac0e555dd18060ccf626643')
write pr: HY80326  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/EntityReadApi.java
data: ('HY80326', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/EntityReadApi.java', ';', '1/14/21 8:44', ';', 'Ie4787d4f43052e82f66f59e734fccef3e1d6d813')
write pr: HY81210  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/NoChangesAreAllowedInActivationValidationRule.java
data: ('HY81210', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/NoChangesAreAllowedInActivationValidationRule.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/BucketPrioritiesResolver.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/BucketPrioritiesResolver.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY80326  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TaxExemptionSpecificationAdapter.java
data: ('HY80326', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TaxExemptionSpecificationAdapter.java', ';', '1/14/21 8:44', ';', 'Ie4787d4f43052e82f66f59e734fccef3e1d6d813')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/BucketPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/BucketPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY76158  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java
data: ('HY76158', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java', ';', '1/5/21 8:26', ';', 'I726f9045f92a2de202c1f14f5262208d99bd4fc5')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY76158  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/SlimStrategy.java
data: ('HY76158', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/SlimStrategy.java', ';', '12/18/20 13:18', ';', 'I526f074db835e50317acc2606f6fef4814c9c114')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/ResourcePrioritiesProvider.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/ResourcePrioritiesProvider.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/RelatedProductPriorityListResolver.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/RelatedProductPriorityListResolver.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY85154  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/commoncharacteristic/CommonCharacteristicTemplateConverter.java
data: ('HY85154', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/commoncharacteristic/CommonCharacteristicTemplateConverter.java', ';', '2/12/21 12:12', ';', 'I7d5cf2585d6ed62cedbd6d8e9832ec572874ab47')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationPageToEntityMapper.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationPageToEntityMapper.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/AddToTaggedBucketPriorityListTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/AddToTaggedBucketPriorityListTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/AbstractPageWithBucketPriorityListTest.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/AbstractPageWithBucketPriorityListTest.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListRankingEntryExtractor.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListRankingEntryExtractor.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestProductPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestProductPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestGlobalPriorityListImporter.java
data: ('HY81210', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestGlobalPriorityListImporter.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY82015  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY82015', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '1/19/21 10:35', ';', 'I3c5daa61be5f9ac28fb5da1168ed44dada99237a')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestNetworkPolicyGroupPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestNetworkPolicyGroupPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestGlobalPriorityListImporter.java
data: ('HY81210', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestGlobalPriorityListImporter.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY76158  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java
data: ('HY76158', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java', ';', '12/18/20 13:18', ';', 'I526f074db835e50317acc2606f6fef4814c9c114')
write pr: HY81210  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ProductPriorityListProvisioner.java

data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListVersionUpdaterFactory.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HY81210', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListVersionUpdaterFactory.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListVersionUpdaterFactory.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/NoChangesAreAllowedInActivationValidationRule.java
data: ('HY81210', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/NoChangesAreAllowedInActivationValidationRule.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationPageToEntityMapper.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationPageToEntityMapper.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestSharingProviderPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestSharingProviderPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/ProductPriorityListImporter.java
data: ('HY81210', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/ProductPriorityListImporter.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY82015  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY82015', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '1/19/21 10:35', ';', 'I3c5daa61be5f9ac28fb5da1168ed44dada99237a')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/SharingProviderPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/SharingProviderPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestRelatedProductPriorityListResolver.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestRelatedProductPriorityListResolver.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY79243  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HY79243', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '12/22/20 15:46', ';', 'Ifda0dca09eeada6add9de92ed3d873d36e081e16')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListRankingEntryExtractor.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListRankingEntryExtractor.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY85154  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/commoncharacteristic/TestCommonCharacteristicTemplateConverter.java
data: ('HY85154', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/commoncharacteristic/TestCommonCharacteristicTemplateConverter.java', ';', '2/12/21 12:12', ';', 'I7d5cf2585d6ed62cedbd6d8e9832ec572874ab47')
write pr: HY83614  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestBucketPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestBucketPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HY81210', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/ProductPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/ProductPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterTemplateProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterTemplateProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestNetworkPolicyGroupPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestNetworkPolicyGroupPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY76158  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/UseResumptionTimeCharacteristicBuilder.java
data: ('HY76158', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/UseResumptionTimeCharacteristicBuilder.java', ';', '12/18/20 13:18', ';', 'I526f074db835e50317acc2606f6fef4814c9c114')
write pr: HY81210  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/ProductPriorityListImporter.java
data: ('HY81210', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/ProductPriorityListImporter.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY80326  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TestTaxExemptionSpecificationAdapter.java
data: ('HY80326', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TestTaxExemptionSpecificationAdapter.java', ';', '1/14/21 8:44', ';', 'Ie4787d4f43052e82f66f59e734fccef3e1d6d813')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billingaccountspecification/BillingAccountSpecificationListEntryConverter.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billingaccountspecification/BillingAccountSpecificationListEntryConverter.java', ';', '2/15/21 14:07', ';', 'I5a6b0f2f3d282d22a675ac28437adff2ebde9aa2')
write pr: HY81414  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageToEntityMapper.java
data: ('HY81414', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageToEntityMapper.java', ';', '1/19/21 10:01', ';', 'Id22ae279bc9f09042ee3c4cc91a979c6ccb3c00e')
write pr: HY81210  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HY81210', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/communitymembership/TestServiceSpecificParameter.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/communitymembership/TestServiceSpecificParameter.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListDataMigration.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListDataMigration.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81679  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sessionsetupfee/TestSessionSetupFeeTemplateProvider.java
data: ('HY81679', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sessionsetupfee/TestSessionSetupFeeTemplateProvider.java', ';', '1/23/21 20:50', ';', 'I69ffa54dbc7fa256ddfa9f07c82b7c150d1d152f')
write pr: HY81210  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/AbstractPriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/AbstractPriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY78897  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/NormalizedEventSpecificationCapabilities.java
data: ('HY78897', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/NormalizedEventSpecificationCapabilities.java', ';', '12/22/20 11:55', ';', 'I04c4bac3c7defafb5ac0e555dd18060ccf626643')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationPriorityManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationPriorityManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/ResourceProvider.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/ResourceProvider.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/ProductPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/ProductPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY78897  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/TestNormalizedEventSpecificationPageConverter.java
data: ('HY78897', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/normalizedeventspecification/TestNormalizedEventSpecificationPageConverter.java', ';', '12/22/20 11:55', ';', 'I04c4bac3c7defafb5ac0e555dd18060ccf626643')
write pr: HY76158  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestUseResumptionTimeCharacteristicBuilder.java
data: ('HY76158', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/TestUseResumptionTimeCharacteristicBuilder.java', ';', '12/18/20 13:18', ';', 'I526f074db835e50317acc2606f6fef4814c9c114')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListRankingEntryExtractor.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListRankingEntryExtractor.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/RecurrencePriorityListProvisioner.java
data: ('HY81210', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/RecurrencePriorityListProvisioner.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81414  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/BillingCycleSpecificationFromAgreementPageConverter.java
data: ('HY81414', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/BillingCycleSpecificationFromAgreementPageConverter.java', ';', '1/19/21 10:01', ';', 'Id22ae279bc9f09042ee3c4cc91a979c6ccb3c00e')

write pr: HY81210  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/BillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HY81210', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/BillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/TestBucketPrioritiesResolver.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/prioritylisttable/TestBucketPrioritiesResolver.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY79243  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HY79243', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '12/22/20 15:46', ';', 'Ifda0dca09eeada6add9de92ed3d873d36e081e16')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestProductPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestProductPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81679  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sessionsetupfee/TestSessionSetupFeeTemplateProvider.java
data: ('HY81679', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sessionsetupfee/TestSessionSetupFeeTemplateProvider.java', ';', '1/23/21 20:50', ';', 'I69ffa54dbc7fa256ddfa9f07c82b7c150d1d152f')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListVersionUpdaterFactory.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListVersionUpdaterFactory.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY80468  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/TestAffectedEntity.java
data: ('HY80468', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/TestAffectedEntity.java', ';', '1/8/21 17:46', ';', 'I800ee7b6e377f7b9f1317fb0f225ca3514f02818')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/AddToTaggedBucketPriorityListTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/AddToTaggedBucketPriorityListTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/communitymembership/TestServiceSpecificParameter.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/communitymembership/TestServiceSpecificParameter.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81414  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestBillingCycleSpecificationFromAgreementPageConverter.java
data: ('HY81414', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestBillingCycleSpecificationFromAgreementPageConverter.java', ';', '1/19/21 10:01', ';', 'Id22ae279bc9f09042ee3c4cc91a979c6ccb3c00e')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestBucketPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestBucketPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/GlobalPriorityListImporter.java
data: ('HY81210', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/GlobalPriorityListImporter.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY79243  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HY79243', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '12/22/20 15:46', ';', 'Ifda0dca09eeada6add9de92ed3d873d36e081e16')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListVersionUpdaterFactory.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListVersionUpdaterFactory.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY82015  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY82015', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '1/19/21 10:35', ';', 'I3c5daa61be5f9ac28fb5da1168ed44dada99237a')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterTemplateProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/normalizedparameter/NormalizedParameterTemplateProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY80468  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/AffectedEntity.java
data: ('HY80468', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/AffectedEntity.java', ';', '1/8/21 17:46', ';', 'I800ee7b6e377f7b9f1317fb0f225ca3514f02818')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83666  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestChargeEventItemizationSpecificationPageConverter.java
data: ('HY83666', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestChargeEventItemizationSpecificationPageConverter.java', ';', '2/4/21 17:38', ';', 'I77de173f894eebe7898e2d38b9441cea232ae458')
write pr: HY82987  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedBillingAccountHelper.java
data: ('HY82987', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedBillingAccountHelper.java', ';', '2/12/21 13:10', ';', 'I0a0e081bba0b4151faabde3a7fffc53bda1ca5da')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestSharingProviderPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestSharingProviderPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY81210  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HY81210', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY80326  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/URLPathTrafficEntityResolver.java
data: ('HY80326', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/URLPathTrafficEntityResolver.java', ';', '1/14/21 8:44', ';', 'Ie4787d4f43052e82f66f59e734fccef3e1d6d813')
write pr: HY82015  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY82015', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '1/19/21 10:35', ';', 'I3c5daa61be5f9ac28fb5da1168ed44dada99237a')
write pr: HY81210  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java
data: ('HY81210', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billingaccountspecification/BillingAccountSpecificationListEntryConverter.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billingaccountspecification/BillingAccountSpecificationListEntryConverter.java', ';', '2/15/21 14:07', ';', 'I5a6b0f2f3d282d22a675ac28437adff2ebde9aa2')
write pr: HY81210  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/RecurrencePriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/RecurrencePriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY76158  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/pops/SlimProductOfferingPriceSpecification.java
data: ('HY76158', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/pops/SlimProductOfferingPriceSpecification.java', ';', '12/18/20 13:18', ';', 'I526f074db835e50317acc2606f6fef4814c9c114')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/AddToTaggedBucketPriorityListTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/AddToTaggedBucketPriorityListTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/AbstractPageWithBucketPriorityListTest.java
data: ('HY81210', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/AbstractPageWithBucketPriorityListTest.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestProductPriorityListImporter.java
data: ('HY81210', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/TestProductPriorityListImporter.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY83614  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java
data: ('HY83614', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java', ';', '1/29/21 7:55', ';', 'I9fadf1c2479da8aada9e94b69ecb6558812f667a')
write pr: HY80326  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TestTaxExemptionSpecificationAdapter.java
data: ('HY80326', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TestTaxExemptionSpecificationAdapter.java', ';', '1/14/21 8:44', ';', 'Ie4787d4f43052e82f66f59e734fccef3e1d6d813')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListDataMigration.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListDataMigration.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BucketTagBucketPriorityListManagement.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BucketTagBucketPriorityListManagement.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY85154  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/commoncharacteristic/TestCommonCharacteristicTemplateConverter.java
data: ('HY85154', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/commoncharacteristic/TestCommonCharacteristicTemplateConverter.java', ';', '2/12/21 12:12', ';', 'I7d5cf2585d6ed62cedbd6d8e9832ec572874ab47')
write pr: HY81210  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java
data: ('HY81210', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY81210  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestBucketPriorityListUpdater.java
data: ('HY81210', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestBucketPriorityListUpdater.java', ';', '2/15/21 6:51', ';', 'I68ceddd5b1618b17d2d12d63d817ae80255ac2eb')
write pr: HY82907  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/communitymembership/TestServiceSpecificParameter.java
data: ('HY82907', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/communitymembership/TestServiceSpecificParameter.java', ';', '1/25/21 12:17', ';', 'I752ae0a3bba83e5c7277a0509275387a4057d926')

write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/main/java/com/ericsson/bss/rmca/examples/EventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/EventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/TestTransactionEventPublisherImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/TestTransactionEventPublisherImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListsUpdaterTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/TestIdentifiedTaskExecutorServiceImpl.java
data: ('HY68239', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/TestIdentifiedTaskExecutorServiceImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductListUpdate.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductListUpdate.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/IdentifiedTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/IdentifiedTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY72715  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/defaultcondition/DefaultConditionTemplateConverter.java
data: ('HY72715', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/defaultcondition/DefaultConditionTemplateConverter.java', ';', '11/27/20 12:28', ';', 'Ib6b429fe634082e140eafd74bf6e55abf07a319d')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/TestProductPriorityListGeneratorEventConsumer.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/TestProductPriorityListGeneratorEventConsumer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/DataImport.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/DataImport.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/TestIdentifiedTaskExecutorServiceImpl.java
data: ('HY68239', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/TestIdentifiedTaskExecutorServiceImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/PriorityListManagementTaskFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductListUpdate.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductListUpdate.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/TestProductPriorityListGeneratorEventConsumer.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/TestProductPriorityListGeneratorEventConsumer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsFiltererTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsFiltererTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestGenericPriorityListManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListManagement.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/ScenarioTriggeredEventTriggerDetailsUpdateEventConsumer.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/ScenarioTriggeredEventTriggerDetailsUpdateEventConsumer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY72715  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/defaultcondition/DefaultConditionTemplateConverter.java
data: ('HY72715', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/defaultcondition/DefaultConditionTemplateConverter.java', ';', '11/27/20 12:28', ';', 'Ib6b429fe634082e140eafd74bf6e55abf07a319d')
write pr: HY72715  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/CusCondition.java
data: ('HY72715', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/CusCondition.java', ';', '11/27/20 12:28', ';', 'Ib6b429fe634082e140eafd74bf6e55abf07a319d')
write pr: HY68239  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/event/TestTransactionEventBus_ITCase.java
data: ('HY68239', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/event/TestTransactionEventBus_ITCase.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/event/RmcaEventConstants.java
data: ('HY68239', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/event/RmcaEventConstants.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/TestScenarioTriggeredEventTriggerDetailsUpdateTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/TestScenarioTriggeredEventTriggerDetailsUpdateTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/TestScenarioTriggeredEventTriggerDetailsUpdateTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/TestScenarioTriggeredEventTriggerDetailsUpdateTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/event/RmcaEventConstants.java
data: ('HY68239', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/event/RmcaEventConstants.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorker.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorker.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/FilterTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')

data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestFilterTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/event/RmcaEventConstants.java
data: ('HY68239', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/event/RmcaEventConstants.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/GenericPriorityListManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/GenericPriorityListManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImport_UseCase.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/TestScenarioTriggeredEventTriggerDetailsUpdateEventConsumer.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/TestScenarioTriggeredEventTriggerDetailsUpdateEventConsumer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorkerImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorkerImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/event/TestTransactionEventBus_ITCase.java
data: ('HY68239', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/event/TestTransactionEventBus_ITCase.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/ScenarioTriggeredEventTriggerDetailsUpdateTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/ScenarioTriggeredEventTriggerDetailsUpdateTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorkerImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorkerImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/cache/IdentifiedTaskExecutorService.java
data: ('HY68239', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/cache/IdentifiedTaskExecutorService.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/cache/IdentifiedTaskExecutorService.java
data: ('HY68239', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/cache/IdentifiedTaskExecutorService.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImport.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImport.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/ProductPriorityListGeneratorEventConsumer.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/productprioritygenerator/ProductPriorityListGeneratorEventConsumer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsUpdaterTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsUpdaterTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventAdminStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java
data: ('HY68239', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/cache/IdentifiedTaskExecutorServiceImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListManagement.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListManagement.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ImportExportImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsFiltererTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsFiltererTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/TestTransactionEventPublisherImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/TestTransactionEventPublisherImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY72715  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/defaultcondition/DefaultConditionTemplateConverter.java
data: ('HY72715', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/defaultcondition/DefaultConditionTemplateConverter.java', ';', '11/27/20 12:28', ';', 'Ib6b429fe634082e140eafd74bf6e55abf07a319d')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestAddToTaggedBucketPriorityListTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java
data: ('HY68239', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBillingAccountSpecificationDeactivationManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsUpdaterTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestProductPriorityListsUpdaterTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BillingAccountSpecificationDeactivationManagementTask.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBasPriorityListManagement.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBasPriorityListManagement.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorkerImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/executor/EventConsumerThreadPoolWorkerImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductListUpdate.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductListUpdate.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/SpecificationUpdater.java
data: ('HY68239', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/SpecificationUpdater.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestEventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java
data: ('HY68239', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestPriorityListManagementTaskFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductPrioList.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductPrioList.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/main/java/com/ericsson/bss/rmca/examples/EventConsumerThreadPoolWorkerStub.java
data: ('HY68239', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/EventConsumerThreadPoolWorkerStub.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImport.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImport.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HY68239', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY72715  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/CusCondition.java
data: ('HY72715', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/CusCondition.java', ';', '11/27/20 12:28', ';', 'Ib6b429fe634082e140eafd74bf6e55abf07a319d')
write pr: HY68239  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductPrioList.java
data: ('HY68239', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/productpriolist/TestProductPrioList.java', ';', '11/24/20 13:09', ';', 'I67c43e922fa010152663e194164861f1ad8345ef')
write pr: HY68239  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java

write pr: HY89080  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationSlimDocument.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationSlimDocument.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY84047  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationOverrideNesValidationRule.java
data: ('HY84047', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationOverrideNesValidationRule.java', ';', '3/2/21 11:19', ';', 'I3c8e5abc751d0162a50263c5834b6c9576ac28c9')
write pr: HY84047  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationOverrideNesValidationRule.java
data: ('HY84047', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationOverrideNesValidationRule.java', ';', '3/2/21 11:19', ';', 'I3c8e5abc751d0162a50263c5834b6c9576ac28c9')
write pr: HY89080  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/AggregationLevelCriteria.java
data: ('HY89080', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/AggregationLevelCriteria.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY89080  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationSlimDocument.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationSlimDocument.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY84047  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationOverrideNesValidationRule.java
data: ('HY84047', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationOverrideNesValidationRule.java', ';', '3/2/21 11:19', ';', 'I3c8e5abc751d0162a50263c5834b6c9576ac28c9')
write pr: HY84047  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationOverrideNesValidationRule.java
data: ('HY84047', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationOverrideNesValidationRule.java', ';', '3/2/21 11:19', ';', 'I3c8e5abc751d0162a50263c5834b6c9576ac28c9')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationListEntry.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationListEntry.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationSlimDocument.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationSlimDocument.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY89080  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationListEntry.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationListEntry.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89080  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/TestAggregationLevelCriteria.java
data: ('HY89080', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/TestAggregationLevelCriteria.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationListEntry.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationListEntry.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billspecification/aggregations/PredefinedBillSpecificationAggregationLevels.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billspecification/aggregations/PredefinedBillSpecificationAggregationLevels.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY89080  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/AggregationLevelCriteria.java
data: ('HY89080', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/AggregationLevelCriteria.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationListEntry.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationListEntry.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY89080  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/TestAggregationLevelCriteria.java
data: ('HY89080', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/characteristic/TestAggregationLevelCriteria.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89080  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationListEntry.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationListEntry.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY89080  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationSlimDocument.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationSlimDocument.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billspecification/aggregations/PredefinedBillSpecificationAggregationLevels.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billspecification/aggregations/PredefinedBillSpecificationAggregationLevels.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestMetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationSlimDocument.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationSlimDocument.java', ';', '3/2/21 12:22', ';', 'I29240cf72c3a5c1d97f3927ba0669d5a82ecb24b')
write pr: HY89080  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationSlimDocument.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/BillSpecificationSlimDocument.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY89080  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationListEntry.java
data: ('HY89080', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/billspecification/TestBillSpecificationListEntry.java', ';', '3/2/21 13:33', ';', 'Icfa982a9535318b005bd8c7d0cba59c8cccead30')
write pr: HY88913  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java
data: ('HY88913', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/MetaDataValidationUtil.java', ';', '3/2/21 13:15', ';', 'I7e0be4a9e034f7e59692fa522b75513858c5ccac')
write pr: HY89037  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java
data: ('HY89037', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java
data: ('HY89037', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java
data: ('HY89037', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java
data: ('HY89037', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/DownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java
data: ('HY89037', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/dependency/TestDownstreamDependency_UseCase.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')
write pr: HY89037  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java
data: ('HY89037', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/dependency/TestDownstreamDependencyAnalyzer.java', ';', '3/3/21 13:38', ';', 'Ib1a8503a13ead41f0e20f7120ced0f5198aff465')

write pr: HY91241  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java
data: ('HY91241', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: restproxy/api/src/main/java/com/ericsson/bss/rmca/restproxy/api/notificationtemplate/Category.java
data: ('HY91241', ';', 'restproxy/api/src/main/java/com/ericsson/bss/rmca/restproxy/api/notificationtemplate/Category.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java
data: ('HY91241', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/TestRuleContext_ITCase.java
data: ('HY91241', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/TestRuleContext_ITCase.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java
data: ('HY91241', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestScenarioFactoryImpl.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/PredefinedScenario.java
data: ('HY91241', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/PredefinedScenario.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/PredefinedScenario.java
data: ('HY91241', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/PredefinedScenario.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java
data: ('HY91241', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY91241  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java
data: ('HY91241', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ScenarioFactoryImpl.java', ';', '3/16/21 9:16', ';', 'I5095f4c9a753399f3d4c918c4dcd16653ab737fc')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/NetworkAuthorizationRuleBehaviorDecorationProvider.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/NetworkAuthorizationRuleBehaviorDecorationProvider.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestNetworkAuthorizationRuleBehaviorDecorationProvider.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestNetworkAuthorizationRuleBehaviorDecorationProvider.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/NetworkAuthorizationRuleBehaviorDecorationProvider.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/NetworkAuthorizationRuleBehaviorDecorationProvider.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java
data: ('HY87723', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java
data: ('HY87723', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java
data: ('HY87723', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/networkauthorization/TestNetworkAuthorizationCompiledRuleToRmcaEntityConverter.java
data: ('HY87723', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/networkauthorization/TestNetworkAuthorizationCompiledRuleToRmcaEntityConverter.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/RuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java
data: ('HY87723', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java
data: ('HY87723', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java
data: ('HY87723', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestNetworkAuthorizationRuleBehaviorDecorationProvider.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestNetworkAuthorizationRuleBehaviorDecorationProvider.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/NetworkAuthorizationRuleBehaviorDecorationProvider.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/NetworkAuthorizationRuleBehaviorDecorationProvider.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestNetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkAuthorizationRuleBehaviorDataMigration.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/NetworkAuthorizationRuleBehaviorDataMigration.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestNetworkAuthorizationRuleBehaviorDecorationProvider.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestNetworkAuthorizationRuleBehaviorDecorationProvider.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '3/19/21 7:44', ';', 'I07514e3305b2ee226e7c6266dbd7cd496f9310c5')
write pr: HY87723  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/TestNetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java
data: ('HY87723', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/NetworkAuthorizationRuleBehaviorDecorator.java', ';', '3/19/21 7:44', ';', 'I2c1f07ed252277a1d60c84468caedbb6d82a04f1')
write pr: HY87723  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HY87723', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '3/19/21 7:44', ';', 'I60eaddd8a81aa4c7470c4441e92e835ba94a15ac')
write pr: HY87723  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rule/rule/TestRuleBehaviorRuleDecorator.java

data: ('HY92395', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92395  java: restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/filter/ProviderPriority.java
data: ('HY92395', ';', 'restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/filter/ProviderPriority.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY92395  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java
data: ('HY92395', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92395  java: restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/ResponseBuilder.java
data: ('HY92395', ';', 'restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/ResponseBuilder.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY92395  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java
data: ('HY92395', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY92395  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestResponseBuilder.java
data: ('HY92395', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestResponseBuilder.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY92395  java: restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/ResponseBuilder.java
data: ('HY92395', ';', 'restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/ResponseBuilder.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92395  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java
data: ('HY92395', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '3/24/21 19:17', ';', 'I44d73828d486169c97966f052d4c198384ee0664')
write pr: HY92395  java: restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/filter/ProviderPriority.java
data: ('HY92395', ';', 'restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/filter/ProviderPriority.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92395  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java
data: ('HY92395', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/SecurityRequestFilterImpl.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92395  java: restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/filter/SecurityRequestFilter.java
data: ('HY92395', ';', 'restservice/base/src/main/java/com/ericsson/bss/rmca/restservice/base/filter/SecurityRequestFilter.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92395  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java
data: ('HY92395', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/TestSecurityRequestFilterImpl.java', ';', '3/23/21 21:32', ';', 'Id0e9cb3a2520736432795951aa509c3d1c7f3c10')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsNoRmRefToNESWithUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsNoRmRefToNESWithUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/PolicyValueSpecificationNoRmRefToNESWithUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/PolicyValueSpecificationNoRmRefToNESWithUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/TestPolicyValueSpecificationNoRmRefToNesWithUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/TestPolicyValueSpecificationNoRmRefToNesWithUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/TestPopsNoRmRefToNesWithUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/TestPopsNoRmRefToNesWithUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/NormalizedEventSpecificationCharacteristicCanNotUseUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/NormalizedEventSpecificationCharacteristicCanNotUseUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY92098', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY92098', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/TestNormalizedEventSpecificationCanNotUseUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/TestNormalizedEventSpecificationCanNotUseUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NormalizedEventSpecificationValidationRuleProvider.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/NormalizedEventSpecificationValidationRuleProvider.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/PolicyValueSpecificationNoRmRefToNESWithDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/PolicyValueSpecificationNoRmRefToNESWithDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueSpecificationValidationRuleProvider.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueSpecificationValidationRuleProvider.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/NormalizedEventSpecificationCharacteristicCanNotUseDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/NormalizedEventSpecificationCharacteristicCanNotUseDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/TestPopsNoRmRefToNesWithDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/TestPopsNoRmRefToNesWithDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY92098', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsNoRmRefToNESWithDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsNoRmRefToNESWithDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/TestNormalizedEventSpecificationCanNotUseDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/TestNormalizedEventSpecificationCanNotUseDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductOfferingPriceSpecificationValidationRuleProvider.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductOfferingPriceSpecificationValidationRuleProvider.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/TestPolicyValueSpecificationNoRmRefToNesWithDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/TestPolicyValueSpecificationNoRmRefToNesWithDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY92098', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY92098', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/TestPopsNoRmRefToNesWithDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/TestPopsNoRmRefToNesWithDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/TestNormalizedEventSpecificationCanNotUseDeprecatedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/normalizedeventspecification/TestNormalizedEventSpecificationCanNotUseDeprecatedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsNoRmRefToNESWithUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productofferingpricespecification/PopsNoRmRefToNESWithUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/TestPolicyValueSpecificationNoRmRefToNesWithUnsupportedValueTypeValidationRule.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvaluespecification/TestPolicyValueSpecificationNoRmRefToNesWithUnsupportedValueTypeValidationRule.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')

data: ('HY94345', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/filters/ListPublicQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/MockQueryFactory.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/MockQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestUrlPathExtendedTrafficEntityResolver.java
data: ('HY94345', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestUrlPathExtendedTrafficEntityResolver.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java
data: ('HY94345', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQuery.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQuery.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQuery.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQuery.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94510  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/EtdPageToEntityMapper.java
data: ('HY94510', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/EtdPageToEntityMapper.java', ';', '3/30/21 9:06', ';', 'I752e18c0c77d9133b84189347341678bcaeea407')
write pr: HY94345  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryFactory.java
data: ('HY94345', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestIdListQuery.java
data: ('HY94345', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestIdListQuery.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestExternalQueryFactory.java
data: ('HY94345', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestExternalQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIdQueryResultImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIdQueryResultImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY92098  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java
data: ('HY92098', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestChaCompareDataConditionHook.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY92098  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HY92098', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY94345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/utils/ListPagesUtils.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/utils/ListPagesUtils.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/IdQueryResult.java
data: ('HY94345', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/IdQueryResult.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestCachedViewImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestUrlPathExtendedTrafficEntityResolver.java
data: ('HY94345', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestUrlPathExtendedTrafficEntityResolver.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/TestRestListEntityImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/TestRestListEntityImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94510  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java
data: ('HY94510', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/PopsPageToEntityMapper.java', ';', '3/30/21 9:06', ';', 'I752e18c0c77d9133b84189347341678bcaeea407')
write pr: HY94345  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisioner.java
data: ('HY94345', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisioner.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIdQuery.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIdQuery.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/TestCounterListEntry.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/TestCounterListEntry.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestAbstractPriorityListProvisioner.java
data: ('HY94345', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestAbstractPriorityListProvisioner.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY92098  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java
data: ('HY92098', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/AbstractChaConditionHook.java', ';', '3/25/21 10:32', ';', 'I9bf4720758c918b7d2f6c1b01a1b4046af245250')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPrivateQueryFactoryImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPrivateQueryFactoryImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ListPublicQueryFactory.java
data: ('HY94345', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/ListPublicQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestUrlPathTrafficEntityResolver.java
data: ('HY94345', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestUrlPathTrafficEntityResolver.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/tag/TestRestBucketTagPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/tag/TestRestBucketTagPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisioner.java
data: ('HY94345', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisioner.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java
data: ('HY94345', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestPriorityListProvisioner.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListPublicQueryFactory.java
data: ('HY94345', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListPublicQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/VersionPersistenceServiceImpl.java
data: ('HY94345', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/VersionPersistenceServiceImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestIdListQuery.java
data: ('HY94345', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestIdListQuery.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: testutil/entityserviceviewsstubs/src/main/java/com/ericsson/bss/rmca/testutil/entityserviceviews/stubs/MockIdQuery.java
data: ('HY94345', ';', 'testutil/entityserviceviewsstubs/src/main/java/com/ericsson/bss/rmca/testutil/entityserviceviews/stubs/MockIdQuery.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestRmcaVersionedEntity.java
data: ('HY94345', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestRmcaVersionedEntity.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPrivateQueryFactoryImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPrivateQueryFactoryImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94510  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/TestEtdPageToEntityMapper.java
data: ('HY94510', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/TestEtdPageToEntityMapper.java', ';', '3/30/21 9:06', ';', 'I752e18c0c77d9133b84189347341678bcaeea407')
write pr: HY94345  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java
data: ('HY94345', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/MockQueryFactory.java
data: ('HY94345', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/MockQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQuery.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQuery.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/TestCharacteristicLookupImpl.java
data: ('HY94345', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/TestCharacteristicLookupImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestRestProductOfferingPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java
data: ('HY94345', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/TestCounterListEntry.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/TestCounterListEntry.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TemporaryEntityStorage.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TemporaryEntityStorage.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TemporaryEntityStorage.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/TemporaryEntityStorage.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java
data: ('HY94345', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGeneratorImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')

write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/TestSetChargingIntervalTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/TestSetChargingIntervalTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/ConditionHelper.java
data: ('HY91667', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/ConditionHelper.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/TestDeductLinearPriceTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/TestDeductLinearPriceTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredRateHook.java
data: ('HY91667', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredRateHook.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/ConditionHelper.java
data: ('HY91667', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/ConditionHelper.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConverterUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConverterUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY94345  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/CatalogManagementApiQueryFactory.java
data: ('HY94345', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/CatalogManagementApiQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/TestCounterListEntry.java
data: ('HY94345', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/TestCounterListEntry.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/View.java
data: ('HY94345', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/View.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94510  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/TestPopsPageToEntityMapper.java
data: ('HY94510', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/TestPopsPageToEntityMapper.java', ';', '3/30/21 9:06', ';', 'I752e18c0c77d9133b84189347341678bcaeea407')
write pr: HY94345  java: configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisioner.java
data: ('HY94345', ';', 'configurationprovisioner/src/test/java/com/ericsson/bss/rmca/configurationprovisioner/TestProductPriorityListProvisioner.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryParameterFactoryImpl.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestIdListQuery.java
data: ('HY94345', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestIdListQuery.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/nes/TestRestNormalizedEventSpecificationPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/nes/TestRestNormalizedEventSpecificationPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/MockQueryFactory.java
data: ('HY94345', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/MockQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestRmcaVersionedEntity.java
data: ('HY94345', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestRmcaVersionedEntity.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/ExternalQueryFactory.java
data: ('HY94345', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/ExternalQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/nes/TestRestNormalizedEventSpecificationPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/nes/TestRestNormalizedEventSpecificationPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListPublicQueryFactory.java
data: ('HY94345', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListPublicQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListPrivateQueryFactory.java
data: ('HY94345', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListPrivateQueryFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/nes/TestRestNormalizedEventSpecificationPageImpl.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/nes/TestRestNormalizedEventSpecificationPageImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestUrlPathTrafficEntityResolver.java
data: ('HY94345', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestUrlPathTrafficEntityResolver.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIdQueryResultImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestIdQueryResultImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/utils/CompositeFactory.java
data: ('HY94345', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/utils/CompositeFactory.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: persistenceservice/src/main/java/com/ericsson/bss/rmca/persistenceservice/VersionedPersistenceService.java
data: ('HY94345', ';', 'persistenceservice/src/main/java/com/ericsson/bss/rmca/persistenceservice/VersionedPersistenceService.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestUrlPathTrafficEntityResolver.java
data: ('HY94345', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestUrlPathTrafficEntityResolver.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PrivateQueryFactoryImpl.java
data: ('HY94345', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PrivateQueryFactoryImpl.java', ';', '3/29/21 17:39', ';', 'I41908543663ce332b98c9dac23f1f43224b242a8')
write pr: HY94345  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java
data: ('HY94345', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java', ';', '3/29/21 17:39', ';', 'I117184725517533865fe3bc69fe7f215d5cbe15f')
write pr: HY94345  java: testutil/entityserviceviewsstubs/src/main/java/com/ericsson/bss/rmca/testutil/entityserviceviews/stubs/PrivateQueryFactoryStub.java

data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/TestDeductLinearPriceTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/TestDeductLinearPriceTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConverterUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConverterUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredRateHook.java
data: ('HY91667', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredRateHook.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/TestAccumulateConsumedUnitsTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java
data: ('HY91667', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredRateHook.java
data: ('HY91667', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/TieredRateHook.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/TestSetChargingIntervalTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/TestSetChargingIntervalTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConsumableUnit.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConsumableUnit.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConsumableUnit.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConsumableUnit.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/common/CommonActionTemplateUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/accumulateconsumedunits/AccumulateConsumedUnitsProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/TestSetChargingIntervalTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/TestSetChargingIntervalTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredRateHook.java
data: ('HY91667', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestTieredRateHook.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConverterUtils.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/ConverterUtils.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java
data: ('HY91667', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ConditionConstants.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplate.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setcharginginterval/SetChargingIntervalTemplate.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java
data: ('HY91667', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/deductlinearprice/DeductLinearPriceTemplateConverter.java', ';', '4/6/21 11:55', ';', 'I9c77f53ec9495cc4011714f4dfae17257b35ae39')
write pr: HY91667  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java

write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductCharge.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductCharge.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestSlimEventTriggerDetails.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestSlimEventTriggerDetails.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Refill.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Refill.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestSlimEventTriggerDetails.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestSlimEventTriggerDetails.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/UsageTriggered.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/UsageTriggered.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ScenarioTriggered.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ScenarioTriggered.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ScenarioTriggered.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ScenarioTriggered.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimRuleDetails.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimRuleDetails.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimRuleDetails.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimRuleDetails.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimRuleDetails.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimRuleDetails.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/LifecycleStateChange.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/LifecycleStateChange.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/UsageTriggered.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/UsageTriggered.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/LifecycleStateChange.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/LifecycleStateChange.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Recurrence.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Refill.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Refill.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Promotion.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductExchange.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductExchange.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductExchange.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductExchange.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/OneTimeChargeRule.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/OneTimeChargeRule.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Pricing.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/Pricing.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY97770  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java
data: ('HY97770', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java', ';', '4/19/21 13:27', ';', 'I4aeba3cb1a733b2ffcab64deea65e0ee402cc5c2')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/ConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY91270  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java
data: ('HY91270', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/preset/conditionconverter/TestConditionCharacteristicToPresetConverter.java', ';', '4/22/21 18:16', ';', 'Ib7d46cf06a2ea8a4d957ca65a3d7c43ebd3de638')
write pr: HY92980  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java
data: ('HY92980', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java', ';', '3/23/21 12:40', ';', 'I48a2799c1ecb7a8d18a5c0a485c9ce731c5b941a')
write pr: PBI:4206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PersistenceConverter.java
data: ('PBI:4206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PersistenceConverter.java', ';', '4/26/21 13:44', ';', 'Ifbcaeba8abae0880b8938ca9137db417b34df5ec')
write pr: PBI:4206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestAbstractTransactionImpl.java
data: ('PBI:4206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestAbstractTransactionImpl.java', ';', '4/26/21 13:44', ';', 'Ifbcaeba8abae0880b8938ca9137db417b34df5ec')
write pr: PBI:4206  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/po/TestProductOfferingConverter.java
data: ('PBI:4206', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/po/TestProductOfferingConverter.java', ';', '4/26/21 13:44', ';', 'Ifbcaeba8abae0880b8938ca9137db417b34df5ec')
write pr: PBI:4206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateTransactionImpl.java
data: ('PBI:4206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateTransactionImpl.java', ';', '4/26/21 13:44', ';', 'Ifbcaeba8abae0880b8938ca9137db417b34df5ec')
write pr: PBI:4206  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('PBI:4206', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '4/26/21 18:44', ';', 'Ib4773f701c7951e99b6ca370296735651f82d8a1')
write pr: PBI:4206  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PlaceholderProductOfferingPriceConverter.java
data: ('PBI:4206', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/PlaceholderProductOfferingPriceConverter.java', ';', '4/26/21 15:19', ';', 'Ib88f192efe0beb8d01b472a43e895c578005c168')
write pr: PBI:4206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java
data: ('PBI:4206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java', ';', '4/26/21 13:44', ';', 'Ifbcaeba8abae0880b8938ca9137db417b34df5ec')
write pr: PBI:4206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PlaceholderProductOfferingPriceHandler.java
data: ('PBI:4206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/PlaceholderProductOfferingPriceHandler.java', ';', '4/26/21 18:43', ';', 'I75636c1f6816af17499153316fe456ad88da2035')
write pr: PBI:4206  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/ProductOfferingConverter.java
data: ('PBI:4206', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/ProductOfferingConverter.java', ';', '4/26/21 13:44', ';', 'Ifbcaeba8abae0880b8938ca9137db417b34df5ec')
write pr: PBI:4206  java: oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java
data: ('PBI:4206', ';', 'oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java', ';', '4/26/21 18:44', ';', 'Ib4773f701c7951e99b6ca370296735651f82d8a1')

write pr: HZ17294  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/NormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ17294  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java
data: ('HZ17294', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/valuebuilder/condition/normalizedparameter/TestNormalizedParameterTemplateValueConverter.java', ';', '5/12/21 7:52', ';', 'Ie279dce1285b30489eec2ef9144828bd74d7ddd8')
write pr: HZ18829  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/FixedPriceWithAccumulationHook.java
data: ('HZ18829', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/FixedPriceWithAccumulationHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedDocumentSpecificationProvider.java
data: ('HY99922', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedDocumentSpecificationProvider.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/customerfacingservicespecification/TestCfssSignatureValidationRule.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/customerfacingservicespecification/TestCfssSignatureValidationRule.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/customerfacingservicespecification/TestCfssSignatureValidationRule.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/customerfacingservicespecification/TestCfssSignatureValidationRule.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/TestDiscountHooksUtils.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/TestDiscountHooksUtils.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java
data: ('HY99922', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HY99922  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedDocumentSpecificationProvider.java
data: ('HY99922', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedDocumentSpecificationProvider.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HY99922  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedDocumentSpecificationProvider.java
data: ('HY99922', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedDocumentSpecificationProvider.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateConverter.java
data: ('HZ18829', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateConverter.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/HookUtils.java
data: ('HZ18829', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/HookUtils.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestDiscountPriceHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestDiscountPriceHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestRelativeDiscountHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestRelativeDiscountHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceWithAccumulationHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceWithAccumulationHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestRelativeDiscountHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestRelativeDiscountHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/HookUtils.java
data: ('HZ18829', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/HookUtils.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedDocumentSpecificationProvider.java
data: ('HY99922', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/TestLatestModifiedDocumentSpecificationProvider.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HY99922  java: integrationtest/specbrowser/src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecLocationHelper.java
data: ('HY99922', ';', 'integrationtest/specbrowser/src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecLocationHelper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HY99922  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java
data: ('HY99922', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateProvider.java
data: ('HZ18829', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateProvider.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java
data: ('HY99922', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HY99922  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java
data: ('HY99922', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/TestGenericUiEntityMapper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/TestHookUtils.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/TestHookUtils.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateConverter.java
data: ('HZ18829', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateConverter.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java
data: ('HY99922', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateProvider.java
data: ('HZ18829', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/TestFixedPriceTemplateProvider.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/TestHookUtils.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/utils/TestHookUtils.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedDocumentSpecificationProvider.java
data: ('HY99922', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/provider/LatestModifiedDocumentSpecificationProvider.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateProvider.java
data: ('HZ18829', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateProvider.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: integrationtest/specbrowser/src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecLocationHelper.java
data: ('HY99922', ';', 'integrationtest/specbrowser/src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecLocationHelper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/FixedPriceWithAccumulationHook.java
data: ('HZ18829', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/FixedPriceWithAccumulationHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceWithAccumulationHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceWithAccumulationHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HY99922  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java
data: ('HY99922', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/uientity/GenericUiEntityMapper.java', ';', '5/17/21 6:27', ';', 'I080f7c25b5c841646afd165b533314845400e19e')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestRelativeDiscountHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestRelativeDiscountHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestFixedPriceHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestDiscountPriceHook.java
data: ('HZ18829', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/actions/TestDiscountPriceHook.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateConverter.java
data: ('HZ18829', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateConverter.java', ';', '5/17/21 14:09', ';', 'Ic7f037e45a65680f5eb8f7ab660537b92d6e5331')
write pr: HZ18829  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/fixedprice/FixedPriceTemplateConverter.java

write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementRealizationItemSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementRealizationItemSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementRealizationItemSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementRealizationItemSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ26996  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/aggregatedcharges/AggregatedChargesRulePopsPageConverter.java
data: ('HZ26996', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/rule/aggregatedcharges/AggregatedChargesRulePopsPageConverter.java', ';', '7/1/21 17:08', ';', 'I5bb5854812a2ea26ba0cd0369e580c3660e4c5e8')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java
data: ('HZ29967', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29852  java: restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/ServiceRegistryCommands.java
data: ('HZ29852', ';', 'restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/ServiceRegistryCommands.java', ';', '7/22/21 16:34', ';', 'Ic595d7273694af2ac7086611f68219a5b50477b2')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java
data: ('HZ29967', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/BillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HZ25871', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/BillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29592  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationActionValidationRule.java
data: ('HZ29592', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationActionValidationRule.java', ';', '7/14/21 10:41', ';', 'I4a18741db1a9f97ef5b8f6b9db33a6526747d751')
write pr: HZ25871  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HZ25871', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ27688  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/RecurrenceRuleConverter.java
data: ('HZ27688', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/RecurrenceRuleConverter.java', ';', '6/29/21 7:21', ';', 'I51583d062fa93d99933c16788bf4024aafaa673d')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ32036  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java
data: ('HZ32036', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java', ';', '7/23/21 19:34', ';', 'I7c690fd5775f7fc9b4637e7343bdea8871c2558f')
write pr: HZ25725  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java
data: ('HZ25725', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/RecurrencePriorityListFilterer.java', ';', '6/21/21 9:57', ';', 'Ie2a780af21c7197d986141bd69e895946ed38152')
write pr: HZ28689  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestCharacteristicSetType.java
data: ('HZ28689', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestCharacteristicSetType.java', ';', '7/22/21 11:58', ';', 'Ibe21065a34b5ba06a2e553c3aea62566e916cd59')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29592  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationActionValidationRule.java
data: ('HZ29592', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationActionValidationRule.java', ';', '7/14/21 10:41', ';', 'I4a18741db1a9f97ef5b8f6b9db33a6526747d751')
write pr: HZ32036  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java
data: ('HZ32036', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichedProductOfferingHelper.java', ';', '7/23/21 19:34', ';', 'I7c690fd5775f7fc9b4637e7343bdea8871c2558f')
write pr: HZ27688  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/TestRecurrenceRuleConverter.java
data: ('HZ27688', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/TestRecurrenceRuleConverter.java', ';', '6/29/21 7:21', ';', 'I51583d062fa93d99933c16788bf4024aafaa673d')
write pr: HZ25504  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HZ25504', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '6/22/21 13:28', ';', 'I168251030015bdde2233467fca00209b77dede30')
write pr: HZ29967  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java
data: ('HZ29967', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPurposeValidationRule.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java
data: ('HZ25871', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HZ25871', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ25871  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBasPriorityListManagement.java
data: ('HZ25871', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/TestBasPriorityListManagement.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDuplicatePageQueryImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ28689  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestCharacteristicSetType.java
data: ('HZ28689', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestCharacteristicSetType.java', ';', '7/22/21 11:58', ';', 'Ibe21065a34b5ba06a2e553c3aea62566e916cd59')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HZ29967', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageProvider.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageProvider.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29081  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationMustAddValueValidationRule.java
data: ('HZ29081', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationMustAddValueValidationRule.java', ';', '7/8/21 15:03', ';', 'I1e15b15c6dd0e076bdb065b7c38bc267a6d101d4')
write pr: HZ25504  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestAggregatedChargesPriorityListFilterer.java
data: ('HZ25504', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestAggregatedChargesPriorityListFilterer.java', ';', '6/22/21 11:49', ';', 'I06a8594877aacf61d9c93ac4ee799ecd2370e930')
write pr: HZ29081  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java
data: ('HZ29081', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java', ';', '7/8/21 15:03', ';', 'I1e15b15c6dd0e076bdb065b7c38bc267a6d101d4')
write pr: HZ25871  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HZ25871', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ26349  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/LifecycleBaseTransitionRules.java
data: ('HZ26349', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/LifecycleBaseTransitionRules.java', ';', '6/25/21 16:41', ';', 'I6ee04736ecddfdeac32f599c7c3bd8d736626f90')
write pr: HZ25504  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestAggregatedChargesPriorityListFilterer.java
data: ('HZ25504', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestAggregatedChargesPriorityListFilterer.java', ';', '6/22/21 11:49', ';', 'I06a8594877aacf61d9c93ac4ee799ecd2370e930')
write pr: HZ25504  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HZ25504', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '6/22/21 13:28', ';', 'I168251030015bdde2233467fca00209b77dede30')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/EnrichmentHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestFillPageQueryImpl.java

write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContractHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContractHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29592  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationActionValidationRule.java
data: ('HZ29592', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/lifecyclespecification/TestLifecycleSpecificationActionValidationRule.java', ';', '7/14/21 10:41', ';', 'I4a18741db1a9f97ef5b8f6b9db33a6526747d751')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java
data: ('HZ25871', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/billingaccountspecification/TestBillingAccountSpecificationAllRelatedBucketMustBeInBucketPriorityList.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichmentHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestContactMediumAssociationHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestContactMediumAssociationHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ27688  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/RecurrenceRuleConverter.java
data: ('HZ27688', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/RecurrenceRuleConverter.java', ';', '6/29/21 7:21', ';', 'I51583d062fa93d99933c16788bf4024aafaa673d')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestContractHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestContractHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HZ25871', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestCreatePageTransactionImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestCreatePageTransactionImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageProvider.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageProvider.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageToEntityMapper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageToEntityMapper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ28689  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/userdefinedconditions/UserDefinedConditionsExtractor.java
data: ('HZ28689', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/userdefinedconditions/UserDefinedConditionsExtractor.java', ';', '7/22/21 11:58', ';', 'Ibe21065a34b5ba06a2e553c3aea62566e916cd59')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestAbstractPageTransaction.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/BillingAccountSpecificationValidationRuleProvider.java
data: ('HZ25871', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/BillingAccountSpecificationValidationRuleProvider.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/ContactMediumAssociationHelper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestDeletePageTransactionImpl.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ32036  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java
data: ('HZ32036', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java', ';', '7/23/21 19:34', ';', 'I7c690fd5775f7fc9b4637e7343bdea8871c2558f')
write pr: HZ29967  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/CharacteristicUtils.java
data: ('HZ29967', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/CharacteristicUtils.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ27688  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/RecurrenceRuleConverter.java
data: ('HZ27688', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/RecurrenceRuleConverter.java', ';', '6/29/21 7:21', ';', 'I51583d062fa93d99933c16788bf4024aafaa673d')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageProvider.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageProvider.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ25871  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/BillingAccountSpecificationValidationRuleProvider.java
data: ('HZ25871', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/BillingAccountSpecificationValidationRuleProvider.java', ';', '7/8/21 17:02', ';', 'Iae901f5c42075cc1263af6391b9fb0a2d9909d86')
write pr: HY84047  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationOverrideNesValidationRule.java
data: ('HY84047', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationOverrideNesValidationRule.java', ';', '3/2/21 11:19', ';', 'I3c8e5abc751d0162a50263c5834b6c9576ac28c9')
write pr: HZ26349  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecificationProvider.java
data: ('HZ26349', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecificationProvider.java', ';', '6/25/21 16:41', ';', 'I6ee04736ecddfdeac32f599c7c3bd8d736626f90')
write pr: HZ29967  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageProvider.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/TestAgreementSpecificationPageProvider.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ26349  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecificationProvider.java
data: ('HZ26349', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedLifecycleSpecificationProvider.java', ';', '6/25/21 16:41', ';', 'I6ee04736ecddfdeac32f599c7c3bd8d736626f90')
write pr: HZ29967  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HZ29967', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageToEntityMapper.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageToEntityMapper.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ29967  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java
data: ('HZ29967', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementRealizationItemSpecificationPageConverter.java', ';', '7/21/21 9:34', ';', 'Ie19877ea5c39f8d685b7be780e6145aead05b733')
write pr: HZ34011  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java
data: ('HZ34011', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java', ';', '8/10/21 13:14', ';', 'Ieb7e16c72584f0c29abc694b45988106b0ebea5c')
write pr: HZ34109  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HZ34109', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '8/6/21 14:33', ';', 'I82d37fb83e4f4a408c63994f405011c0b2db9661')
write pr: HZ34011  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HZ34011', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '8/10/21 13:14', ';', 'Ieb7e16c72584f0c29abc694b45988106b0ebea5c')
write pr: HZ34942  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34942', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java', ';', '8/13/21 6:17', ';', 'Ie548f9101ebc91f714fb192b0c57986891563b10')
write pr: HZ34109  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java
data: ('HZ34109', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java', ';', '8/6/21 14:33', ';', 'I82d37fb83e4f4a408c63994f405011c0b2db9661')
write pr: HZ34942  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/billingcyclespecification/TestOffsetsHelper.java
data: ('HZ34942', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/billingcyclespecification/TestOffsetsHelper.java', ';', '8/13/21 6:17', ';', 'Ie548f9101ebc91f714fb192b0c57986891563b10')
write pr: HZ36369  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/customerfacingservicespecification/CustomerFacingServiceSpecificationListEntry.java
data: ('HZ36369', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/customerfacingservicespecification/CustomerFacingServiceSpecificationListEntry.java', ';', '8/27/21 7:29', ';', 'Idfac37940e93be4c05a6fa02609a693f583dddcb')
write pr: HZ34011  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HZ34011', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '8/10/21 13:14', ';', 'Ieb7e16c72584f0c29abc694b45988106b0ebea5c')
write pr: HZ32685  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java
data: ('HZ32685', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/TestContractSpecificationPageConverter.java', ';', '7/30/21 12:52', ';', 'I5a08733d7c5dc8e4a122fea6caf59c35f6ab7af3')
write pr: HZ34109  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HZ34109', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '8/6/21 14:33', ';', 'I82d37fb83e4f4a408c63994f405011c0b2db9661')
write pr: HZ32685  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/contractspecification/ContractSpecificationPageConverter.java

write pr: HZ38198  java: oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/service/RmcaAlarm.java
data: ('HZ38198', ';', 'oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/service/RmcaAlarm.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/service/RmcaAlarm.java
data: ('HZ38198', ';', 'oamservices/fm/src/main/java/com/ericsson/bss/rmca/oamservices/fm/service/RmcaAlarm.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/InvoicingViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/InvoicingViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/service/TestRmcaAlarm.java
data: ('HZ38198', ';', 'oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/service/TestRmcaAlarm.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/invproxy/TestInvoicingViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ40381  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java
data: ('HZ40381', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ38198  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/TestCpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ40381  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HZ40381', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ40381  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationMustAddValueValidationRule.java
data: ('HZ40381', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/ProductSpecificationMustAddValueValidationRule.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ40381  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HZ40381', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ38198  java: oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/service/TestRmcaAlarm.java
data: ('HZ38198', ';', 'oamservices/fm/src/test/java/com/ericsson/bss/rmca/oamservices/fm/service/TestRmcaAlarm.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ40381  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HZ40381', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ38198  java: restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java
data: ('HZ38198', ';', 'restproxy/impl/src/main/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/CpmViewImpl.java', ';', '9/13/21 13:22', ';', 'If4df5cbf38056aa9ad48e5db188a55e25fe72cc9')
write pr: HZ40381  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java
data: ('HZ40381', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ40381  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java
data: ('HZ40381', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/productspecification/TestProductSpecificationMustAddValueValidationRule.java', ';', '9/14/21 14:39', ';', 'I339705ed33f7183cf9554b996c511a72788ac013')
write pr: HZ34946  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java
data: ('HZ34946', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestBillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestBillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestBillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestBillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java
data: ('HZ34946', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/BillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java
data: ('HZ34946', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/testdata/DefaultTestDataCreator.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ34946  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestBillingCycleSpecificationCharacteristicValidationRule.java
data: ('HZ34946', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestBillingCycleSpecificationCharacteristicValidationRule.java', ';', '9/15/21 15:04', ';', 'I95870c9156a1a20725803696dfa5f07739fff555')
write pr: HZ41407  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestRelaxCharacteristicModificationInVersionRule.java
data: ('HZ41407', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestRelaxCharacteristicModificationInVersionRule.java', ';', '9/17/21 11:44', ';', 'I899aa305e64b05d14fc0ebe638f00545d85b5193')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ43872', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/1/21 17:37', ';', 'I23c26dfac5c54c8bb4ac32b7a6c949d2323a74fa')
write pr: HZ43872  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java

data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/TestBundleOnlyPredicate.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListFiltererDataMigration.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListFiltererDataMigration.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/BundleOnlyPredicate.java
data: ('HZ43719', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/BundleOnlyPredicate.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/BundleOnlyPredicate.java
data: ('HZ43719', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/BundleOnlyPredicate.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListUpdateHelper.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListUpdateHelper.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/TestBundleOnlyPredicate.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/TestBundleOnlyPredicate.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestRecurrencePriorityListUpdater.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestRecurrencePriorityListUpdater.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestAggregatedChargesPriorityListUpdater.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestAggregatedChargesPriorityListUpdater.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListFiltererDataMigration.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/RecurrencePriorityListFiltererDataMigration.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestAggregatedChargesPriorityListUpdater.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestAggregatedChargesPriorityListUpdater.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestAggregatedChargesPriorityListUpdater.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestAggregatedChargesPriorityListUpdater.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/RecurrencePriorityListUpdater.java
data: ('HZ43719', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/RecurrencePriorityListUpdater.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListUpdateHelper.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListUpdateHelper.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestRecurrencePriorityListFilterer.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/TestBundleOnlyPredicate.java
data: ('HZ43719', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/common/TestBundleOnlyPredicate.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java
data: ('HZ43719', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestRecurrencePriorityListFiltererDataMigration.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ43719  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/AggregatedChargesPriorityListUpdater.java
data: ('HZ43719', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/AggregatedChargesPriorityListUpdater.java', ';', '10/4/21 6:41', ';', 'Iafc41a17a742347f1442621a4812217e380e325b')
write pr: HZ33722  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/PartyRoleFilter.java
data: ('HZ33722', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/PartyRoleFilter.java', ';', '8/5/21 11:27', ';', 'Ib04201d7aef50ed876aee20b5faf95c04c7b47fb')
write pr: HZ33722  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestPartyRoleFilter.java
data: ('HZ33722', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/TestPartyRoleFilter.java', ';', '8/5/21 11:27', ';', 'Ib04201d7aef50ed876aee20b5faf95c04c7b47fb')
write pr: HZ41188  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListUpdateHelper.java
data: ('HZ41188', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/TestPriorityListUpdateHelper.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestAggregatedChargesPriorityListFilterer.java
data: ('HZ41188', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestAggregatedChargesPriorityListFilterer.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agregatedchargesprioritylist/TestAggregatedChargesBucketProvider.java
data: ('HZ41188', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agregatedchargesprioritylist/TestAggregatedChargesBucketProvider.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/AggregatedChargesPriorityListFilterer.java
data: ('HZ41188', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/AggregatedChargesPriorityListFilterer.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HZ41188', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/datamigration/AggregateChargesPriorityListDataMigration.java
data: ('HZ41188', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/datamigration/AggregateChargesPriorityListDataMigration.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/AggregatedChargesPriorityListFilterer.java
data: ('HZ41188', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/AggregatedChargesPriorityListFilterer.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/event/TestAggregatedChargesPriorityListManagement_ITCase.java
data: ('HZ41188', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/event/TestAggregatedChargesPriorityListManagement_ITCase.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agregatedchargesprioritylist/TestAggregatedChargesPriorityListConverter.java
data: ('HZ41188', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agregatedchargesprioritylist/TestAggregatedChargesPriorityListConverter.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/GlobalPriorityListImporter.java
data: ('HZ41188', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/prioritylistmanagement/GlobalPriorityListImporter.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/AggregatedChargesPriorityListFilterer.java
data: ('HZ41188', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/AggregatedChargesPriorityListFilterer.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/AggregateChargesRankingEntryUpdater.java
data: ('HZ41188', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/AggregateChargesRankingEntryUpdater.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/TestAggregatedChargesPriorityListSorter.java
data: ('HZ41188', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/TestAggregatedChargesPriorityListSorter.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/AggregatedChargesPriorityListMerger.java
data: ('HZ41188', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/AggregatedChargesPriorityListMerger.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java
data: ('HZ41188', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestDataImportPriorityLists.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HZ41188', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestAggregateChargesPriorityListDataMigrationImpl.java
data: ('HZ41188', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/TestAggregateChargesPriorityListDataMigrationImpl.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGlobalPriorityListDataMigrationPredicate.java
data: ('HZ41188', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/TestGlobalPriorityListDataMigrationPredicate.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/AbstractDataImportTest.java
data: ('HZ41188', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/AbstractDataImportTest.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java
data: ('HZ41188', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/datamigration/DataMigrationScheduler.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java
data: ('HZ41188', ';', 'importexport/impl/src/main/java/com/ericsson/bss/rmca/importexport/impl/ServiceConfig.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java
data: ('HZ41188', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/updater/PriorityListUpdateHelper.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/AbstractDataImportTest.java
data: ('HZ41188', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/AbstractDataImportTest.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agregatedchargesprioritylist/TestAggregatedChargesSpecificationsProvider.java
data: ('HZ41188', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agregatedchargesprioritylist/TestAggregatedChargesSpecificationsProvider.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java
data: ('HZ41188', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/importexport/TestImportExport_UseCase.java', ';', '10/14/21 19:58', ';', 'Ib86e8fcddac551d564acffcc742e806cacffe8b1')
write pr: HZ41188  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/merging/AggregatedChargesPriorityListMerger.java

write pr: HZ47224  java: oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java
data: ('HZ47224', ';', 'oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java', ';', '10/27/21 14:00', ';', 'I76d79c3bacc4a8107812f4c2bbe2c0394f39c3cd')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47224  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HZ47224', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '10/27/21 14:00', ';', 'I76d79c3bacc4a8107812f4c2bbe2c0394f39c3cd')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationContext.java
data: ('HZ47803', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationContext.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/main/java/com/ericsson/bss/rmca/restproxy/listener/ForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/main/java/com/ericsson/bss/rmca/restproxy/listener/ForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47224  java: oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java
data: ('HZ47224', ';', 'oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java', ';', '10/27/21 14:00', ';', 'I76d79c3bacc4a8107812f4c2bbe2c0394f39c3cd')
write pr: HZ47803  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java
data: ('HZ47803', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ47224  java: oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java
data: ('HZ47224', ';', 'oamservices/fcimpl/src/test/java/com/ericsson/bss/rmca/oamservices/fcimpl/functiondefinition/TestRmcaFunctionDefinition.java', ';', '10/27/21 14:00', ';', 'I76d79c3bacc4a8107812f4c2bbe2c0394f39c3cd')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/main/java/com/ericsson/bss/rmca/restproxy/listener/ForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/main/java/com/ericsson/bss/rmca/restproxy/listener/ForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ47803  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java
data: ('HZ47803', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/main/java/com/ericsson/bss/rmca/restproxy/listener/ForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/main/java/com/ericsson/bss/rmca/restproxy/listener/ForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47224  java: oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java
data: ('HZ47224', ';', 'oamservices/fc/src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', '10/27/21 14:00', ';', 'I76d79c3bacc4a8107812f4c2bbe2c0394f39c3cd')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/PriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java
data: ('HZ47803', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java
data: ('HZ47803', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/ProductOfferingVersionResolver.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/agreementrealizationspecification/TestPriceEnrichmentValidationRule.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/TestThatValidationRulesAreStateless.java
data: ('HZ47803', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/TestThatValidationRulesAreStateless.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java
data: ('HZ47803', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationContext.java
data: ('HZ47803', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationContext.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ47803  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java
data: ('HZ47803', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/ValidationHandlerImpl.java', ';', '10/27/21 5:39', ';', 'If70bd0d11bdee9587c52a4a0d12ba94dd31268a2')
write pr: HZ48014  java: restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ48014  java: restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java
data: ('HZ48014', ';', 'restproxy/listener/src/test/java/com/ericsson/bss/rmca/restproxy/listener/TestForeignDataConsistencyDeactivationTask.java', ';', '10/27/21 18:57', ';', 'Ib07694166c9a916ce70a37c02e8ffa3ba0d93d2d')
write pr: HZ48547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/TestAggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')
write pr: HZ48547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java
data: ('HZ48547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/packages/aggregatedcharges/AggregatedChargesConditionTemplateCompiler.java', ';', '11/5/21 14:29', ';', 'I28718619297d8073686e4af6ee20565eea2b24e7')

write pr: HX40662  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestProductSpecificationImpl.java
data: ('HX40662', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestProductSpecificationImpl.java', ';', '12/19/18 13:55', ';', 'I45ca8ab3c5eda5021d6665a1c80be8e33e954244')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ApopsCarryOverValidationRule.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ApopsCarryOverValidationRule.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX40491  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/TestNetworkPolicyCounterPageConverter.java
data: ('HX40491', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/TestNetworkPolicyCounterPageConverter.java', ';', '12/21/18 13:53', ';', 'Ifb80c5f5d11e993e2683413bd3c1bcf2f2a687ca')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/PsValidationRuleProvider.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/PsValidationRuleProvider.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX36776  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierMetadataHelper.java
data: ('HX36776', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierMetadataHelper.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX39881  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX39881', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '12/20/18 12:10', ';', 'I4b917b709d808c43b17111dbb9545c75c0489b57')
write pr: HX37893  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/TestBucketThresholdRule.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/TestBucketThresholdRule.java', ';', '12/10/18 9:24', ';', 'Ie1fbc01366235544638954ff25682b4f091478a1')
write pr: HX37893  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/BucketThresholdRule.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/BucketThresholdRule.java', ';', '12/10/18 9:24', ';', 'Ie1fbc01366235544638954ff25682b4f091478a1')
write pr: HX35355  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java
data: ('HX35355', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java', ';', '12/21/18 9:24', ';', 'I802aaa7663b019107e3cb68ca37fb56c90a4fbf7')
write pr: HX36776  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX36776', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX37893  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/AbstractRestInternalTest.java', ';', '12/10/18 9:24', ';', 'Ie1fbc01366235544638954ff25682b4f091478a1')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productoffering/ApopsCarryOverValidationRule.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productoffering/ApopsCarryOverValidationRule.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductOfferingValidationRuleProvider.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductOfferingValidationRuleProvider.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX36776  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productoffering/TestApopsCarryOverValidationRule.java
data: ('HX36776', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productoffering/TestApopsCarryOverValidationRule.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX37893  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/BucketThresholdRule.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/BucketThresholdRule.java', ';', '12/12/18 13:32', ';', 'Ia1c19160b7e6b4181fbf7df7e4824100467d19fa')
write pr: HX35383  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java
data: ('HX35383', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java', ';', '12/3/18 8:24', ';', 'Iaa1f43d98c7168753d17091ff21ed82f8d168762')
write pr: HX37893  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/AbstractBucketPageConverter.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/AbstractBucketPageConverter.java', ';', '12/12/18 13:32', ';', 'Ia1c19160b7e6b4181fbf7df7e4824100467d19fa')
write pr: HX35537  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/CatalogManagementApi.java
data: ('HX35537', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/CatalogManagementApi.java', ';', '11/29/18 12:46', ';', 'I76a3cb536b764cc690b7dc097e36e4114344f5b7')
write pr: HX39442  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/billingaccount/TestBillingAccountBucketPageConverter.java
data: ('HX39442', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/billingaccount/TestBillingAccountBucketPageConverter.java', ';', '12/13/18 10:14', ';', 'I773ed30b927199f6ea662ee7b4d3b13b24bc5821')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/PsValidationRuleProvider.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/PsValidationRuleProvider.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX37893  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/BucketThresholdRuleListBuilder.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/BucketThresholdRuleListBuilder.java', ';', '12/10/18 9:24', ';', 'Ie1fbc01366235544638954ff25682b4f091478a1')
write pr: HX35337  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierHelper.java
data: ('HX35337', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierHelper.java', ';', '11/29/18 6:47', ';', 'I0128ff71aca96b8dc58bbc248f6e90ec38f19034')
write pr: HX40995  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/NonRecurrentCarryOverAllowedOnlyForPercentageCarryOver.java
data: ('HX40995', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/NonRecurrentCarryOverAllowedOnlyForPercentageCarryOver.java', ';', '12/21/18 10:43', ';', 'If23abaf64bb7878ad4b0796aa9d53f28c91a6b46')
write pr: HX36776  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productspecification/TestProductSpecificationCarryOverValidationRule.java
data: ('HX36776', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productspecification/TestProductSpecificationCarryOverValidationRule.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX35337  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java
data: ('HX35337', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java', ';', '11/29/18 6:47', ';', 'I0128ff71aca96b8dc58bbc248f6e90ec38f19034')
write pr: HX39881  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/ThresholdWithinBoundsValidationRule.java
data: ('HX39881', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/ThresholdWithinBoundsValidationRule.java', ';', '12/20/18 12:10', ';', 'I4b917b709d808c43b17111dbb9545c75c0489b57')
write pr: HX36776  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX36776', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX35355  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/utils/TestHookUtils.java
data: ('HX35355', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/utils/TestHookUtils.java', ';', '12/21/18 9:24', ';', 'I802aaa7663b019107e3cb68ca37fb56c90a4fbf7')
write pr: HX35337  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java
data: ('HX35337', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java', ';', '11/29/18 6:47', ';', 'I0128ff71aca96b8dc58bbc248f6e90ec38f19034')
write pr: HX36377  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleStateValidationRule.java
data: ('HX36377', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleStateValidationRule.java', ';', '12/3/18 9:53', ';', 'I15f33dd4390d1719884d1368b38abd09fb6ed54e')
write pr: HX40662  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestProductSpecificationImpl.java
data: ('HX40662', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestProductSpecificationImpl.java', ';', '12/19/18 13:55', ';', 'I45ca8ab3c5eda5021d6665a1c80be8e33e954244')
write pr: HX36698  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java
data: ('HX36698', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java', ';', '12/6/18 15:22', ';', 'Ibe22867306854bc126d131fcb6e86e601051fa2a')
write pr: HX39442  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/AbstractBucketPageConverter.java
data: ('HX39442', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/AbstractBucketPageConverter.java', ';', '12/13/18 10:14', ';', 'I773ed30b927199f6ea662ee7b4d3b13b24bc5821')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX36776  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java
data: ('HX36776', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX40963  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/preset/conditionconverter/global/TestManualRecurrenceTrigger.java
data: ('HX40963', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/preset/conditionconverter/global/TestManualRecurrenceTrigger.java', ';', '12/20/18 13:53', ';', 'I5963b207c52401ffbfe5d5777290ead0157c95f3')
write pr: HX39881  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX39881', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '12/20/18 12:10', ';', 'I4b917b709d808c43b17111dbb9545c75c0489b57')
write pr: HX36776  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX36776', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX39442  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/billingaccount/TestBillingAccountBucketPageConverter.java
data: ('HX39442', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/billingaccount/TestBillingAccountBucketPageConverter.java', ';', '12/13/18 10:14', ';', 'I773ed30b927199f6ea662ee7b4d3b13b24bc5821')
write pr: HX36776  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX36776', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX35337  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java
data: ('HX35337', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java', ';', '11/29/18 6:47', ';', 'I0128ff71aca96b8dc58bbc248f6e90ec38f19034')
write pr: HX39922  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ChargingCapabilityViewImpl.java
data: ('HX39922', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ChargingCapabilityViewImpl.java', ';', '12/17/18 11:25', ';', 'I58ee1f00191397c1d944603c9b3702c404c4270a')
write pr: HX36776  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierMetadataHelper.java
data: ('HX36776', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierMetadataHelper.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX36776  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java
data: ('HX36776', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/TestPossibleActionModifierMetadataHelper.java', ';', '12/10/18 15:46', ';', 'I8e11ee522c649791f45335fd49ad4bc281694421')
write pr: HX37893  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/ThresholdSpecificationListBuilder.java
data: ('HX37893', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/bucket/ThresholdSpecificationListBuilder.java', ';', '12/10/18 9:24', ';', 'Ie1fbc01366235544638954ff25682b4f091478a1')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ApopsCarryOverValidationRule.java
data: ('HX36776', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ApopsCarryOverValidationRule.java', ';', '12/12/18 11:42', ';', 'I2d5d06cba56fb1ad810b9195db16e7aee7978dc9')
write pr: HX37893  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/BucketSpecificationSignatureValidationRule.java
data: ('HX37893', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/BucketSpecificationSignatureValidationRule.java', ';', '12/10/18 9:24', ';', 'Ie1fbc01366235544638954ff25682b4f091478a1')
write pr: HX36776  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productspecification/ProductSpecificationCarryOverValidationRule.java

data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestEntityDecorator.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestEntityDecorator.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX33706  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/CharacteristicSensitiveInfoFieldsValidationRule.java
data: ('HX33706', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/CharacteristicSensitiveInfoFieldsValidationRule.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HX31479  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java
data: ('HX31479', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/ScheduleDefinitionDecorationProvider.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/ScheduleDefinitionDecorationProvider.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/AbstractEntityTest.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/AbstractEntityTest.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AbstractVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AbstractVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/DecoratorFactoryImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/DecoratorFactoryImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33706  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/CharacteristicSensitiveInfoFieldsValidationRule.java
data: ('HX33706', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/CharacteristicSensitiveInfoFieldsValidationRule.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX21028  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java
data: ('HX21028', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX28161  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/generallogicalspecification/TestGeneralLogicalSpecificationPageConverter.java
data: ('HX28161', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/generallogicalspecification/TestGeneralLogicalSpecificationPageConverter.java', ';', '10/19/18 10:59', ';', 'Id3c97fda38f8af8a52a676b1936b36985c69f0f7')
write pr: HX19843  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/CommunityMembershipHook.java
data: ('HX19843', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/CommunityMembershipHook.java', ';', '9/12/18 13:24', ';', 'Ib99322642cac28684254a54559ffb46f1bbf79e3')
write pr: HX21056  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestProductOfferingLifeCycleNotificationsValidationRule.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestProductOfferingLifeCycleNotificationsValidationRule.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX21028  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX33998  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java
data: ('HX33998', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/BillingAccountSpecificationToPageConverter.java', ';', '11/16/18 15:06', ';', 'I76d67cc9b1e97debef8a97ff561180832aafd0e8')
write pr: HX32771  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/physicalresourcespecification/TestPhysicalResourceSpecificationPage.java
data: ('HX32771', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/physicalresourcespecification/TestPhysicalResourceSpecificationPage.java', ';', '11/20/18 12:22', ';', 'I24ca6b01118e1ba6e1295d00539e70aa02420696')
write pr: HX12080  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntities.java
data: ('HX12080', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntities.java', ';', '8/7/18 11:09', ';', 'I6c459763d261e8edd17c18a03a862eed63a2636a')
write pr: HX33974  java: integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/NotificationTemplateStubView.java
data: ('HX33974', ';', 'integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/NotificationTemplateStubView.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX20786  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/resources/pbs/ProductBucketSpecificationPage.java
data: ('HX20786', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/resources/pbs/ProductBucketSpecificationPage.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX18238  java: examples/src/test/java/com/ericsson/bss/rmca/examples/TestRmcaServicesFactory.java
data: ('HX18238', ';', 'examples/src/test/java/com/ericsson/bss/rmca/examples/TestRmcaServicesFactory.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX21056  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX10271  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/TestScenarioTriggeredRuleValidation.java
data: ('HX10271', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/TestScenarioTriggeredRuleValidation.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX30279  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ExportTaskImpl.java
data: ('HX30279', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ExportTaskImpl.java', ';', '10/30/18 7:48', ';', 'If21c4a2830d4ee3083fd231d88280fea1d23fc24')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntities.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntities.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX24580  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/Rmref.java
data: ('HX24580', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/Rmref.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX30393  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestProductSpecificationLifecycleTypeValidationRule.java
data: ('HX30393', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestProductSpecificationLifecycleTypeValidationRule.java', ';', '10/30/18 12:05', ';', 'I22a3c1a5298f05d608176777246b1dc1541baeb7')
write pr: HX20770  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX20770', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '10/9/18 9:17', ';', 'Ifd1a6013e2122d2439df8ad80b8da420391a7d70')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ScenarioTriggered.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ScenarioTriggered.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX31479  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java
data: ('HX31479', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: BSUC:FT8-96  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/RemoveLockAnnotationImportProcessor.java
data: ('BSUC:FT8-96', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/RemoveLockAnnotationImportProcessor.java', ';', '11/26/18 11:00', ';', 'I89f8420156f7d744aa68ad2049395f8bf02d1956')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productspecification/PsMustHavePbsIfRelatedBucketRefCharsAreFound.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/productspecification/PsMustHavePbsIfRelatedBucketRefCharsAreFound.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AbstractVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AbstractVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX21028  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/PsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX27740  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyBucketSpec.java
data: ('HX27740', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyBucketSpec.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX17537  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java
data: ('HX17537', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java', ';', '8/31/18 9:08', ';', 'I3a912b4821ab9191df60483f51e3de3021c46915')
write pr: HX27740  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/helpers/recurrenceprioritylist/RecurrencePriorityListPageHelper.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/helpers/recurrenceprioritylist/RecurrencePriorityListPageHelper.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX16411  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java
data: ('HX16411', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java', ';', '8/27/18 9:50', ';', 'Ifb96107b78481cb6844c987cc46f916fc8b83352')
write pr: HX21028  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX14183  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java
data: ('HX14183', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java', ';', '10/9/18 13:50', ';', 'I06fb0a967b35bbba80711bf6293de8108a31fab5')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPriceSpecificationVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPriceSpecificationVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductOfferingValidationRuleProvider.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductOfferingValidationRuleProvider.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPrice.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPrice.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HW76061  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HW76061', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPrice.java

write pr: HX19899  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestHeaderValidator.java
data: ('HX19899', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/RequestHeaderValidator.java', ';', '9/12/18 18:44', ';', 'Ie373f54b2e1db29890fdaf68809e711daad69e44')
write pr: HX33655  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/SlimCampaign.java
data: ('HX33655', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/SlimCampaign.java', ';', '11/15/18 13:08', ';', 'Id6e7962f2cfd89225f144ec694904cbdda71a79f')
write pr: HX21028  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX21028  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX33974  java: examples/src/main/java/com/ericsson/bss/rmca/examples/NotificationTemplateViewStub.java
data: ('HX33974', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/NotificationTemplateViewStub.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBusinessSystemConfigurationProvider.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBusinessSystemConfigurationProvider.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPriceSpecificationVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPriceSpecificationVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX21056  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX20786  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/resources/babs/TestBillingAccountBucketSpecificationPage.java
data: ('HX20786', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/resources/babs/TestBillingAccountBucketSpecificationPage.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestFunctionControl_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestFunctionControl_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HW94055  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/TestScenarioTriggered.java
data: ('HW94055', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/TestScenarioTriggered.java', ';', '8/24/18 7:15', ';', 'Iaf1a706996929b14af8e6b45a2846d208e68f916')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateTransactionImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateTransactionImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX27740  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java
data: ('HX27740', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX25348  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/bsc/TestBusinessSystemConfiguration_ITCase.java
data: ('HX25348', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/bsc/TestBusinessSystemConfiguration_ITCase.java', ';', '10/11/18 8:53', ';', 'I2a5fd208434c54bceff9397785b3f376c6a0309a')
write pr: HX21056  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestConfigurationDataImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestConfigurationDataImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductOfferingValidationRuleProvider.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductOfferingValidationRuleProvider.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestExportTaskImpl.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestExportTaskImpl.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX27397  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HX27397', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '10/18/18 5:56', ';', 'Ie4b41612ed39e4243c7bebdf78d71521a6a5ba43')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/AbstractEntityTest.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/AbstractEntityTest.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX36034  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestRestPageImpl.java
data: ('HX36034', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageservice/TestRestPageImpl.java', ';', '11/27/18 9:12', ';', 'I7581be4045a2c6ab531762efcbc32f47d87b35df')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/migration/TestScheduleDefinitionDataMigration_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/migration/TestScheduleDefinitionDataMigration_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX13306  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java
data: ('HX13306', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java', ';', '8/8/18 8:52', ';', 'I333eb2ba5f74390ab363e4281cea9568467e3e44')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPrice.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPrice.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestActiveFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/ActiveFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/ActiveFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/EntityAccessWrapper.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/EntityAccessWrapper.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX31479  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestTranslationBuilder.java
data: ('HX31479', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestTranslationBuilder.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX17537  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java
data: ('HX17537', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestConditionType.java', ';', '8/31/18 9:08', ';', 'I3a912b4821ab9191df60483f51e3de3021c46915')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX29089  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/ProductSpecificationTranslateCharacteristicValidationRule.java
data: ('HX29089', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/ProductSpecificationTranslateCharacteristicValidationRule.java', ';', '10/30/18 13:47', ';', 'Id31df18370f4153bee1657435f32cd9b4c61d43e')
write pr: HX27740  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/UsedBy.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/UsedBy.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX19843  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/CommunityMembershipHook.java
data: ('HX19843', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/CommunityMembershipHook.java', ';', '9/12/18 13:24', ';', 'Ib99322642cac28684254a54559ffb46f1bbf79e3')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestPsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestPsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX30393  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestBlockingValidationError.java
data: ('HX30393', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestBlockingValidationError.java', ';', '10/30/18 12:05', ';', 'I22a3c1a5298f05d608176777246b1dc1541baeb7')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllExceptionAreListedInSpecificationLevelSignatureRule.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllExceptionAreListedInSpecificationLevelSignatureRule.java', ';', '11/16/18 8:16', ';', 'Ic4393d24b8a2f00b9ea43badb7dd7f4c7040451a')
write pr: HX25348  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/baseconfiguration/TestBaseConfiguration_ITCase.java
data: ('HX25348', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/baseconfiguration/TestBaseConfiguration_ITCase.java', ';', '10/11/18 8:53', ';', 'I2a5fd208434c54bceff9397785b3f376c6a0309a')
write pr: HX10271  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierMetadataHelper.java
data: ('HX10271', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/pop/helpers/PossibleActionModifierMetadataHelper.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX24614  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX24614', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX33706  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX33706', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HX20786  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/testdata/BillingAccountBucketResourceSpecificationBuilder.java
data: ('HX20786', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/testdata/BillingAccountBucketResourceSpecificationBuilder.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX21524  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/TestRemoveLockAnnotationImportProcessor.java
data: ('HX21524', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/TestRemoveLockAnnotationImportProcessor.java', ';', '10/9/18 7:51', ';', 'I239f8050848efc66bff9097a293ae0e3cc40dc3b')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogManagement/TestCatalogManagement_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogManagement/TestCatalogManagement_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX29089  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HX29089', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '10/30/18 13:47', ';', 'Id31df18370f4153bee1657435f32cd9b4c61d43e')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineWrapperFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineWrapperFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX21028  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java
data: ('HX21028', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRecurrence.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRecurrence.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX23286  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/helpers/recurrenceprioritylist/RecurrencePriorityListPageHelper.java

write pr: HX27740  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/TestNetworkPolicyCounterPageConverter.java
data: ('HX27740', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/TestNetworkPolicyCounterPageConverter.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPrice.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPrice.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/common/CompiledOption.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/common/CompiledOption.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestDisallowSharedBucketInConditionValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestDisallowSharedBucketInConditionValidationRule.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java', ';', '9/23/18 7:43', ';', 'Icb5ccc2293009bae0aeec96bc171b4d5289d7164')
write pr: HX33974  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/NotificationTemplateViewImpl.java
data: ('HX33974', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/NotificationTemplateViewImpl.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX24614  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX24614', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX21056  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/RuleContext.java
data: ('HX21056', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/RuleContext.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryImpl.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX10271  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX10271', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX31479  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestTranslationBuilder.java
data: ('HX31479', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestTranslationBuilder.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX21209  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ConsumedServiceUnavailableException.java
data: ('HX21209', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ConsumedServiceUnavailableException.java', ';', '9/28/18 12:36', ';', 'I9ae1de55338f306564649be0784d1541fa2cf4c7')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllSpecificationsHaveSpecificationLevelSignatureRuleRegistered.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllSpecificationsHaveSpecificationLevelSignatureRuleRegistered.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX20786  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/BucketHelper.java
data: ('HX20786', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/BucketHelper.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX13089  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/TestEntityAccessHelper.java
data: ('HX13089', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/TestEntityAccessHelper.java', ';', '8/7/18 13:56', ';', 'Iaa614ca2bc96c12a33760840bf4f0e11f890232b')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductCharge.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductCharge.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX33974  java: examples/src/main/java/com/ericsson/bss/rmca/examples/NotificationTemplateViewStub.java
data: ('HX33974', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/NotificationTemplateViewStub.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX27740  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java
data: ('HX27740', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterPageConverter.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX21028  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ExceptionFactory.java
data: ('HX21028', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ExceptionFactory.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX33655  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestSlimCampaign.java
data: ('HX33655', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestSlimCampaign.java', ';', '11/15/18 13:08', ';', 'Id6e7962f2cfd89225f144ec694904cbdda71a79f')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX10271  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/TestXmlHelper.java
data: ('HX10271', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/TestXmlHelper.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX27397  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java
data: ('HX27397', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Purpose.java', ';', '10/18/18 5:56', ';', 'Ie4b41612ed39e4243c7bebdf78d71521a6a5ba43')
write pr: HX33974  java: integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/NotificationTemplateStubView.java
data: ('HX33974', ';', 'integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/NotificationTemplateStubView.java', ';', '11/16/18 8:16', ';', 'Ic4393d24b8a2f00b9ea43badb7dd7f4c7040451a')
write pr: HX28483  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestCatalogManagementApi.java
data: ('HX28483', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestCatalogManagementApi.java', ';', '10/25/18 10:55', ';', 'Id14300b3ee30c03a8325883db4646f269561a8ad')
write pr: HX20770  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestRestExceptionHandler.java
data: ('HX20770', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestRestExceptionHandler.java', ';', '10/9/18 13:18', ';', 'I64f236ccf352294f62923837d2c438ee11df8174')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX27397  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestCharacteristic.java
data: ('HX27397', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestCharacteristic.java', ';', '10/18/18 5:56', ';', 'Ie4b41612ed39e4243c7bebdf78d71521a6a5ba43')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPriceSpecificationVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPriceSpecificationVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX35238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleStateValidationRule.java
data: ('HX35238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleStateValidationRule.java', ';', '11/22/18 8:27', ';', 'Ib102d276c891a06da58ada9c87a4be40498ac8ea')
write pr: HX28483  java: restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestCatalogManagementApi.java
data: ('HX28483', ';', 'restserviceimpl/extendedtraffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/TestCatalogManagementApi.java', ';', '10/25/18 10:55', ';', 'Id14300b3ee30c03a8325883db4646f269561a8ad')
write pr: HX21028  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java
data: ('HX21028', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX20786  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java
data: ('HX20786', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '9/23/18 9:16', ';', 'I72fb985ecf784c8d13ac1813278c69ece041142d')
write pr: BSUC:FT34-18  java: integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/ConfigurationsFirstEntities.java
data: ('BSUC:FT34-18', ';', 'integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/ConfigurationsFirstEntities.java', ';', '9/7/18 12:08', ';', 'Ia86ad76b484e89a7f12cdd6c44b074ac9ab6064d')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/migration/TestScheduleDefinitionDataMigration_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/migration/TestScheduleDefinitionDataMigration_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX20770  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX20770', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '10/9/18 9:17', ';', 'Ifd1a6013e2122d2439df8ad80b8da420391a7d70')
write pr: HX14183  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java
data: ('HX14183', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/RuleBuilderJiveTest.java', ';', '10/9/18 13:50', ';', 'I06fb0a967b35bbba80711bf6293de8108a31fab5')
write pr: HX35238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestProductOfferingLifeCycleStateValidationRule.java
data: ('HX35238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestProductOfferingLifeCycleStateValidationRule.java', ';', '11/22/18 8:27', ';', 'Ib102d276c891a06da58ada9c87a4be40498ac8ea')
write pr: HX21056  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/RuleContext.java
data: ('HX21056', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/RuleContext.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX23275  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX23275', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '10/24/18 8:18', ';', 'I7e1985f059749436f5239f741777c1e164563f3c')
write pr: HX20786  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/loadRegulation/TestInternalRest_LoadRegulation_ITCase.java
data: ('HX20786', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/loadRegulation/TestInternalRest_LoadRegulation_ITCase.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX10271  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/ScenarioTriggeredRuleValidation.java
data: ('HX10271', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/ScenarioTriggeredRuleValidation.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX27740  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/sharingspecification/TestUsedBy.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/sharingspecification/TestUsedBy.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX21416  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java
data: ('HX21416', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionParameters.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionParameters.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX27740  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/bucketdeterminationspecification/SharedBucket.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/bucketdeterminationspecification/SharedBucket.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX36034  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/NetworkPolicyCounterSpecificationVersion.java
data: ('HX36034', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/NetworkPolicyCounterSpecificationVersion.java', ';', '11/27/18 9:12', ';', 'I7581be4045a2c6ab531762efcbc32f47d87b35df')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java

write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/EntityDecorator.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/EntityDecorator.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllValidationRulesAreRegistered.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllValidationRulesAreRegistered.java', ';', '11/16/18 8:16', ';', 'Ic4393d24b8a2f00b9ea43badb7dd7f4c7040451a')
write pr: HX33975  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/NotificationTemplateIdValidationRule.java
data: ('HX33975', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/NotificationTemplateIdValidationRule.java', ';', '11/16/18 14:03', ';', 'Iae0094ba52e457469ecf6b793f45663300398dc5')
write pr: HX36034  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/PolicyRuleType.java
data: ('HX36034', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/PolicyRuleType.java', ';', '11/27/18 9:12', ';', 'I7581be4045a2c6ab531762efcbc32f47d87b35df')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestDisallowSharedBucketInConditionValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestDisallowSharedBucketInConditionValidationRule.java', ';', '11/6/18 13:10', ';', 'I95449c7e77797eb651c436de1432f0cbcd069626')
write pr: HW76061  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/price/MandatoryProductOfferingPriceFieldValidationRule.java
data: ('HW76061', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/price/MandatoryProductOfferingPriceFieldValidationRule.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HW89611  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/billingcyclespecification/TestBillingCycleSpecificationLinkValidationRule.java
data: ('HW89611', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/billingcyclespecification/TestBillingCycleSpecificationLinkValidationRule.java', ';', '8/20/18 13:01', ';', 'I030f5e80fbf7bd40bc85c49fd5abd0775c47a81d')
write pr: HX21209  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/list/TestChargingServiceHelper.java
data: ('HX21209', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/list/TestChargingServiceHelper.java', ';', '9/28/18 12:36', ';', 'I9ae1de55338f306564649be0784d1541fa2cf4c7')
write pr: HX16411  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/helpers/predicate/MovedResourceSpecificationTypePredicate.java
data: ('HX16411', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/helpers/predicate/MovedResourceSpecificationTypePredicate.java', ';', '8/27/18 9:50', ';', 'Ifb96107b78481cb6844c987cc46f916fc8b83352')
write pr: HX30583  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/RemoveLockAnnotationImportProcessor.java
data: ('HX30583', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/RemoveLockAnnotationImportProcessor.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX33974  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/NotificationTemplateViewImpl.java
data: ('HX33974', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/NotificationTemplateViewImpl.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX36034  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/CounterListEntry.java
data: ('HX36034', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/networkpolicycounter/CounterListEntry.java', ';', '11/27/18 9:12', ';', 'I7581be4045a2c6ab531762efcbc32f47d87b35df')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestNotificationTemplateViewImpl.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestNotificationTemplateViewImpl.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX30279  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/StatisticsViewImpl.java
data: ('HX30279', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/StatisticsViewImpl.java', ';', '10/30/18 10:30', ';', 'Iafeeb75bb0abf08084b11987f44bdcd707d5b3da')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX21962  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportWithCreationAndLastModifiedDate.java
data: ('HX21962', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportWithCreationAndLastModifiedDate.java', ';', '9/26/18 9:24', ';', 'I45fd6f5e4934f2aff332f1d4ff387c4f8f0b5931')
write pr: HX21056  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConfigurationDataImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConfigurationDataImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HW76061  java: cobaprovisioner/src/main/java/com/ericsson/bss/rmca/cobaprovisioner/CobaDataProvisioner.java
data: ('HW76061', ';', 'cobaprovisioner/src/main/java/com/ericsson/bss/rmca/cobaprovisioner/CobaDataProvisioner.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX27740  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/recurrenceprioritylist/RecurrenceRanking.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/types/recurrenceprioritylist/RecurrenceRanking.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX20786  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/PbsUomSameAsBaseUomValidationRule.java
data: ('HX20786', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/PbsUomSameAsBaseUomValidationRule.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX19534  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/RelationHelper.java
data: ('HX19534', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/RelationHelper.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntityProvisioner.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntityProvisioner.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX27740  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/PrioritizedBucket.java
data: ('HX27740', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/PrioritizedBucket.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX19534  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/RelationHelper.java
data: ('HX19534', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/RelationHelper.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX33974  java: integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/NotificationTemplateStubView.java
data: ('HX33974', ';', 'integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/NotificationTemplateStubView.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX21209  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX21209', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/28/18 12:36', ';', 'I9ae1de55338f306564649be0784d1541fa2cf4c7')
write pr: HX31479  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateProductOfferingTransaction.java
data: ('HX31479', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateProductOfferingTransaction.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX21028  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX21028', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX18238  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX18238', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18899  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestEntityConverter.java
data: ('HX18899', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/TestEntityConverter.java', ';', '9/12/18 11:00', ';', 'I71009599b90231ce6aba850d6363e305ead306ab')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBusinessSystemConfigurationProvider.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBusinessSystemConfigurationProvider.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX31479  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/TranslationBuilder.java
data: ('HX31479', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/TranslationBuilder.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestBusinessSystemConfigurationEntityProvisioner.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestBusinessSystemConfigurationEntityProvisioner.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HW76061  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HW76061', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX33706  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX33706', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX30583  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/RemoveLockAnnotationImportProcessor.java
data: ('HX30583', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/RemoveLockAnnotationImportProcessor.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestTieredAvailableUnitsHook.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestTieredAvailableUnitsHook.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AbstractSpecification.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AbstractSpecification.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCopyUtils.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCopyUtils.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX21056  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX21056', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestBusinessSystemConfigurationEntityProvisioner.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestBusinessSystemConfigurationEntityProvisioner.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX21209  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java
data: ('HX21209', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java', ';', '9/28/18 12:36', ';', 'I9ae1de55338f306564649be0784d1541fa2cf4c7')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/common/CompiledOption.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/common/CompiledOption.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/resources/pbs/TestProductBucketSpecificationPage_ITCase.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/resources/pbs/TestProductBucketSpecificationPage_ITCase.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX20786  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/PbsUomSameAsBaseUomValidationRule.java
data: ('HX20786', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/PbsUomSameAsBaseUomValidationRule.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/OneTimeChargePolicyEvent.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/OneTimeChargePolicyEvent.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX36034  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java
data: ('HX36034', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/AllowedRuleBehaviorByRuleTypeValidationRule.java', ';', '11/27/18 9:12', ';', 'I7581be4045a2c6ab531762efcbc32f47d87b35df')

data: ('HX29089', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '10/30/18 13:47', ';', 'Id31df18370f4153bee1657435f32cd9b4c61d43e')
write pr: HX36034  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterDetails.java
data: ('HX36034', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/networkpolicycounter/NetworkPolicyCounterDetails.java', ';', '11/27/18 9:12', ';', 'I7581be4045a2c6ab531762efcbc32f47d87b35df')
write pr: HX13089  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/TestEntityAccessHelper.java
data: ('HX13089', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/TestEntityAccessHelper.java', ';', '8/7/18 13:56', ';', 'Iaa614ca2bc96c12a33760840bf4f0e11f890232b')
write pr: HX14183  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeRequires.java
data: ('HX14183', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/TestActionTypeRequires.java', ';', '10/9/18 13:50', ';', 'I06fb0a967b35bbba80711bf6293de8108a31fab5')
write pr: HX33974  java: mavensitegenerator/src/main/java/com/ericsson/bss/rmca/mavensitegenerator/validationrulesdocsgen/ValidationRulesDocsGenerator.java
data: ('HX33974', ';', 'mavensitegenerator/src/main/java/com/ericsson/bss/rmca/mavensitegenerator/validationrulesdocsgen/ValidationRulesDocsGenerator.java', ';', '11/16/18 13:37', ';', 'Iaeef087ad2d93633c7cd06b0ee81916f2a3d2139')
write pr: HX20786  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java
data: ('HX20786', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/testdata/ProductSpecificationBuilder.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/testdata/ProductSpecificationBuilder.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33655  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestSlimCampaign.java
data: ('HX33655', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/TestSlimCampaign.java', ';', '11/15/18 13:08', ';', 'Id6e7962f2cfd89225f144ec694904cbdda71a79f')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX16411  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/helpers/predicate/MovedResourceSpecificationTypePredicate.java
data: ('HX16411', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/helpers/predicate/MovedResourceSpecificationTypePredicate.java', ';', '8/27/18 9:50', ';', 'Ifb96107b78481cb6844c987cc46f916fc8b83352')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX12080  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java
data: ('HX12080', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java', ';', '8/7/18 11:09', ';', 'I6c459763d261e8edd17c18a03a862eed63a2636a')
write pr: BSUC:4B-1  java: integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/ConfigurationsFirstEntities.java
data: ('BSUC:4B-1', ';', 'integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/ConfigurationsFirstEntities.java', ';', '10/2/18 12:08', ';', 'I1a553555f05b9b7c280f07eba588b856ce9589b8')
write pr: HX18899  java: integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/ConfigurationsFirstEntities.java
data: ('HX18899', ';', 'integrationtest/services/src/main/java/com/ericsson/bss/rmca/integrationtest/services/ConfigurationsFirstEntities.java', ';', '9/12/18 11:00', ';', 'I71009599b90231ce6aba850d6363e305ead306ab')
write pr: HX19534  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestRelationHelper.java
data: ('HX19534', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestRelationHelper.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX11847  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/LatestModifiedSpecifications.java
data: ('HX11847', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/LatestModifiedSpecifications.java', ';', '8/16/18 14:06', ';', 'Ia0d1fb61b8971ff68920528fd4df2e4b7b0b7550')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRecurrence.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRecurrence.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX21028  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java
data: ('HX21028', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/export/TestExport_ITCase.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestPsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestPsMustHavePbsIfRelatedBucketReferencesAreFoundValidationRule.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX21337  java: oamservices/trace/src/main/java/com/ericsson/bss/rmca/oamservices/trace/RmcaTrace.java
data: ('HX21337', ';', 'oamservices/trace/src/main/java/com/ericsson/bss/rmca/oamservices/trace/RmcaTrace.java', ';', '9/19/18 8:54', ';', 'I1c454c74741fa8da38cafd9ecc0d555328c0a7c9')
write pr: HW76061  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HW76061', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/resources/babs/TestBillingAccountBucketSpecificationPage_ITCase.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/resources/babs/TestBillingAccountBucketSpecificationPage_ITCase.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX14183  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/UsageGlobalJiveTest.java
data: ('HX14183', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/UsageGlobalJiveTest.java', ';', '10/9/18 13:50', ';', 'I06fb0a967b35bbba80711bf6293de8108a31fab5')
write pr: HX22294  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/filtering/TestScreening.java
data: ('HX22294', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/filtering/TestScreening.java', ';', '10/1/18 9:37', ';', 'I997b7db9cebb67d59647373377a1c6a0d8eaff7e')
write pr: HX33975  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/TestNotificationTemplateIdValidationRule.java
data: ('HX33975', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/TestNotificationTemplateIdValidationRule.java', ';', '11/16/18 14:03', ';', 'Iae0094ba52e457469ecf6b793f45663300398dc5')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33974  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX33974', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '11/16/18 13:37', ';', 'Iaeef087ad2d93633c7cd06b0ee81916f2a3d2139')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX27740  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/sharingspecification/TestRestSharingSpecificationImpl.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/sharingspecification/TestRestSharingSpecificationImpl.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX11847  java: restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/LatestModifiedSpecifications.java
data: ('HX11847', ';', 'restserviceimpl/cus/src/main/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/LatestModifiedSpecifications.java', ';', '8/16/18 14:06', ';', 'Ia0d1fb61b8971ff68920528fd4df2e4b7b0b7550')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX33655  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestProductOfferingLifeCycleFirstTrafficActivationValidationRule.java
data: ('HX33655', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestProductOfferingLifeCycleFirstTrafficActivationValidationRule.java', ';', '11/15/18 13:08', ';', 'Id6e7962f2cfd89225f144ec694904cbdda71a79f')
write pr: BSUC:FT8-96  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/AddLockAnnotationImportProcessor.java
data: ('BSUC:FT8-96', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/processor/AddLockAnnotationImportProcessor.java', ';', '11/26/18 11:00', ';', 'I89f8420156f7d744aa68ad2049395f8bf02d1956')
write pr: HX19843  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/ConditionTemplatesCrudServiceImpl.java
data: ('HX19843', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/ConditionTemplatesCrudServiceImpl.java', ';', '9/12/18 13:24', ';', 'Ib99322642cac28684254a54559ffb46f1bbf79e3')
write pr: HX10271  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/XmlHelper.java
data: ('HX10271', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/XmlHelper.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/predefined/ProductSpecificationPredefinedCharacteristicsResolver.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/predefined/ProductSpecificationPredefinedCharacteristicsResolver.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestDiscountOnProductCharge.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestDiscountOnProductCharge.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX10271  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HX10271', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX20786  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/resources/pbs/ProductBucketSpecificationPage.java
data: ('HX20786', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/resources/pbs/ProductBucketSpecificationPage.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX13306  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX13306', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '8/8/18 8:52', ';', 'I333eb2ba5f74390ab363e4281cea9568467e3e44')
write pr: HW94055  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/TestScenarioTriggered.java
data: ('HW94055', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/scenariotriggered/TestScenarioTriggered.java', ';', '8/24/18 7:15', ';', 'Iaf1a706996929b14af8e6b45a2846d208e68f916')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryImpl.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX21416  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java
data: ('HX21416', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestRuleContextImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/utils/TestSharingSpecificationUtils.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/utils/TestSharingSpecificationUtils.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX20786  java: jivetest/src/main/java/com/ericsson/bss/rmca/jive/testcases/TestBillingManagement.java
data: ('HX20786', ';', 'jivetest/src/main/java/com/ericsson/bss/rmca/jive/testcases/TestBillingManagement.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX21056  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestConfigurationDataImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestConfigurationDataImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX20786  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX20786', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/DisallowSharedBucketInConditionValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/DisallowSharedBucketInConditionValidationRule.java', ';', '10/31/18 15:31', ';', 'I4ab912b756d7650077a6d9ee5bb0879a6952239c')
write pr: HX11438  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX11438', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '8/9/18 13:52', ';', 'Iaf88387774da18722f1d7fedc7749914831e54e4')
write pr: HX12080  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestThatNoUntestedProvisionersAreAdded.java
data: ('HX12080', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestThatNoUntestedProvisionersAreAdded.java', ';', '8/7/18 11:09', ';', 'I6c459763d261e8edd17c18a03a862eed63a2636a')
write pr: HX16411  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java
data: ('HX16411', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/RestListEntityImpl.java', ';', '8/27/18 9:50', ';', 'Ifb96107b78481cb6844c987cc46f916fc8b83352')
write pr: HX13306  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX13306', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '8/8/18 8:52', ';', 'I333eb2ba5f74390ab363e4281cea9568467e3e44')
write pr: HX20786  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/rs/SlimLogicalResourceSpecification.java

write pr: HX33998  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationToPageConverter.java
data: ('HX33998', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationToPageConverter.java', ';', '11/16/18 15:06', ';', 'I76d67cc9b1e97debef8a97ff561180832aafd0e8')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestThatNoUntestedProvisionersAreAdded.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestThatNoUntestedProvisionersAreAdded.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestFunctionControl_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestFunctionControl_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/predefined/ProductSpecificationPredefinedCharacteristicsResolver.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/predefined/ProductSpecificationPredefinedCharacteristicsResolver.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPriceSpecificationVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/ProductOfferingPriceSpecificationVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX30279  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestExportTaskImpl.java
data: ('HX30279', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestExportTaskImpl.java', ';', '10/30/18 7:48', ';', 'If21c4a2830d4ee3083fd231d88280fea1d23fc24')
write pr: HW76061  java: cobaprovisioner/src/main/java/com/ericsson/bss/rmca/cobaprovisioner/CobaDataProvisioner.java
data: ('HW76061', ';', 'cobaprovisioner/src/main/java/com/ericsson/bss/rmca/cobaprovisioner/CobaDataProvisioner.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/DisallowSharedBucketInConditionValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/DisallowSharedBucketInConditionValidationRule.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX21416  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/TestConditionTemplatesCrudServiceImpl.java
data: ('HX21416', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/TestConditionTemplatesCrudServiceImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/AbstractTransactionImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/AbstractTransactionImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX30279  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/statistics/TestStatisticsViewImpl.java
data: ('HX30279', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/statistics/TestStatisticsViewImpl.java', ';', '10/30/18 10:30', ';', 'Iafeeb75bb0abf08084b11987f44bdcd707d5b3da')
write pr: HX25348  java: integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/ChargingCapabilityStubView.java
data: ('HX25348', ';', 'integrationtest/stubs/src/main/java/com/ericsson/bss/rmca/integrationtest/stubs/proxy/ChargingCapabilityStubView.java', ';', '10/11/18 8:53', ';', 'I2a5fd208434c54bceff9397785b3f376c6a0309a')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CopyUtils.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CopyUtils.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX10271  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/ScenarioTriggeredChangeProductStateValidationRule.java
data: ('HX10271', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/ScenarioTriggeredChangeProductStateValidationRule.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/TestNotificationTemplateIdValidationRule.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/TestNotificationTemplateIdValidationRule.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX20770  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java
data: ('HX20770', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java', ';', '10/9/18 9:17', ';', 'Ifd1a6013e2122d2439df8ad80b8da420391a7d70')
write pr: HX30583  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketTagSetUpdateTask.java
data: ('HX30583', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketTagSetUpdateTask.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CopyUtils.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/CopyUtils.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX14183  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/UsageGlobalJiveTest.java
data: ('HX14183', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/UsageGlobalJiveTest.java', ';', '10/9/18 13:50', ';', 'I06fb0a967b35bbba80711bf6293de8108a31fab5')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewImpl.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/EntityDecorator.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/EntityDecorator.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCopyUtils.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCopyUtils.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18238  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/decorator/DecoratorFactory.java
data: ('HX18238', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/decorator/DecoratorFactory.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/AlignedTieredConditionHook.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX12080  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java
data: ('HX12080', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestPredefinedBusinessSystemConfigurationProvider.java', ';', '8/7/18 11:09', ';', 'I6c459763d261e8edd17c18a03a862eed63a2636a')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AtomicProductOfferingPrice.java
data: ('HX18324', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/AtomicProductOfferingPrice.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX20786  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX20786', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX21337  java: oamservices/trace/src/main/java/com/ericsson/bss/rmca/oamservices/trace/RmcaTrace.java
data: ('HX21337', ';', 'oamservices/trace/src/main/java/com/ericsson/bss/rmca/oamservices/trace/RmcaTrace.java', ';', '9/19/18 8:54', ';', 'I1c454c74741fa8da38cafd9ecc0d555328c0a7c9')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/EventTriggerDetailsDecorationProvider.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/EventTriggerDetailsDecorationProvider.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineWrapperFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineWrapperFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX13089  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/EntityAccessHelper.java
data: ('HX13089', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/EntityAccessHelper.java', ';', '8/7/18 13:56', ';', 'Iaa614ca2bc96c12a33760840bf4f0e11f890232b')
write pr: HX30393  java: entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestBlockingValidationError.java
data: ('HX30393', ';', 'entitymodificationviews/src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestBlockingValidationError.java', ';', '10/30/18 12:05', ';', 'I22a3c1a5298f05d608176777246b1dc1541baeb7')
write pr: HX21028  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRecurrence.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestRecurrence.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX23275  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestAmountTypeValidationRule.java
data: ('HX23275', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/TestAmountTypeValidationRule.java', ';', '11/9/18 10:13', ';', 'I3e5a4248204056b12c390420f85b149bf18de628')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestTieredAvailableUnitsHook.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestTieredAvailableUnitsHook.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX21056  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX21028  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java
data: ('HX21028', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX23275  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/AmountTypeValidationRule.java
data: ('HX23275', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/AmountTypeValidationRule.java', ';', '11/9/18 10:13', ';', 'I3e5a4248204056b12c390420f85b149bf18de628')
write pr: HX27740  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/PrioritizedBucket.java
data: ('HX27740', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/bucketprioritylist/PrioritizedBucket.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HX13746  java: restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/JsonConverterBase.java
data: ('HX13746', ';', 'restserviceimpl/traffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/JsonConverterBase.java', ';', '8/14/18 14:28', ';', 'I521b4f876385377b271bc0cc392681ab35bc3254')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestScheduleDefinitionDecoratorProvider.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestScheduleDefinitionDecoratorProvider.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33706  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX33706', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HX20786  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/TestResourceSpecificationValidationRuleProvider.java
data: ('HX20786', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/TestResourceSpecificationValidationRuleProvider.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineWrapperFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineWrapperFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX10271  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/ScenarioTriggeredChangeProductStateValidationRule.java
data: ('HX10271', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/logicalgorithmspecification/ScenarioTriggeredChangeProductStateValidationRule.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX21262  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java
data: ('HX21262', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/RestProductSpecificationPageImpl.java', ';', '10/5/18 12:01', ';', 'I2988af018fba1115f555a4f5c59a9ecd97146afe')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestCharacteristic.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestCharacteristic.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/ActiveFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/ActiveFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Characteristic.java

data: ('HX24580', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestRmref.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX13174  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingPriceSignatureValidationRule.java
data: ('HX13174', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingPriceSignatureValidationRule.java', ';', '8/24/18 5:58', ';', 'I2aedd9ae19ef3b01ae112477bcb3736aa70d1776')
write pr: HX19843  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/CommunityMembershipHook.java
data: ('HX19843', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/CommunityMembershipHook.java', ';', '9/12/18 13:24', ';', 'Ib99322642cac28684254a54559ffb46f1bbf79e3')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntities.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntities.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX21028  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX21028', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestEntityDecorator.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestEntityDecorator.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX29089  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/ProductSpecificationTranslateCharacteristicValidationRule.java
data: ('HX29089', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/ProductSpecificationTranslateCharacteristicValidationRule.java', ';', '10/30/18 13:47', ';', 'Id31df18370f4153bee1657435f32cd9b4c61d43e')
write pr: HX33706  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestCharacteristicSensitiveInfoFieldsValidationRule.java
data: ('HX33706', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestCharacteristicSensitiveInfoFieldsValidationRule.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HX30583  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HX30583', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingVersion.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingVersion.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HW94055  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/VreHelper.java
data: ('HW94055', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/VreHelper.java', ';', '8/24/18 7:15', ';', 'Iaf1a706996929b14af8e6b45a2846d208e68f916')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestNotificationTemplateViewImpl.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestNotificationTemplateViewImpl.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestProductPriorityListGenerator.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestProductPriorityListGenerator.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX21056  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConfigurationDataImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConfigurationDataImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntityProvisioner.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/BusinessSystemConfigurationEntityProvisioner.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX19534  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestRelationHelper.java
data: ('HX19534', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/TestRelationHelper.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX33974  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/NotificationTemplateIdValidationRule.java
data: ('HX33974', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/common/NotificationTemplateIdValidationRule.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX27740  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/helpers/TestSpecificationHelper.java
data: ('HX27740', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/helpers/TestSpecificationHelper.java', ';', '10/31/18 11:31', ';', 'I754207f4177bebd9e26aaf3361d0ab57303f2c30')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/resources/babs/TestBillingAccountBucketSpecificationPage_ITCase.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/pages/resources/babs/TestBillingAccountBucketSpecificationPage_ITCase.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX21056  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/base/TestRmcaException.java
data: ('HX21056', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/base/TestRmcaException.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/migration/TestScheduleDefinitionDataMigration_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/migration/TestScheduleDefinitionDataMigration_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllValidationRulesAreRegistered.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllValidationRulesAreRegistered.java', ';', '11/16/18 13:37', ';', 'Iaeef087ad2d93633c7cd06b0ee81916f2a3d2139')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryImpl.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestQueryImpl.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllSpecificationsHaveSpecificationLevelSignatureRuleRegistered.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllSpecificationsHaveSpecificationLevelSignatureRuleRegistered.java', ';', '11/16/18 13:37', ';', 'Iaeef087ad2d93633c7cd06b0ee81916f2a3d2139')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33998  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationToPageConverter.java
data: ('HX33998', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountSpecificationToPageConverter.java', ';', '11/16/18 15:06', ';', 'I76d67cc9b1e97debef8a97ff561180832aafd0e8')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/ProductSpecificationVersionDefaultCharacteristicsDecorator.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/ProductSpecificationVersionDefaultCharacteristicsDecorator.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX19843  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/ConditionTemplatesCrudServiceImpl.java
data: ('HX19843', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/ConditionTemplatesCrudServiceImpl.java', ';', '9/12/18 13:24', ';', 'Ib99322642cac28684254a54559ffb46f1bbf79e3')
write pr: HX21416  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java
data: ('HX21416', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestTimelineFilter.java', ';', '9/23/18 7:43', ';', 'Icb5ccc2293009bae0aeec96bc171b4d5289d7164')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestUpdateProductOfferingTransaction.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX11847  java: restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/TestLatestModifiedSpecifications.java
data: ('HX11847', ';', 'restserviceimpl/cus/src/test/java/com/ericsson/bss/rmca/restserviceimpl/cus/pages/statistics/TestLatestModifiedSpecifications.java', ';', '8/16/18 14:06', ';', 'Ia0d1fb61b8971ff68920528fd4df2e4b7b0b7550')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestCharacteristic.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestCharacteristic.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX21337  java: restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/CatalogManagementApi.java
data: ('HX21337', ';', 'restserviceimpl/extendedtraffic/src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/CatalogManagementApi.java', ';', '9/19/18 8:54', ';', 'I1c454c74741fa8da38cafd9ecc0d555328c0a7c9')
write pr: HX13089  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/EntityAccessHelper.java
data: ('HX13089', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/accesshelper/EntityAccessHelper.java', ';', '8/7/18 13:56', ';', 'Iaa614ca2bc96c12a33760840bf4f0e11f890232b')
write pr: HX20786  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestCharacteristicPersonalizationValidationRule.java
data: ('HX20786', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestCharacteristicPersonalizationValidationRule.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX21962  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java
data: ('HX21962', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/UpdateTransactionImpl.java', ';', '9/26/18 9:24', ';', 'I45fd6f5e4934f2aff332f1d4ff387c4f8f0b5931')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/services/SlimEventTriggerDetailsForServices.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/services/SlimEventTriggerDetailsForServices.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/utils/ProductSpecificationValidationContextFacade.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/utils/ProductSpecificationValidationContextFacade.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCopyUtils.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestCopyUtils.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HW94170  java: restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TestNetworkPolicyCounterSpecificationAdapter.java
data: ('HW94170', ';', 'restserviceimpl/traffic/src/test/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/TestNetworkPolicyCounterSpecificationAdapter.java', ';', '8/20/18 9:54', ';', 'I20af4e76eca9d9a9fc1f0eb29b8336258a7cbacc')
write pr: BSUC:FT8-96  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/NoLockAllowed.java
data: ('BSUC:FT8-96', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/NoLockAllowed.java', ';', '11/26/18 11:00', ';', 'I89f8420156f7d744aa68ad2049395f8bf02d1956')
write pr: HX33974  java: examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java
data: ('HX33974', ';', 'examples/src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX24614  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBusinessSystemConfigurationProvider.java
data: ('HX24614', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBusinessSystemConfigurationProvider.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/ProductSpecificationPage.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: BSUC:FT34-18  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/ConfigurationResources.java
data: ('BSUC:FT34-18', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/ConfigurationResources.java', ';', '9/7/18 12:08', ';', 'Ia86ad76b484e89a7f12cdd6c44b074ac9ab6064d')
write pr: HX21416  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/ConditionTemplatesCrudServiceImpl.java
data: ('HX21416', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/ConditionTemplatesCrudServiceImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HX33655  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleFirstTrafficActivationValidationRule.java

write pr: HX30583  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX30583', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX21416  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java
data: ('HX21416', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HW76061  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/price/TestMandatoryProductOfferingPriceFieldValidationRule.java
data: ('HW76061', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/price/TestMandatoryProductOfferingPriceFieldValidationRule.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX29089  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestProductSpecificationTranslateCharacteristicValidationRule.java
data: ('HX29089', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productspecification/TestProductSpecificationTranslateCharacteristicValidationRule.java', ';', '10/30/18 13:47', ';', 'Id31df18370f4153bee1657435f32cd9b4c61d43e')
write pr: HX31479  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/TranslationBuilder.java
data: ('HX31479', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/TranslationBuilder.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllValidationRuleProvidersAreRegistered.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/TestThatAllValidationRuleProvidersAreRegistered.java', ';', '11/16/18 8:16', ';', 'Ic4393d24b8a2f00b9ea43badb7dd7f4c7040451a')
write pr: HX18324  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestEntityDecorator.java
data: ('HX18324', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestEntityDecorator.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX21962  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportWithCreationAndLastModifiedDate.java
data: ('HX21962', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportWithCreationAndLastModifiedDate.java', ';', '9/26/18 9:24', ';', 'I45fd6f5e4934f2aff332f1d4ff387c4f8f0b5931')
write pr: HX25348  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/baseconfiguration/TestBaseConfiguration_ITCase.java
data: ('HX25348', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/baseconfiguration/TestBaseConfiguration_ITCase.java', ';', '10/11/18 8:53', ';', 'I2a5fd208434c54bceff9397785b3f376c6a0309a')
write pr: HX21209  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ConsumedServiceUnavailableException.java
data: ('HX21209', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ConsumedServiceUnavailableException.java', ';', '9/28/18 12:36', ';', 'I9ae1de55338f306564649be0784d1541fa2cf4c7')
write pr: HX19534  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimEventTriggerDetails.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/SlimEventTriggerDetails.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX20786  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/TestResourceSpecificationCobaValuesValidationRule.java
data: ('HX20786', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/resourcespecification/TestResourceSpecificationCobaValuesValidationRule.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/ps/TestProductSpecification_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestOneTimeChargeRule.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestOneTimeChargeRule.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/DisallowSharedBucketInConditionValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/DisallowSharedBucketInConditionValidationRule.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX24614  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/AbstractEntityTest.java
data: ('HX24614', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/AbstractEntityTest.java', ';', '10/15/18 9:28', ';', 'I41938b968d24592bb47423e45ca494fa1f606b7a')
write pr: HX24580  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/PoValidationRuleProvider.java
data: ('HX24580', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/PoValidationRuleProvider.java', ';', '10/25/18 7:51', ';', 'Ie646f1b676687dd6036d8570b2bc8ab71e20787f')
write pr: HX31479  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/TranslationBuilder.java
data: ('HX31479', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/TranslationBuilder.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX30583  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketTagSetUpdateTask.java
data: ('HX30583', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestBucketTagSetUpdateTask.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX21056  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java
data: ('HX21056', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/TestRestRuleContextImpl.java', ';', '10/12/18 11:48', ';', 'If729a79ea82b05937785771ea519706930ff1d2e')
write pr: HX21416  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java
data: ('HX21416', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/RestConditionTemplateImpl.java', ';', '10/23/18 8:14', ';', 'I1bde833bbffb62c2a18934eba32c3580190378e8')
write pr: HX21028  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX31479  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestTranslationBuilder.java
data: ('HX31479', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestTranslationBuilder.java', ';', '11/7/18 16:03', ';', 'I8292395dab5b481e5785c489781d7150f487e558')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestPricing.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestPricing.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX10271  java: utilities/src/main/java/com/ericsson/bss/rmca/utilities/XmlHelper.java
data: ('HX10271', ';', 'utilities/src/main/java/com/ericsson/bss/rmca/utilities/XmlHelper.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX33655  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleFirstTrafficActivationValidationRule.java
data: ('HX33655', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleFirstTrafficActivationValidationRule.java', ';', '11/15/18 13:08', ';', 'Id6e7962f2cfd89225f144ec694904cbdda71a79f')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/TimelineBuilder.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX20786  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/InvalidCobaValueException.java
data: ('HX20786', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/InvalidCobaValueException.java', ';', '10/4/18 7:29', ';', 'I4d1a2cd6643cf6f1f19183e5477960090326ed1b')
write pr: HX33655  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/lifecycle/TestSlimLifeCycle.java
data: ('HX33655', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/po/lifecycle/TestSlimLifeCycle.java', ';', '11/15/18 13:08', ';', 'Id6e7962f2cfd89225f144ec694904cbdda71a79f')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestProductSpecificationDecorationProvider.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestProductSpecificationDecorationProvider.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX33706  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HX33706', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '11/20/18 7:48', ';', 'Ia745a9ee858216c2ebd59a404962df25ea1e2141')
write pr: HW76061  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java
data: ('HW76061', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/CoreAbstractTest.java', ';', '8/29/18 12:32', ';', 'Iafd882646c839361913126a8ac70b05386c64b99')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAtomicProductOfferingPrice.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAtomicProductOfferingPrice.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX10271  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java
data: ('HX10271', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/provider/ProductSpecificationValidationRuleProvider.java', ';', '9/6/18 13:06', ';', 'I951d1d6b7048db07b92478ed7adea8f824c01c4a')
write pr: HX21028  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java
data: ('HX21028', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/ImportTaskImpl.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX33974  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestNotificationTemplateViewImpl.java
data: ('HX33974', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/TestNotificationTemplateViewImpl.java', ';', '11/19/18 8:45', ';', 'I4ba09474b8ac04ded754b68742caffc773bcd154')
write pr: HX28161  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/identificationresourcespecification/TestIdentificationResourceSpecificationPageConverter.java
data: ('HX28161', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/identificationresourcespecification/TestIdentificationResourceSpecificationPageConverter.java', ';', '10/19/18 10:59', ';', 'Id3c97fda38f8af8a52a676b1936b36985c69f0f7')
write pr: HX18324  java: entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java
data: ('HX18324', ';', 'entityserviceviews/src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestAbstractSpecification.java', ';', '9/24/18 9:02', ';', 'I0df283cb3dc5db1bdae828ee6ccf8a9d39d659ee')
write pr: HX18238  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestProductSpecificationDecorationProvider.java
data: ('HX18238', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/providers/TestProductSpecificationDecorationProvider.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18899  java: integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java
data: ('HX18899', ';', 'integrationtest/backwardcompatibility/src/test/java/com/ericsson/bss/rmca/integrationtest/backwardcompatibility/TestReadUsingOldVersion_ITCase.java', ';', '9/12/18 11:00', ';', 'I71009599b90231ce6aba850d6363e305ead306ab')
write pr: HX30583  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HX30583', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/ProductSpecificationVersionDefaultCharacteristicsDecorator.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/ProductSpecificationVersionDefaultCharacteristicsDecorator.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX18238  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java
data: ('HX18238', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TransactionFactoryImpl.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX30583  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX30583', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '11/16/18 13:07', ';', 'I309548a8465f02f85d770d81685177d4121e21a9')
write pr: HX18324  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java
data: ('HX18324', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TimelineFilter.java', ';', '9/23/18 11:45', ';', 'I1502cd960d227e1ed2f95fbab3900f99fa4fe807')
write pr: HX21028  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HX21028', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/25/18 11:01', ';', 'I967a8576f79867c9127bfa72417f30dfc6e75579')
write pr: HX19534  java: restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestOneTimeChargeRule.java
data: ('HX19534', ';', 'restserviceimpl/internal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/TestOneTimeChargeRule.java', ';', '10/8/18 10:42', ';', 'I6f7ee17fbf250e06d595c7a6d5c42efe5ca8cc2f')
write pr: HX33974  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleNotificationsValidationRule.java
data: ('HX33974', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/realmspecific/productoffering/ProductOfferingLifeCycleNotificationsValidationRule.java', ';', '11/16/18 8:16', ';', 'Ic4393d24b8a2f00b9ea43badb7dd7f4c7040451a')
write pr: HX18238  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java
data: ('HX18238', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestUseCase_ITCase.java', ';', '9/11/18 9:26', ';', 'Ic7e46381cf8382ddaf2b5e8bcee3d7cd44f2bd1b')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestDisallowSharedBucketInConditionValidationRule.java
data: ('HX24580', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/characteristic/TestDisallowSharedBucketInConditionValidationRule.java', ';', '11/6/18 13:10', ';', 'I95449c7e77797eb651c436de1432f0cbcd069626')
write pr: HX24580  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestTieredAvailableUnitsHook.java

write pr: HV48833  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/baseconfiguration/SilverLine.java
data: ('HV48833', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/baseconfiguration/SilverLine.java', ';', '12/21/16 9:33', ';', 'I2e1b0664597b023267b78f42bcbe6963b6f64f46')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/TheTerminator.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/TheTerminator.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: artf805128  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/HomeLand.java
data: ('artf805128', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/HomeLand.java', ';', '12/2/16 15:32', ';', 'I92e57c4e5cd4c04034889a15b99b0aff62de8267')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/IveGotThePower.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/IveGotThePower.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV46585  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/RollingStones.java
data: ('HV46585', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/RollingStones.java', ';', '12/9/16 11:02', ';', 'Ib42bf72b2c668af549a18c45ed3f41e02c59a538')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/HomeLand.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/HomeLand.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV48833  java: restserviceimpl/src/main/java/com/ericsson/bss/rmca/restserviceimpl/pages/nes/RestNormalizedEventSpecificationPageImpl.java
data: ('HV48833', ';', 'restserviceimpl/src/main/java/com/ericsson/bss/rmca/restserviceimpl/pages/nes/RestNormalizedEventSpecificationPageImpl.java', ';', '12/21/16 9:33', ';', 'I2e1b0664597b023267b78f42bcbe6963b6f64f46')
write pr: HV46251  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketAddRewardHook.java
data: ('HV46251', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketAddRewardHook.java', ';', '12/6/16 8:08', ';', 'Ifdd7caccab8675a8487a2001dd0dfb026bc6dd73')
write pr: HV43940  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/rating/TestRatingCompiledRuleToRmcaEntityConverter.java
data: ('HV43940', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/rating/TestRatingCompiledRuleToRmcaEntityConverter.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/UnderPressure.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/UnderPressure.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV42540  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/BaseConfiguration.java
data: ('HV42540', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/BaseConfiguration.java', ';', '12/6/16 13:14', ';', 'If392fb38022e05ace9aec8d3a031857bd98fff3a')
write pr: HV35910  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/compilers/conditiontemplates/AbstractConditionTemplateCompiler.java
data: ('HV35910', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/compilers/conditiontemplates/AbstractConditionTemplateCompiler.java', ';', '12/13/16 7:44', ';', 'I02b3b488465add68181c127acb065b75550b379d')
write pr: HV43856  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/representation/resourcefacingservicespecification/endusercommunication/EndUserCommunication.java
data: ('HV43856', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/representation/resourcefacingservicespecification/endusercommunication/EndUserCommunication.java', ';', '12/8/16 9:45', ';', 'I21ad6def9d5560318da08956950f59248fe97826')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/WakeMeUpBeforeYouGo.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/WakeMeUpBeforeYouGo.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: artf761321  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/BisValidationRule.java
data: ('artf761321', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/rules/BisValidationRule.java', ';', '12/5/16 9:37', ';', 'I834b5c918cad5f41f3cadc3bf04efd6293e0b3df')
write pr: HV49911  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java
data: ('HV49911', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java', ';', '12/16/16 7:57', ';', 'Iad4b6628f386907f43e8ebb181d5601047e70432')
write pr: HV30905  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/billingManagement/PostPaidBronzeLineConfigurationProvisioning_ITCase.java
data: ('HV30905', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/billingManagement/PostPaidBronzeLineConfigurationProvisioning_ITCase.java', ';', '12/1/16 15:56', ';', 'Id2d9e83148fc8f264ab8f375ecfc88b0116f28e4')
write pr: HV48914  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/NormalizedParameterHook.java
data: ('HV48914', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/NormalizedParameterHook.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV35910  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/rating/TestRatingConditionCompiler.java
data: ('HV35910', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/rating/TestRatingConditionCompiler.java', ';', '12/13/16 7:44', ';', 'I02b3b488465add68181c127acb065b75550b379d')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/DoubleUp.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/DoubleUp.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: artf761321  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/characteristic/NesCharacteristicFlexibleResponseParameterValidation.java
data: ('artf761321', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/characteristic/NesCharacteristicFlexibleResponseParameterValidation.java', ';', '12/5/16 9:37', ';', 'I834b5c918cad5f41f3cadc3bf04efd6293e0b3df')
write pr: HV45913  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ProxyBase.java
data: ('HV45913', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/proxy/ProxyBase.java', ';', '12/2/16 11:37', ';', 'I53ab1c407e04c5dbbffee648a829d44f6518d866')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/AnotherOneBitesTheDust.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/AnotherOneBitesTheDust.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/FirstInLine.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/FirstInLine.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV48833  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGenerator.java
data: ('HV48833', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/ProductPriorityListGenerator.java', ';', '12/21/16 9:33', ';', 'I2e1b0664597b023267b78f42bcbe6963b6f64f46')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/ForeignFriends.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/ForeignFriends.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV44367  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/sd/TestScheduleDefinition_ITCase.java
data: ('HV44367', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/sd/TestScheduleDefinition_ITCase.java', ';', '12/5/16 14:17', ';', 'I423912eac1e7d7ded27d17a648cc55c05703858d')
write pr: HV44367  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/TestScheduleDefinitionDecorator.java
data: ('HV44367', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/TestScheduleDefinitionDecorator.java', ';', '12/5/16 14:17', ';', 'I423912eac1e7d7ded27d17a648cc55c05703858d')
write pr: HV48914  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java
data: ('HV48914', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV46251  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketAddRefillHook.java
data: ('HV46251', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/BucketAddRefillHook.java', ';', '12/6/16 8:08', ';', 'Ifdd7caccab8675a8487a2001dd0dfb026bc6dd73')
write pr: HV30905  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/billingManagement/PostPaidBronzeLine2_0ConfigurationProvisioning_ITCase.java
data: ('HV30905', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/billingManagement/PostPaidBronzeLine2_0ConfigurationProvisioning_ITCase.java', ';', '12/1/16 15:56', ';', 'Id2d9e83148fc8f264ab8f375ecfc88b0116f28e4')
write pr: HV48914  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/refill/RefillConditionTemplateCompiler.java
data: ('HV48914', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/refill/RefillConditionTemplateCompiler.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV48833  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/baseconfiguration/GoldenNugget.java
data: ('HV48833', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/baseconfiguration/GoldenNugget.java', ';', '12/21/16 9:33', ';', 'I2e1b0664597b023267b78f42bcbe6963b6f64f46')
write pr: HV39104  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/SingleSignOnPage.java
data: ('HV39104', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/pages/SingleSignOnPage.java', ';', '11/30/16 15:10', ';', 'I0842109096073e9fde9f3901addd3b0760c37284')
write pr: HV46191  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/baseconfiguration/SampleConfigurationBase.java
data: ('HV46191', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/baseconfiguration/SampleConfigurationBase.java', ';', '12/9/16 13:31', ';', 'I1bfb5509c44fdbb461ec2d16bf4571850b54436e')
write pr: HV48914  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java
data: ('HV48914', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV43856  java: restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/RestSimulator.java
data: ('HV43856', ';', 'restsimulator/src/main/java/com/ericsson/bss/rmca/restsimulator/RestSimulator.java', ';', '12/8/16 9:45', ';', 'I21ad6def9d5560318da08956950f59248fe97826')
write pr: HV44367  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestScheduleDefinitionModification.java
data: ('HV44367', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestScheduleDefinitionModification.java', ';', '12/5/16 14:17', ';', 'I423912eac1e7d7ded27d17a648cc55c05703858d')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/AbstractConfiguration.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/AbstractConfiguration.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: artf761321  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/characteristic/TestBisCharacteristicValidation.java
data: ('artf761321', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/characteristic/TestBisCharacteristicValidation.java', ';', '12/5/16 9:37', ';', 'I834b5c918cad5f41f3cadc3bf04efd6293e0b3df')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/SilverArrow2.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/SilverArrow2.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/TheGreatDivide.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/TheGreatDivide.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV39499  java: restserviceimpl/src/main/java/com/ericsson/bss/rmca/restserviceimpl/pages/EntityUtils.java
data: ('HV39499', ';', 'restserviceimpl/src/main/java/com/ericsson/bss/rmca/restserviceimpl/pages/EntityUtils.java', ';', '12/9/16 10:20', ';', 'I8acb5593a6163d9a12d3146f9a65ffa6d9f0cbd3')
write pr: HV42540  java: selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/DangerZoneJiveTest.java
data: ('HV42540', ';', 'selenium/src/main/java/com/ericsson/bss/rmca/ui/seleniumtest/jive/usecasetests/DangerZoneJiveTest.java', ';', '12/6/16 13:14', ';', 'If392fb38022e05ace9aec8d3a031857bd98fff3a')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/RollingStones.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/RollingStones.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV30905  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/TestPreset_ITCase.java
data: ('HV30905', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/rulebuilder/TestPreset_ITCase.java', ';', '12/1/16 15:56', ';', 'Id2d9e83148fc8f264ab8f375ecfc88b0116f28e4')
write pr: artf761321  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('artf761321', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '12/5/16 9:37', ';', 'I834b5c918cad5f41f3cadc3bf04efd6293e0b3df')
write pr: HV44367  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateTransactionImpl.java
data: ('HV44367', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CreateTransactionImpl.java', ';', '12/5/16 14:17', ';', 'I423912eac1e7d7ded27d17a648cc55c05703858d')
write pr: HV43940  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/recurrence/RecurrenceCompiledRuleToRmcaEntityConverter.java
data: ('HV43940', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/recurrence/RecurrenceCompiledRuleToRmcaEntityConverter.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/Stairway.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/Stairway.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/WeAreFamily.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/WeAreFamily.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV46251  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/RatingHookUtils.java
data: ('HV46251', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/actions/RatingHookUtils.java', ';', '12/6/16 8:08', ';', 'Ifdd7caccab8675a8487a2001dd0dfb026bc6dd73')
write pr: HV48914  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/NormalizedParameterHook.java
data: ('HV48914', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/conditions/NormalizedParameterHook.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV48914  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java
data: ('HV48914', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/hooks/TestNormalizedParameterHook.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV47493  java: restserviceimpl/src/test/java/com/ericsson/bss/rmca/restserviceimpl/api/adapter/TestApiHelper.java
data: ('HV47493', ';', 'restserviceimpl/src/test/java/com/ericsson/bss/rmca/restserviceimpl/api/adapter/TestApiHelper.java', ';', '12/6/16 15:51', ';', 'I1588a096575c622e4be1bd4e3097dc220e6dc06b')
write pr: HV44367  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/testdata/VersioningTestDataCreator.java
data: ('HV44367', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/testdata/VersioningTestDataCreator.java', ';', '12/5/16 14:17', ';', 'I423912eac1e7d7ded27d17a648cc55c05703858d')

write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/GotToGet.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/GotToGet.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/DangerZone.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/DangerZone.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: HV39499  java: restserviceimpl/src/main/java/com/ericsson/bss/rmca/restserviceimpl/pages/ps/RestProductSpecificationPageImpl.java
data: ('HV39499', ';', 'restserviceimpl/src/main/java/com/ericsson/bss/rmca/restserviceimpl/pages/ps/RestProductSpecificationPageImpl.java', ';', '12/9/16 10:20', ';', 'I8acb5593a6163d9a12d3146f9a65ffa6d9f0cbd3')
write pr: artf761321  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/relationtorules/TestBillingCycleSpecificationLinkValidation.java
data: ('artf761321', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/relationtorules/TestBillingCycleSpecificationLinkValidation.java', ';', '12/5/16 9:37', ';', 'I834b5c918cad5f41f3cadc3bf04efd6293e0b3df')
write pr: HV48914  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/refill/RefillConditionTemplateCompiler.java
data: ('HV48914', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/refill/RefillConditionTemplateCompiler.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HV43940  java: testdata/src/main/java/com/ericsson/bss/rmca/testdata/FunkyFamily.java
data: ('HV43940', ';', 'testdata/src/main/java/com/ericsson/bss/rmca/testdata/FunkyFamily.java', ';', '12/1/16 8:39', ';', 'I0334d96618d5f700a3599c944846ec29176696ec')
write pr: artf761321  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('artf761321', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '12/5/16 9:37', ';', 'I834b5c918cad5f41f3cadc3bf04efd6293e0b3df')
write pr: HV48914  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/refill/RefillConditionTemplateCompiler.java
data: ('HV48914', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/rulebuilder/packages/refill/RefillConditionTemplateCompiler.java', ';', '12/12/16 12:36', ';', 'I18262db2c74921e907f8e5ce3248962dc98ed08d')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/EventTriggerDetailsValidationRuleProvider.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/EventTriggerDetailsValidationRuleProvider.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/BucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/EventTriggerDetailsValidationRuleProvider.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/EventTriggerDetailsValidationRuleProvider.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/AggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/PolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java
data: ('HZ49620', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/bucketlimits/TestBucketLimitsProvider.java', ';', '11/16/21 12:21', ';', 'Ib6c29fc79da077a7e0b0447241ede90a53bbb70c')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/eventtriggerdetails/TestAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:21', ';', 'Ia5ffa245266ba3fd05d4790d7b8af1b3fef7a538')
write pr: HZ49620  java: validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java
data: ('HZ49620', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/validation/rules/realmspecific/policyvalue/TestPolicyValueAggregatedBucketsNotAllowedInConditionsValidationRule.java', ';', '11/16/21 12:32', ';', 'Ib12dc9806952dfa38caaadcd5d9e63ceb1789d2b')
write pr: HZ49620  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/PolicyValueValidationRuleProvider.java

write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskImpl.java', ';', '6/3/19 9:06', ';', 'I37bdbfc1e3f0d67251de9be302d2bf191c5f4e4d')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/PopsBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY58386  java: integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestNormalizedParameter.java
data: ('HY58386', ';', 'integrationtest/componenttestcases/src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rulebuilder/preset/conditionconverter/local/TestNormalizedParameter.java', ';', '8/25/20 14:07', ';', 'If5d8685d5a7befa0bac58749fa2dcaeb3d099302')
write pr: HY47676  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductOfferingValidationRuleProvider.java
data: ('HY47676', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/ProductOfferingValidationRuleProvider.java', ';', '6/19/20 18:35', ';', 'I0ce4c0ee035aa3c7f6d642ff7180c855de4aa0a6')
write pr: HY38940  java: entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationsFrom.java
data: ('HY38940', ';', 'entityserviceimpl/src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/RelationsFrom.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: BSUC:FT8-15  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListManagement.java
data: ('BSUC:FT8-15', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/ProductPriorityListManagement.java', ';', '7/27/20 8:52', ';', 'Id0e64e935b823efb860306c52e4f8d2b69db0bbe')
write pr: HY64562  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY64562', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '9/28/20 11:33', ';', 'I0e88e00e1a2af44c7314ff3b4086d8138cbe69d5')
write pr: HY53290  java: configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java
data: ('HY53290', ';', 'configurationprovisioner/src/main/java/com/ericsson/bss/rmca/configurationprovisioner/PriorityListProvisioner.java', ';', '8/12/20 11:47', ';', 'I28911d54f4be42e28eea90fb8c5684c83ee4e5ed')
write pr: HY48964  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java
data: ('HY48964', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/decorator/decorators/AbstractBucketTagReferenceCharacteristicsDecoration.java', ';', '7/3/20 17:22', ';', 'If9e207632ca12d65682419b63d8d95dc4a76dbcd')
write pr: HY53290  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java
data: ('HY53290', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestPriorityListCleaner.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY62458  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicValuesRegistry.java
data: ('HY62458', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/CharacteristicValuesRegistry.java', ';', '9/22/20 10:41', ';', 'If9dd66370e0eaae973e30d1aefcc49177159b0a6')
write pr: HX80786  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/TestRequestCertificateValidator.java
data: ('HX80786', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/validation/TestRequestCertificateValidator.java', ';', '7/29/19 14:02', ';', 'I9812b225e924ad59d835a15918580426466aa3e9')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/TestBaseEntityDependencyPopulationImpl.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/TestBaseEntityDependencyPopulationImpl.java', ';', '5/27/19 11:03', ';', 'I8d084039653f90ac086796b5fca3a83d75178445')
write pr: HY53290  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntityTypeKeys.java
data: ('HY53290', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntityTypeKeys.java', ';', '8/13/20 10:10', ';', 'I3f29f482bc8388074283ba83baa978d8360d7768')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/event/consumer/prioritylistmanagement/BasPriorityListManagement.java', ';', '8/14/20 12:04', ';', 'I69ec8a7584ff72de6b54a400861d26c03a789254')
write pr: HX90744  java: restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/HTMLEncoder.java
data: ('HX90744', ';', 'restserviceimpl/base/src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/filter/xss/HTMLEncoder.java', ';', '10/2/19 8:03', ';', 'I1978331c622e6a4ebba07912602dab0b6122aee1')
write pr: HY51063  java: restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java
data: ('HY51063', ';', 'restproxy/impl/src/test/java/com/ericsson/bss/rmca/restproxy/impl/internal/cpmproxy/converter/CpmCpiContract.java', ';', '7/17/20 14:03', ';', 'I83275cdb0a5acbcbd563533488ec4f6a26367625')
write pr: HY38940  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/TestSupplementaryEntityAccessHelper.java
data: ('HY38940', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/TestSupplementaryEntityAccessHelper.java', ';', '6/3/20 13:31', ';', 'Icb45255c191c2d3f08c348e92067d848034159a8')
write pr: HY69943  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestPriorityListUpdateHelper.java
data: ('HY69943', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/TestPriorityListUpdateHelper.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HX98025  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/BaseEntityDependencyPopulationImpl.java
data: ('HX98025', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/dependency/BaseEntityDependencyPopulationImpl.java', ';', '10/25/19 5:56', ';', 'Id423f5b8b61ba3ce1d6fcdcecd0ff974793fee28')
write pr: HY52064  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java
data: ('HY52064', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/sendvoiceannouncement/TestSendVoiceAnnouncementProvider.java', ';', '7/28/20 11:42', ';', 'I6cd6688b469a9e29c46c441c321d8b21774ee752')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/SingleValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/SingleValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY51063  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java
data: ('HY51063', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicCustomPurposeValidationRule.java', ';', '8/3/20 9:36', ';', 'I8d1f7b2d9ee1f0042166af77f1e629a5998dd65f')
write pr: HY15429  java: entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java
data: ('HY15429', ';', 'entityserviceviews/src/main/java/com/ericsson/bss/rmca/entityserviceviews/base/ErrorCode.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY66576  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/SetFixedFeeTemplateConverter.java
data: ('HY66576', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setfee/SetFixedFeeTemplateConverter.java', ';', '11/3/20 12:59', ';', 'I4f756c767cd115ef25d821b3497e81046d5494dc')
write pr: HX91715  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedTagSetSpecificationProvisioner.java
data: ('HX91715', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedTagSetSpecificationProvisioner.java', ';', '10/2/19 15:13', ';', 'I5573ba7262fd473417a289056786690f7436f067')
write pr: HY38940  java: entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java
data: ('HY38940', ';', 'entityserviceimpl/src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/TestViewFactoryImpl.java', ';', '6/3/20 13:31', ';', 'I77576068cb6fb2e12e7d7e56d02f92fe1b096dd5')
write pr: HY39972  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java
data: ('HY39972', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/pages/ps/DiscountOnProductCharge.java', ';', '4/30/20 6:15', ';', 'I629f4a47960687b6a4fa395c674aad8b654a8c16')
write pr: HX99751  java: restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestRestExceptionHandler.java
data: ('HX99751', ';', 'restserviceimpl/base/src/test/java/com/ericsson/bss/rmca/restserviceimpl/base/TestRestExceptionHandler.java', ';', '11/7/19 9:03', ';', 'I334ec6690e885b1e3372a5c0f005445799a29357')
write pr: BSUC:FT8-15:4  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ErrorMapKey.java
data: ('BSUC:FT8-15:4', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ErrorMapKey.java', ';', '7/27/20 6:54', ';', 'I0d6c6f576cb0813ff8bb9bc9f0dbd085ead415a0')
write pr: HY69943  java: utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestBucketPriorityListFiltererFactory.java
data: ('HY69943', ';', 'utilities/src/test/java/com/ericsson/bss/rmca/utilities/entity/prioritylistmanagement/filtering/TestBucketPriorityListFiltererFactory.java', ';', '10/29/20 10:27', ';', 'I4e874c4d22ee8a610b40d617fe8f416e5130b569')
write pr: HY59800  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java
data: ('HY59800', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/billingaccountspecification/TestBillingAccountBucketPriorityListToPageConverter.java', ';', '10/29/20 8:28', ';', 'I7474b823442a3ef9b2de35ad45ceba91b9760f77')
write pr: HY24973  java: restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/RelativeSharingLimitFilter.java
data: ('HY24973', ';', 'restserviceimpl/internal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/list/filter/with/RelativeSharingLimitFilter.java', ';', '2/5/20 13:15', ';', 'Ied8cca294197f65fdec96d1b2200ef62b5aa0a38')
write pr: HY35363  java: importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/TestContractSpecificationVersionImportValidator.java
data: ('HY35363', ';', 'importexport/impl/src/test/java/com/ericsson/bss/rmca/importexport/impl/entityimporter/externalimport/TestContractSpecificationVersionImportValidator.java', ';', '4/3/20 12:07', ';', 'Idc1d5442147a3362f78678e36589b171570c7583')
write pr: HX70206  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java
data: ('HX70206', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/importexport/TestImportTaskValidator.java', ';', '6/3/19 9:06', ';', 'I37bdbfc1e3f0d67251de9be302d2bf191c5f4e4d')
write pr: HX94272  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java
data: ('HX94272', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/TestNotificationHook.java', ';', '10/9/19 12:53', ';', 'Iec41389cc0a2a3261d31bb5bbcf04a6b552d68c1')
write pr: HY65926  java: restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setthresholdscenario/TestSetThresholdScenarioConverter.java
data: ('HY65926', ';', 'restserviceimpl/restinternal/src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/action/setthresholdscenario/TestSetThresholdScenarioConverter.java', ';', '10/5/20 9:30', ';', 'I8f82135218b73e7df4ddcb1a3a75f52324e1ab78')
write pr: HY42535  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/RefillRuleListEntry.java
data: ('HY42535', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/listpages/rule/refill/RefillRuleListEntry.java', ';', '5/25/20 7:11', ';', 'I0a261b3544a27b878a527f917baf90508e444eb6')
write pr: HX92381  java: entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestSendTransactionNotificationTask.java
data: ('HX92381', ';', 'entitymodificationimpl/src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestSendTransactionNotificationTask.java', ';', '9/26/19 14:23', ';', 'I9f8a674f3f3862391e5eba16e40f650149c284ab')
write pr: HY53290  java: entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java
data: ('HY53290', ';', 'entitymodificationimpl/src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/CascadingDeactivateTransactionImpl.java', ';', '8/14/20 12:55', ';', 'I5cd1d7f4fa9712e18268163bcf8eb47320f94e9d')
write pr: HY15429  java: entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java
data: ('HY15429', ';', 'entitymodificationviews/src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java', ';', '12/18/19 17:45', ';', 'Ib1c0021ceaa73836ddf8150dcce410b20b097d8f')
write pr: HY59766  java: validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java
data: ('HY59766', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/UnsupportedValue.java', ';', '9/9/20 7:01', ';', 'Ibe9afb468806ba06a8aa7b84b56821239545917c')
write pr: HY65732  java: integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java
data: ('HY65732', ';', 'integrationtest/testcases/src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogBusinessConfigurationUtility/export/TestImportExport_ITCase.java', ';', '10/2/20 8:26', ';', 'Ia423aa41d7b3b6e4242c7c02eb2cb65a6cc7b3d0')
write pr: HY53290  java: persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/BasePersistenceFactoryImpl.java
data: ('HY53290', ';', 'persistenceimpl/src/main/java/com/ericsson/bss/rmca/persistenceimpl/BasePersistenceFactoryImpl.java', ';', '8/13/20 10:10', ';', 'I3f29f482bc8388074283ba83baa978d8360d7768')
write pr: HY69751  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/ScheduleDefinitionPageConverter.java
data: ('HY69751', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/scheduledefinition/ScheduleDefinitionPageConverter.java', ';', '10/30/20 15:47', ';', 'If2bb29b073b4090995afd493fd5dd11db3b5b956')
write pr: HY65601  java: validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestCompareValuesHook.java
data: ('HY65601', ';', 'validation/src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/hooks/conditions/normalizedparameter/TestCompareValuesHook.java', ';', '10/5/20 12:19', ';', 'I4b643b6094bf5501295e184f5bb1e3899be343f3')
write pr: HY17547  java: validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/converters/AbstractCompiledRuleToRmcaEntityConverter.java
data: ('HY17547', ';', 'validation/src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/converters/AbstractCompiledRuleToRmcaEntityConverter.java', ';', '12/18/19 17:09', ';', 'I025191e59d2d79e20947134d37fa514325360b68')
write pr: HX87622  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/BucketPriorityListToPageConverter.java
data: ('HX87622', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/buckettag/BucketPriorityListToPageConverter.java', ';', '9/2/19 14:26', ';', 'I918005d5474780183d563e4b6ac1ed4b7c50f5b8')
write pr: HY33683  java: restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java
data: ('HY33683', ';', 'restserviceimpl/restinternal/src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/agreementspecification/AgreementSpecificationPageConverter.java', ';', '3/25/20 11:55', ';', 'I097f13d8eacbfcb1be15b160dfbcf24b8d563727')

0        None
1        None
2        None
3        None
4        None
         ...
20396    None
20397    None
20398    None
20399    None
20400    None
Length: 19479, dtype: object

In [66]:
df_fn_filtered3 = pd.DataFrame(files_list3)
files_list3 = []

In [67]:
df_fn_filtered3.to_csv( PR3_csv, encoding='utf-8', header=False, index=False, sep='\t' )

In [68]:
import numpy as np
np.savetxt( PR3_txt, df_fn_filtered3.values, fmt='%s', delimiter=' ' )

In [69]:
df_fn_filtered3.head()

,0,1,2,3,4,5,6
0,HX90744,;,restserviceimpl/base/src/main/java/com/ericsso...,;,10/2/19 8:03,;,I1978331c622e6a4ebba07912602dab0b6122aee1
1,HX91715,;,entitymodificationimpl/src/test/java/com/erics...,;,10/2/19 15:13,;,I5573ba7262fd473417a289056786690f7436f067
2,HY60437,;,integrationtest/componenttestcases/src/test/ja...,;,9/4/20 6:08,;,I69cfd57a14355f01285abe37f29243e56d81f62a
3,HY18902,;,integrationtest/componenttestcases/src/test/ja...,;,1/14/20 13:35,;,I2b897fa224f045af30aa06cd201b2205e856ab7e
4,HX86471,;,entitymodificationimpl/src/main/java/com/erics...,;,9/2/19 12:30,;,Ie1f272531a90eb5d9df20f0a5a3506da059e9c57

In [70]:
df_fn_filtered3.shape

(13887, 7)

In [53]:
#authorFilePath.to_csv( fileNameOutput, encoding='utf-8', index=False)

In [54]:
#authorFilePath.to_csv( PR3_csv, encoding='utf-8', header=False, index=False, sep='\t')

In [55]:
#import numpy as np
#np.savetxt( PR3_txt, authorFilePath.values, fmt='%s', delimiter=' ')